Repository scalableminds/webknossos, pull requests merged in 2018-06, with the labels that each got.

#2650 Send protobuf tracing to frontend instead of json
  .babelrc
  .flowconfig
  app/assets/flow/ProtoFlowStub.js.flow
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/helpers/generate_dummy_trees.js
  app/assets/javascripts/oxalis/model/helpers/proto_helpers.js
  app/assets/javascripts/oxalis/model/reducers/reducer_helpers.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  app/models/binary/DataStoreHandler.scala
  package.json
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/TracingController.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
  webpack.config.js
  yarn.lock
Labels: backend-easy, enhancement, frontend

#2663 Toast for h and g keyboard shortcuts
  app/assets/javascripts/admin/help/keyboardshortcut_view.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/combinations/volumetracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
Labels: enhancement, frontend

#2673 Fix node selection & 3d viewport rotation/zooming & shortcuts
  app/assets/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/combinations/volumetracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/view/input_catcher.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
  app/assets/javascripts/oxalis/view/plane_view.js
Labels: bug, frontend

#2671 fix extractReleaseNotes script
  tools/extractReleaseNotes.js
Labels: low-hanging-fruit

#2682 Fix CORS header for health check request
  app/assets/javascripts/admin/datastore_health_check.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Application.scala
Labels: bug

#2689 Fix renaming of trees with no name
  app/assets/javascripts/oxalis/model/sagas/skeletontracing_saga.js
Labels: bug, frontend, urgent

#2690 Hotfix bucket loading order for ortho mode
  app/assets/javascripts/oxalis/model/binary.js
Labels: bug, frontend

#2681 Rename binary to data_layer
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller/combinations/volumetracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/geometries/materials/abstract_plane_material_factory.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/arbitrary_cube_adapter.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bounding_box.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_builder.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/flight_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/oblique_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_traversals.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/data_cube.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/data_rendering_logic.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/mappings.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/ping_strategy.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/ping_strategy_3d.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/polyhedron_rasterizer.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/pullqueue.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/pushqueue.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/temporal_bucket_manager.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/texture_bucket_manager.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
  app/assets/javascripts/oxalis/model/data_connection_info.js
  app/assets/javascripts/oxalis/model/data_layer.js
  app/assets/javascripts/oxalis/model/sagas/update_actions.js
  app/assets/javascripts/oxalis/model/sagas/volumetracing_saga.js
  app/assets/javascripts/oxalis/view/right-menu/mapping_info_view.js
  app/assets/javascripts/oxalis/view/right_menu_view.js
  app/assets/javascripts/test/api/api_skeleton_latest.spec.js
  app/assets/javascripts/test/api/api_v2.spec.js
  app/assets/javascripts/test/api/api_volume_latest.spec.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  app/assets/javascripts/test/model/binary/cube.spec.js
  app/assets/javascripts/test/model/binary/data_rendering_logic.spec.js
  app/assets/javascripts/test/model/binary/layers/wkstore_adapter.spec.js
  app/assets/javascripts/test/model/binary/pullqueue.spec.js
  app/assets/javascripts/test/model/binary/temporal_bucket_manager.spec.js
  app/assets/javascripts/test/model/collisions.spec.js
  app/assets/javascripts/test/model/model.spec.js
Labels: frontend

#2693 Respect packing degree of segmentation layer in shader
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model/binary/data_rendering_logic.js
Labels: frontend

#2696 Fix DataSets update query for zero-datasets case
  app/models/binary/DataSet.scala
Labels: backend, backend-easy, bug

#2701 Ensure that only buckets for existing zoom steps are pulled
  app/assets/javascripts/oxalis/model/binary.js
Labels: bug

#2704 annotate foreign-key sql evolution
  conf/evolutions/012-add-foreign-keys.sql
Labels: backend

#2637 upgrade grpc and use new fossildb standard health check
  .circleci/config.yml
  docker-compose.yml
  fossildb/version
  package.json
  project/Dependencies.scala
  project/plugins.sbt
  test/infrastructure/deployment.bash
  util/src/main/scala/com/scalableminds/util/rpc/RPCRequest.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Application.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Controller.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/TracingController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/FossilDBClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/TracingDataStore.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/TracingService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/UpdateActions.scala
Labels: backend, enhancement

#2687 Refactor ping (prefetch) functionality
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_arbitrary.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_plane.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/pullqueue.js
  app/assets/javascripts/oxalis/model/data_layer.js
  app/assets/javascripts/oxalis/model/sagas/prefetch_saga.js
  app/assets/javascripts/oxalis/model/sagas/root_saga.js
  app/assets/javascripts/test/sagas/prefetch_saga.spec.js
Labels: frontend

#2709 Decrease shader compilation time
  app/assets/javascripts/oxalis/constants.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
Labels: enhancement, frontend

#2714 create workaround route to trigger Initial Data Insertion (scmboy)
  app/Global.scala
  app/controllers/InitialDataController.scala
  conf/messages
  conf/webknossos.routes
Labels: backend, bug

#2723 fix: when admin creates explorative on dataset with no allowed teams, use orga team
  app/models/annotation/AnnotationService.scala
Labels: backend, bug

#2672 backend refactoring: merge Project and ProjectSQL
  app/controllers/AnnotationIOController.scala
  app/controllers/Controller.scala
  app/controllers/InitialDataController.scala
  app/controllers/ProjectController.scala
  app/controllers/ReportController.scala
  app/controllers/TaskController.scala
  app/controllers/WKDataStoreController.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/handler/ProjectInformationHandler.scala
  app/models/annotation/handler/TaskInformationHandler.scala
  app/models/project/Project.scala
  app/models/task/Task.scala
  app/models/task/TaskService.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/thirdparty/BrainTracing.scala
Labels: backend, refactoring

#2713 Disable uglifyJS compress functionality
  webpack.config.js
Labels: frontend

#2726 Fix segmentation tab
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller/combinations/volumetracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/model/binary/data_cube.js
  app/assets/javascripts/oxalis/view/right-menu/mapping_info_view.js
Labels: frontend

#2733 only use xyz components of segmentation id to check for zero
  app/assets/javascripts/oxalis/shaders/main_data_fragment.glsl.js
Labels: bug, frontend

#2734 clearer message if task assignment fails due to dataset access rights
  app/models/annotation/AnnotationMutations.scala
  app/models/annotation/AnnotationService.scala
Labels: backend, enhancement

#2715 Improve warning-toasts regarding segmentation
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/accessors/volumetracing_accessor.js
  app/assets/javascripts/oxalis/model/sagas/annotation_saga.js
  app/assets/javascripts/oxalis/model/sagas/root_saga.js
Labels: frontend

#2736 Fix task list in Firefox for low x resolutions (#2708)
  app/assets/javascripts/dashboard/dashboard_task_list_view.js
Labels: enhancement, frontend

#2676 refactor backend: merge Task and TaskSQL
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Dashboard.scala
  app/controllers/ProjectController.scala
  app/controllers/ScriptsController.scala
  app/controllers/StatisticsController.scala
  app/controllers/TaskController.scala
  app/controllers/TaskTypeController.scala
  app/controllers/TimeController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/handler/ProjectInformationHandler.scala
  app/models/annotation/handler/TaskInformationHandler.scala
  app/models/annotation/handler/TaskTypeInformationHandler.scala
  app/models/task/CompletionStatus.scala
  app/models/task/Task.scala
  app/models/task/TaskService.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/thirdparty/BrainTracing.scala
  app/utils/SQLHelpers.scala
Labels: backend, refactoring

#2735 Use toast key to update existing toasts
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/libs/toast.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/pushqueue.js
  app/assets/javascripts/oxalis/model/sagas/annotation_saga.js
  app/assets/javascripts/oxalis/model/sagas/save_saga.js
  app/assets/javascripts/oxalis/view/action-bar/share_modal_view.js
Labels: enhancement, frontend

#2740 don’t run the periodic cleanup jobs on shutdown (where they failed)
  app/oxalis/cleanup/CleanupService.scala
Labels: backend, enhancement

#2745 add optional width and height params to thumbnail api. increase default to 400x400
  app/controllers/DataSetController.scala
  conf/webknossos.routes
  util/src/main/scala/com/scalableminds/util/tools/Math.scala
Labels: backend, enhancement

#2749 Avoid suboptimal bucket loading sequence for initial loading of dataset
  app/assets/javascripts/oxalis/model/data_layer.js
Labels: frontend

#2677 Refactor Backend: merge Annotation and AnnotationSQL
  app/Global.scala
  app/assets/javascripts/test/backend-snapshot-tests/annotations.e2e.js
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Dashboard.scala
  app/controllers/ProjectController.scala
  app/controllers/StatisticsController.scala
  app/controllers/TaskController.scala
  app/controllers/UserController.scala
  app/controllers/UserTokenController.scala
  app/controllers/WKDataStoreController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationIdentifier.scala
  app/models/annotation/AnnotationInformationProvider.scala
  app/models/annotation/AnnotationMerger.scala
  app/models/annotation/AnnotationMutations.scala
  app/models/annotation/AnnotationRestrictions.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/AnnotationStore.scala
  app/models/annotation/AnnotationType.scala
  app/models/annotation/TemporaryAnnotationStore.scala
  app/models/annotation/handler/AnnotationInformationHandler.scala
  app/models/annotation/handler/ProjectInformationHandler.scala
  app/models/annotation/handler/SavedTracingInformationHandler.scala
  app/models/annotation/handler/TaskInformationHandler.scala
  app/models/annotation/handler/TaskTypeInformationHandler.scala
  app/models/annotation/nml/NmlWriter.scala
  app/models/binary/DataSet.scala
  app/models/task/Task.scala
  app/models/team/Organization.scala
  app/models/team/Team.scala
  app/models/user/time/TimeSpan.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/thirdparty/BrainTracing.scala
Labels: backend, refactoring

#2750 Improve some flow types and integrate Enumjs
  .flowconfig
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/router.js
  package.json
  yarn.lock
Labels: frontend

#2758 allow teammanagers to create explorationals on datasets without allowed teams
  app/models/annotation/AnnotationService.scala
Labels: backend, bug

#2759 Fix project link
  app/assets/javascripts/admin/project/project_list_view.js
  app/assets/javascripts/router.js
Labels: bug, frontend

#2769 Fix link from tasks list to task type
  app/assets/javascripts/admin/tasktype/task_type_list_view.js
  app/assets/javascripts/router.js
Labels: bug, frontend

#2768 in progress report, hide old paused projects even if they have open instances
  app/controllers/ReportController.scala
Labels: backend, enhancement

#2766 Render error chain in toast if provided
  app/assets/javascripts/libs/toast.js
  app/assets/stylesheets/main.less
Labels: enhancement, frontend

#2743 Test that empty trees are properly renamed and then persisted
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/admin/task/task_list_view.js
  app/assets/javascripts/dashboard/explorative_annotations_view.js
  app/assets/javascripts/libs/template_helpers.js
  app/assets/javascripts/oxalis/model/actions/task_actions.js
  app/assets/javascripts/test/fixtures/skeletontracing_server_objects.js
  app/assets/javascripts/test/fixtures/tasktracing_server_objects.js
  app/assets/javascripts/test/fixtures/volumetracing_server_objects.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  app/assets/javascripts/test/helpers/saveHelpers.js
  app/assets/javascripts/test/sagas/saga_integration.spec.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  app/models/project/Project.scala
  app/models/task/Task.scala
Labels: frontend, testing

#2751 Refactor Model Part 3: Resolutions and model initialization
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/accessors/dataset_accessor.js
  app/assets/javascripts/oxalis/model/accessors/flycam_accessor.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bounding_box.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/flight_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/oblique_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/data_cube.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/mappings.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_plane.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/pullqueue.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
  app/assets/javascripts/oxalis/model/data_layer.js
  app/assets/javascripts/oxalis/model/helpers/reduce_reducers.js
  app/assets/javascripts/oxalis/model/reducers/reducer_helpers.js
  app/assets/javascripts/oxalis/model/sagas/prefetch_saga.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/test/fixtures/volumetracing_server_objects.js
  app/assets/javascripts/test/model/binary/cube.spec.js
  app/assets/javascripts/test/model/binary/layers/wkstore_adapter.spec.js
  app/assets/javascripts/test/model/binary/pullqueue.spec.js
  app/assets/javascripts/test/model/flycam_accessors.spec.js
  app/assets/javascripts/test/model/model.spec.js
  app/assets/javascripts/test/sagas/prefetch_saga.spec.js
Labels: frontend, refactoring

#2760 Refactor Model Part 4: Slim model.js and reduce dependencies on DataLayer class
  app/Global.scala
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller/camera_controller.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/accessors/dataset_accessor.js
  app/assets/javascripts/oxalis/model/accessors/skeletontracing_accessor.js
  app/assets/javascripts/oxalis/model/accessors/volumetracing_accessor.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/mappings.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_plane.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
  app/assets/javascripts/oxalis/model/data_layer.js
  app/assets/javascripts/oxalis/model/sagas/prefetch_saga.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/test/api/api_skeleton_latest.spec.js
  app/assets/javascripts/test/api/api_v2.spec.js
  app/assets/javascripts/test/backend-snapshot-tests/annotations.e2e.js
  app/assets/javascripts/test/model/binary/layers/wkstore_adapter.spec.js
  app/assets/javascripts/test/model/model.spec.js
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Dashboard.scala
  app/controllers/DataSetController.scala
  app/controllers/ProjectController.scala
  app/controllers/StatisticsController.scala
  app/controllers/TaskController.scala
  app/controllers/UserController.scala
  app/controllers/UserTokenController.scala
  app/controllers/WKDataStoreController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationIdentifier.scala
  app/models/annotation/AnnotationInformationProvider.scala
  app/models/annotation/AnnotationMerger.scala
  app/models/annotation/AnnotationMutations.scala
  app/models/annotation/AnnotationRestrictions.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/AnnotationStore.scala
  app/models/annotation/AnnotationType.scala
  app/models/annotation/TemporaryAnnotationStore.scala
  app/models/annotation/handler/AnnotationInformationHandler.scala
  app/models/annotation/handler/ProjectInformationHandler.scala
  app/models/annotation/handler/SavedTracingInformationHandler.scala
  app/models/annotation/handler/TaskInformationHandler.scala
  app/models/annotation/handler/TaskTypeInformationHandler.scala
  app/models/annotation/nml/NmlWriter.scala
  app/models/binary/DataSet.scala
  app/models/task/Task.scala
  app/models/team/Organization.scala
  app/models/team/Team.scala
  app/models/user/time/TimeSpan.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/cleanup/CleanupService.scala
  app/oxalis/thirdparty/BrainTracing.scala
  conf/webknossos.routes
  public/images/mpi-logos.svg
  util/src/main/scala/com/scalableminds/util/tools/Math.scala
Labels: frontend, refactoring

#2764 Refactor Model Part 5: Extract rendering code into own module
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model/accessors/dataset_accessor.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/flight_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/oblique_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/layer_rendering_manager.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/pushqueue.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
  app/assets/javascripts/oxalis/model/data_layer.js
  app/assets/javascripts/oxalis/model/sagas/prefetch_saga.js
  app/assets/javascripts/test/model/binary/layers/wkstore_adapter.spec.js
  app/assets/javascripts/test/sagas/prefetch_saga.spec.js
Labels: frontend, refactoring

#2778 Refactor Model Part 6: Extract initialization into own module
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/geometries/materials/abstract_plane_material_factory.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/accessors/dataset_accessor.js
  app/assets/javascripts/oxalis/model/accessors/skeletontracing_accessor.js
  app/assets/javascripts/oxalis/model/accessors/volumetracing_accessor.js
  app/assets/javascripts/oxalis/model/actions/skeletontracing_actions.js
  app/assets/javascripts/oxalis/model/actions/volumetracing_actions.js
  app/assets/javascripts/oxalis/model/helpers/generate_dummy_trees.js
  app/assets/javascripts/oxalis/model/helpers/proto_helpers.js
  app/assets/javascripts/oxalis/model/reducers/reducer_helpers.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  app/assets/javascripts/oxalis/model/sagas/prefetch_saga.js
  app/assets/javascripts/oxalis/model_initialization.js
  app/assets/javascripts/test/fixtures/skeletontracing_server_objects.js
  app/assets/javascripts/test/fixtures/tasktracing_server_objects.js
  app/assets/javascripts/test/fixtures/volumetracing_server_objects.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  app/assets/javascripts/test/model/model.spec.js
  app/assets/javascripts/test/sagas/prefetch_saga.spec.js
Labels: frontend, refactoring

#2774 in task search, when filtered by user, show all un-cancelled instead of just active
  app/controllers/TaskController.scala
  app/models/annotation/Annotation.scala
  app/models/project/Project.scala
  app/models/task/Task.scala
  app/utils/SQLHelpers.scala
  conf/messages
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
Labels: backend, enhancement

#2724 Ensure that extra buckets and fallback buckets are loaded with lower priority
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_plane.js
Labels: enhancement, frontend

#2782 fix check for monotonically increasing resolutions
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
Labels: bug

#2787 Hotfix unnecessary scrolling area for firefox
  app/assets/javascripts/oxalis/view/tracing_layout_view.js
Labels: bug, frontend

#2808 Show appropriate error message when webgl crashes
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/view/tracing_view.js
Labels: enhancement

#2793 Enforce minimum-read-time for new task description modal
  app/assets/javascripts/libs/render_independently.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/view/new_task_description_modal.js
Labels: enhancement, frontend

#2796 Test TextureBucketManager
  app/assets/javascripts/oxalis/model/bucket_data_handling/texture_bucket_manager.js
  app/assets/javascripts/test/model/texture_bucket_manager.spec.js
Labels: testing

#2797 Implement better error importing for async code
  app/assets/javascripts/admin/auth/auth_token_view.js
  app/assets/javascripts/admin/project/project_list_view.js
  app/assets/javascripts/admin/scripts/script_list_view.js
  app/assets/javascripts/admin/statistic/open_tasks_report_view.js
  app/assets/javascripts/admin/task/task_list_view.js
  app/assets/javascripts/admin/tasktype/task_type_list_view.js
  app/assets/javascripts/admin/team/team_list_view.js
  app/assets/javascripts/dashboard/advanced_dataset/dataset_access_list_view.js
  app/assets/javascripts/dashboard/dashboard_task_list_view.js
  app/assets/javascripts/dashboard/dataset/dataset_import_view.js
  app/assets/javascripts/dashboard/dataset_view.js
  app/assets/javascripts/dashboard/explorative_annotations_view.js
  app/assets/javascripts/dashboard/spotlight_view.js
  app/assets/javascripts/dashboard/transfer_task_modal.js
  app/assets/javascripts/libs/error_handling.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/view/action-bar/user_scripts_modal_view.js
Labels: enhancement

#2810 Revert "Test TextureBucketManager (#2796)"
  app/assets/javascripts/oxalis/model/bucket_data_handling/texture_bucket_manager.js
Labels: bug

#2805 update scroll-into-view-if-needed and do not scroll body (#2804)
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/comment.js
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/tree_comment_list.js
  package.json
  yarn.lock
Labels: bug, frontend

#2812 Fix the delete initial node warning in tasks
  app/assets/javascripts/oxalis/model/actions/skeletontracing_actions.js
Labels: bug, frontend

#2795 when editing project, dont update paused status
  app/controllers/ProjectController.scala
Labels: backend, bug

#2799 in task creation, make initial node a branchpoint
  app/models/annotation/AnnotationService.scala
Labels: backend, enhancement

#2785 Model refactoring Base 3
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/controller/camera_controller.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/geometries/materials/abstract_plane_material_factory.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/accessors/dataset_accessor.js
  app/assets/javascripts/oxalis/model/accessors/flycam_accessor.js
  app/assets/javascripts/oxalis/model/accessors/skeletontracing_accessor.js
  app/assets/javascripts/oxalis/model/accessors/volumetracing_accessor.js
  app/assets/javascripts/oxalis/model/actions/skeletontracing_actions.js
  app/assets/javascripts/oxalis/model/actions/volumetracing_actions.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bounding_box.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/flight_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/oblique_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/data_cube.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/layer_rendering_manager.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/mappings.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_plane.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/pullqueue.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/pushqueue.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
  app/assets/javascripts/oxalis/model/data_layer.js
  app/assets/javascripts/oxalis/model/helpers/generate_dummy_trees.js
  app/assets/javascripts/oxalis/model/helpers/proto_helpers.js
  app/assets/javascripts/oxalis/model/reducers/reducer_helpers.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  app/assets/javascripts/oxalis/model/sagas/prefetch_saga.js
  app/assets/javascripts/oxalis/model_initialization.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/test/api/api_skeleton_latest.spec.js
  app/assets/javascripts/test/api/api_v2.spec.js
  app/assets/javascripts/test/fixtures/skeletontracing_server_objects.js
  app/assets/javascripts/test/fixtures/tasktracing_server_objects.js
  app/assets/javascripts/test/fixtures/volumetracing_server_objects.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  app/assets/javascripts/test/model/binary/cube.spec.js
  app/assets/javascripts/test/model/binary/layers/wkstore_adapter.spec.js
  app/assets/javascripts/test/model/binary/pullqueue.spec.js
  app/assets/javascripts/test/model/flycam_accessors.spec.js
  app/assets/javascripts/test/model/model.spec.js
  app/assets/javascripts/test/sagas/prefetch_saga.spec.js
Labels: refactoring

#2801 make it possible again to kick user out of organization team
  app/controllers/UserController.scala
Labels: backend, enhancement

#2784 Use isTeamManagerOrAdminOf instead of isTeamManagerOfBLOCKING
  app/controllers/UserTokenController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationMutations.scala
  app/models/annotation/AnnotationRestrictions.scala
  app/models/annotation/handler/ProjectInformationHandler.scala
  app/models/annotation/handler/TaskInformationHandler.scala
  app/models/annotation/handler/TaskTypeInformationHandler.scala
  app/models/user/User.scala
Labels: backend, refactoring

#2813 Make headless gl an optional dependency
  package.json
Labels: enhancement, frontend

#2816 Parallelize some awaits and avoid fetching user twice in dashboard
  app/assets/javascripts/admin/project/project_create_view.js
  app/assets/javascripts/admin/project/project_list_view.js
  app/assets/javascripts/admin/scripts/script_create_view.js
  app/assets/javascripts/admin/task/task_search_form.js
  app/assets/javascripts/admin/user/user_list_view.js
  app/assets/javascripts/dashboard/dashboard_task_list_view.js
  app/assets/javascripts/dashboard/dashboard_view.js
  app/assets/javascripts/dashboard/dataset/dataset_import_view.js
  app/assets/javascripts/main.js
  app/assets/javascripts/oxalis/model/accessors/user_accessor.js
  app/assets/javascripts/oxalis/view/action-bar/merge_modal_view.js
  app/assets/javascripts/test/backend-snapshot-tests/datasets.e2e.js
Labels: enhancement

#2806 delete tree if delete node is initiated for an empty tree
  app/assets/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/model/actions/skeletontracing_actions.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
  app/assets/javascripts/oxalis/model/sagas/skeletontracing_saga.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
  app/assets/javascripts/test/reducers/skeletontracing_reducer.spec.js
Labels: enhancement

#2821 Split shader into two compilation units & better clean up
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/geometries/arbitrary_plane.js
  app/assets/javascripts/oxalis/geometries/materials/abstract_plane_material_factory.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/geometries/plane.js
  app/assets/javascripts/oxalis/shaders/coords.glsl.js
  app/assets/javascripts/oxalis/shaders/filtering.glsl.js
  app/assets/javascripts/oxalis/shaders/main_data_fragment.glsl.js
  app/assets/javascripts/oxalis/shaders/utils.glsl.js
  app/assets/javascripts/test/shaders/shader_syntax.spec.js
Labels: enhancement, frontend
