Repository scalableminds/webknossos, pull requests merged in 2018-10, with the labels that each got.

#3251 Remove deprecation warnings
  app/RequestHandler.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/DataSetController.scala
  app/controllers/TaskController.scala
  conf/logback.xml
  project/AssetCompilation.scala
  webknossos-datastore/app/DsRequestHandler.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/StandaloneDatastore.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/TemporaryStore.scala
Labels: backend, refactoring

#3278 rename oxalis config key to webKnossos
  MIGRATIONS.md
  app/controllers/TaskController.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/mail/DefaultMails.scala
  app/utils/WkConf.scala
  conf/application.conf
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreConfig.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/WebKnossosServer.scala
  webknossos-datastore/conf/standalone-datastore.conf
Labels: backend, datastore-changes, refactoring

#3320 Fix visual login form error
  app/assets/javascripts/navbar.js
Labels: enhancement, frontend

#3325 catch requests for non-existent resolution, reply with empty
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
Labels: backend, bug, datastore-changes, frontend

#3322 add column family volumeUpdates
  fossildb/run.sh
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/volume/VolumeTracingBucketHelper.scala
Labels: backend, datastore-changes

#3326 Beautify right menu
  .gitignore
  app/assets/javascripts/oxalis/view/layouting/default_layout_configs.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
  app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
  app/assets/javascripts/oxalis/view/right-menu/mapping_info_view.js
  app/assets/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
  app/assets/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  app/assets/javascripts/test/screenshots/Cortex_knossos.png
  app/assets/javascripts/test/screenshots/ROI2017_wkw.png
  app/assets/javascripts/test/screenshots/confocal-multi_knossos.png
  app/assets/javascripts/test/screenshots/dsA_2.png
  app/assets/javascripts/test/screenshots/e2006_knossos.png
  app/assets/javascripts/test/screenshots/fluro-rgb_knossos.png
  app/assets/stylesheets/trace_view/_right_menu.less
Labels: enhancement, frontend

#3324 backend conversion route for tracings to hybrid
  app/controllers/AnnotationController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
  conf/messages
  conf/webknossos.routes
Labels: backend, enhancement

#3299 Multiple custom layouts for tracing views
  CHANGELOG.md
  app/assets/javascripts/oxalis/model/actions/ui_actions.js
  app/assets/javascripts/oxalis/model/reducers/ui_reducer.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/action-bar/add_new_layout_modal.js
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/javascripts/oxalis/view/action_bar_view.js
  app/assets/javascripts/oxalis/view/layouting/default_layout_configs.js
  app/assets/javascripts/oxalis/view/layouting/golden_layout_adapter.js
  app/assets/javascripts/oxalis/view/layouting/layout_persistence.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
  app/assets/stylesheets/trace_view/_action_bar.less
  flow-typed/npm/antd_vx.x.x.js
  yarn.lock
Labels: enhancement, frontend

#3336 in project create form, add default for isBlacklistedFromReport
  app/assets/javascripts/admin/project/project_create_view.js
Labels: bug, frontend

#3334 Restful API - correct http verbs
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/oxalis/model/sagas/settings_saga.js
  app/assets/javascripts/oxalis/view/action-bar/merge_modal_view.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  app/controllers/AnnotationController.scala
  app/controllers/DataSetController.scala
  app/controllers/TeamController.scala
  app/controllers/WKDataStoreController.scala
  conf/webknossos.routes
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/WebKnossosServer.scala
Labels: backend, frontend

#3330 Enable Datastore to watch multiple directories
  CHANGELOG.md
  conf/application.conf
  util/src/main/scala/com/scalableminds/util/io/PathUtils.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreConfig.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreModule.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BaseDirService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/conf/standalone-datastore.conf
Labels: backend, datastore-changes, enhancement

#3221 added version-protocol for foreign-datastore requests
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/admin/datastore_health_check.js
  app/assets/javascripts/libs/request.js
  app/assets/javascripts/main.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/navbar.js
  app/assets/javascripts/oxalis/view/action-bar/merge_modal_view.js
  app/assets/javascripts/oxalis/view/action-bar/user_scripts_modal_view.js
  project/BuildInfoSettings.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Application.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/StandaloneDatastore.scala
Labels: backend, datastore-changes, enhancement, planned

#3344 thumbnails default to black again, if no data is found at requested position
  package.json
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
Labels: backend, bug, datastore-changes

#3338 upgraded scala to 2.12 & added migrations
  app/oxalis/security/WkSilhouetteEnvironment.scala
  app/oxalis/thirdparty/BrainTracing.scala
  app/utils/CustomPostgresProfile.scala
  build.sbt
  project/Dependencies.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/volume/FallbackLayerAdapter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/volume/VolumeTracingBucketHelper.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/volume/VolumeTracingLayer.scala
Labels: backend, datastore-changes, refactoring

#3349 Allow to restore older volume versions
  CHANGELOG.md
  app/assets/javascripts/oxalis/model/bucket_data_handling/data_cube.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/layer_rendering_manager.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
  app/assets/javascripts/oxalis/model/sagas/save_saga.js
  app/assets/javascripts/oxalis/model/sagas/volumetracing_saga.js
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/javascripts/oxalis/view/version_list.js
  app/assets/javascripts/oxalis/view/version_view.js
  app/assets/javascripts/test/model/binary/layers/wkstore_adapter.spec.js
  app/assets/javascripts/test/sagas/skeletontracing_saga.spec.js
  app/assets/javascripts/test/sagas/volumetracing_saga.spec.js
  docs/tracing_ui.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/DataRequests.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/requests/DataServiceRequests.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/volume/VolumeTracingLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/volume/VolumeTracingService.scala
Labels: backend, datastore-changes, enhancement, frontend

#3362 Prevent accidental dismissal of team role modal view
  app/assets/javascripts/admin/user/team_role_modal_view.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
Labels: frontend

#3381 Ensure shared Data Cube Cache by holding Binary Data Service in injected Singleton
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreModule.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataServiceHolder.scala
Labels: backend, bug, datastore-changes, urgent

#3368 add api route to signal planned maintenance
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/datastore_health_check.js
  app/assets/javascripts/messages.js
  app/controllers/MaintenanceController.scala
  conf/evolutions/30-maintenance.sql
  conf/evolutions/reversions/030-maintenance.sql
  conf/webknossos.routes
  tools/postgres/schema.sql
Labels: backend, frontend, new feature

#3365 Iterate on version history view
  CHANGELOG.md
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/oxalis/model/sagas/save_saga.js
  app/assets/javascripts/oxalis/model/sagas/skeletontracing_saga.js
  app/assets/javascripts/oxalis/model/sagas/update_actions.js
  app/assets/javascripts/oxalis/model/sagas/volumetracing_saga.js
  app/assets/javascripts/oxalis/view/version_entry.js
  app/assets/javascripts/oxalis/view/version_entry_group.js
  app/assets/javascripts/oxalis/view/version_list.js
  app/assets/javascripts/test/libs/utils.spec.js
  app/assets/javascripts/test/sagas/skeletontracing_saga.spec.js
  app/assets/javascripts/test/sagas/volumetracing_saga.spec.js
  app/assets/stylesheets/trace_view/_right_menu.less
  app/assets/stylesheets/trace_view/_tracing_view.less
  flow-typed/npm/antd_vx.x.x.js
  flow-typed/npm/lodash_v4.x.x.js
Labels: frontend

#3387 Fix duplicate evolution number 30
  conf/evolutions/031-maintenance.sql
  conf/evolutions/reversions/031-maintenance.sql
  tools/postgres/schema.sql
Labels: backend, bug

#3388 Bump flow, eslint + plugin versions
  package.json
  yarn.lock
Labels: frontend

#3371 Show dataset extent in right menu tab
  CHANGELOG.md
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
  app/assets/javascripts/oxalis/view/scalebar.js
Labels: enhancement, frontend

#3383 Refactored dropdown item events
  app/assets/javascripts/admin/task/task_annotation_view.js
  app/assets/javascripts/dashboard/advanced_dataset/dataset_action_view.js
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
Labels: frontend, refactoring

#3390 Clearer Error Message when uploading NML for inaccessible Dataset
  app/controllers/AnnotationIOController.scala
  app/models/annotation/AnnotationService.scala
  conf/messages
Labels: backend, enhancement

#3403 Use correct volume download route in TracingStoreRpcClient
  app/models/annotation/TracingStoreRpcClient.scala
Labels: backend, bug

#3386 Limit number of Tasks to be created in one API Request
  app/controllers/TaskController.scala
  conf/messages
Labels: backend, security

#3385 Add REST API versioning support
  app/controllers/LegacyApiController.scala
  conf/routes
  conf/webknossos.routes
  conf/webknossosApi.routes
Labels: backend, enhancement

#3378 Added button to revoke admin rights in frontend
  CHANGELOG.md
  app/assets/javascripts/admin/user/user_list_view.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
Labels: enhancement, frontend-easy

#3379 Fixed bug in removing layouts
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/stylesheets/trace_view/_action_bar.less
Labels: bug, frontend-easy

#3402 Add debugging methods to visualize wireframe of buckets
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/texture_bucket_manager.js
Labels: frontend

#3399 Enable hybrid tracings by default
  CHANGELOG.md
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/dashboard/advanced_dataset/dataset_action_view.js
  app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
  app/models/annotation/AnnotationService.scala
  conf/application.conf
  docs/tracing_ui.md
Labels: backend, frontend

#3389 Restrict user visibility (non-teammanagers see only themselves)
  app/models/user/User.scala
Labels: backend, enhancement, security

#3394 Handle Cross-Datastore Duplicates, introducing scratch datastores
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStore.scala
  conf/evolutions/032-scratch-datastores.sql
  conf/evolutions/reversions/32-scratch-datastores.sql
  test/db/dataStores.csv
  tools/postgres/schema.sql
Labels: backend, enhancement

#3413 clearer message when annotation couldnt be found while logged out
  app/controllers/AnnotationController.scala
  conf/messages
Labels: backend, enhancement

#3376 Add REST API docs
  docs/index.md
  docs/rest_api.md
Labels: backend
