Repository scalableminds/webknossos, pull requests merged in 2018-12, with the labels that each got.

#3462 added position NaN check in flycam moving reducer and url manager
  app/assets/javascripts/oxalis/controller/url_manager.js
  app/assets/javascripts/oxalis/model/reducers/flycam_reducer.js
Labels: bug, frontend

#3504 Revert "Revert "Add Recommended Configuration to Task Types""
  CHANGELOG.md
  MIGRATIONS.md
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/admin/tasktype/recommended_configuration_view.js
  app/assets/javascripts/admin/tasktype/task_type_create_view.js
  app/assets/javascripts/dashboard/dataset/dataset_import_view.js
  app/assets/javascripts/dashboard/dataset/validation.js
  app/assets/javascripts/libs/render_independently.js
  app/assets/javascripts/libs/user_settings.schema.json
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/model/sagas/root_saga.js
  app/assets/javascripts/oxalis/model/sagas/task_saga.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/recommended_configuration_modal.js
  app/assets/javascripts/oxalis/view/settings/dataset_settings_view.js
  app/assets/javascripts/oxalis/view/settings/setting_input_views.js
  app/assets/javascripts/oxalis/view/settings/user_settings_view.js
  app/assets/javascripts/test/backend-snapshot-tests/tasktypes.e2e.js
  app/assets/javascripts/test/enzyme/snapshot.e2e.js
  app/assets/javascripts/test/fixtures/tasktracing_server_objects.js
  app/assets/javascripts/test/libs/schema.spec.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.snap
  app/controllers/InitialDataController.scala
  app/controllers/UserController.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  conf/evolutions/036-add-lastTaskTypeId-to-user.sql
  conf/evolutions/reversions/036-add-lastTaskTypeId-to-user.sql
  conf/webknossos.latest.routes
  test/db/users.csv
  tools/postgres/schema.sql
  tools/test.sh
Labels: bug

#3533 enable tracing on public datasets of other organizations
  CHANGELOG.md
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
Labels: backend

#3534 Freeze volume versions
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/oxalis/view/version_view.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  conf/application.conf
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreConfig.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/TracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/SkeletonTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/conf/standalone-tracingstore.conf
Labels: backend

#3541 Volume Tracing Stream: Skip invalid buckets
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingBucketHelper.scala
Labels: backend, bug, can't reproduce, urgent

#3532 Disable downsampling of buckets on client
  app/assets/javascripts/oxalis/constants.js
  app/assets/javascripts/test/model/flycam_accessors.spec.js
Labels: frontend

#3493 Isosurface frontend
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/libs/mjs.js
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/model/accessors/flycam_accessor.js
  app/assets/javascripts/oxalis/model/sagas/isosurface_saga.js
  app/assets/javascripts/oxalis/model/sagas/root_saga.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/plane_view.js
  app/assets/javascripts/oxalis/view/right-menu/mapping_info_view.js
  app/assets/javascripts/oxalis/view/settings/dataset_settings_view.js
  package.json
Labels: frontend

#3554 Fix url for isosurface requests
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/oxalis/model/sagas/isosurface_saga.js
Labels: bug

#3477 Script to apply mapping to volume tracing
  tools/apply-mapping/.gitignore
  tools/apply-mapping/main.py
  tools/apply-mapping/requirements.txt
Labels: backend

#3567 Extract braintracing parameters to config
  app/oxalis/thirdparty/BrainTracing.scala
  app/utils/WkConf.scala
  conf/application.conf
Labels: backend

#3566 Include organization in new user admin notification mail
  app/oxalis/mail/DefaultMails.scala
Labels: backend

#3571 Fix redirect url after dataset upload
  CHANGELOG.md
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/dataset/dataset_add_view.js
  app/assets/javascripts/admin/dataset/dataset_upload_view.js
Labels: frontend
