Repository scalableminds/webknossos, pull requests merged in 2018-02, with the labels that each got.

#2354 Fix regression in AbstractTreeViewer due to new EdgeCollection data structure
  app/assets/javascripts/oxalis/model/edge_collection.js
  app/assets/javascripts/oxalis/view/right-menu/abstract_tree_renderer.js
Labels: frontend

#2362 ensure that getNRandomColors always returns n colors even for n > 500
  app/assets/javascripts/libs/color_generator.js
Labels: frontend

#2365 Allow multiple Datastore Auth Tokens
  app/controllers/UserTokenController.scala
  app/oxalis/security/BearerTokenAuthenticatorDAO.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
Labels: backend, bug

#2366 Allow users to access their own time tracking data
  app/controllers/TimeController.scala
  app/models/user/User.scala
Labels: backend, backend-easy, enhancement

#2369 Add /api/features, exposing part of the config
  app/controllers/Application.scala
  conf/application.conf
  conf/webknossos.routes
Labels: backend, discussion, enhancement

#2377 Fix tree sorting in tracing view
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
Labels: frontend

#2379 Internally paginated volume downloads
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/FossilDBClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/volume/VolumeTracingBucketHelper.scala
  webknossos-datastore/proto/fossildbapi.proto
Labels: backend
