Repository scalableminds/webknossos, pull requests merged in 2018-04, with the labels that each got.

#2438 make scmboy superuser by default (sees datastore token)
  app/Global.scala
  conf/application.conf
Labels: backend, backend-easy, infrastructure

#2451 Adds default position, zoom and rotation to datasets
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/sagas/root_saga.js
  app/assets/javascripts/oxalis/model/sagas/settings_saga.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/test/sagas/settings_saga.spec.js
  app/models/configuration/DataSetConfiguration.scala
Labels: enhancement, frontend

#2454 Mutexes finishAndGetNext
  app/assets/javascripts/oxalis/api/api_latest.js
Labels: bug, frontend

#2455 use position + zoom from dataset defaultconfiguration for thumbnail
  app/controllers/DataSetController.scala
  app/models/binary/DataStoreHandler.scala
  util/src/main/scala/com/scalableminds/util/tools/JsonHelper.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/ImageThumbnail.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend, enhancement

#2456 limit task search api to 1000
  app/models/task/Task.scala
Labels: backend, bug

#2461 fix task deletion queries
  app/models/task/Task.scala
Labels: backend, bug

#2463 sort dataset resolutions in backend
  app/models/binary/DataSet.scala
Labels: backend, enhancement

#2464 in main.html do not attempt autologin if it is deactivated
  app/views/main.scala.html
Labels: backend, backend-easy, enhancement

#2469 increase sql isolation level for user dataset config upsert
  app/models/user/User.scala
Labels: backend, bug

#2471 Fix: Create Task from NML: team Id is sent as String, not BSONObjectID
  app/controllers/TaskController.scala
Labels: backend, bug

#2474 Make it easier to select nodes when particleSize is small
  app/assets/javascripts/oxalis/geometries/materials/node_shader.js
Labels: frontend

#2450 URL-Sharing of Datasets
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/dashboard/dataset/dataset_import_view.js
  app/assets/javascripts/dashboard/dataset_view.js
  app/assets/javascripts/dashboard/spotlight_view.js
  app/assets/javascripts/libs/window.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  app/assets/stylesheets/_dashboard.less
  app/controllers/DataSetController.scala
  app/controllers/UserTokenController.scala
  app/models/annotation/Annotation.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/oxalis/security/URLSharing.scala
  app/utils/SQLHelpers.scala
  conf/evolutions_postgres/002-add-dataset-urlsharing-token.sql
  conf/webknossos.routes
  test/db_postgres/dataSets.csv
  tools/postgres/schema-updated.sql
  tools/postgres/schema.sql
  util/src/main/scala/com/scalableminds/util/reactivemongo/AccessContext.scala
Labels: backend, enhancement, frontend

#2475 Fixed dataset search
  app/assets/javascripts/dashboard/advanced_dataset/advanced_dataset_view.js
  app/assets/javascripts/dashboard/gallery_dataset_view.js
  app/assets/javascripts/test/fixtures/dataset_server_object.js
Labels: bug, frontend

#2481 fix sql query to reset tasks to base
  app/models/annotation/Annotation.scala
Labels: backend, bug

#2479 Shows error message of invalid datasource in import screen
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/admin/dataset/dataset_upload_view.js
  app/assets/javascripts/dashboard/dataset/dataset_import_view.js
  app/assets/javascripts/messages.js
Labels: enhancement, frontend

#2483 Transactionally Initialize Task Annotations, avoiding double assignment
  app/Global.scala
  app/controllers/TaskController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/AnnotationState.scala
  app/models/task/Task.scala
  app/models/task/TaskAssignmentService.scala
  app/models/task/TaskService.scala
  app/oxalis/jobs/AvailableTasksJob.scala
  conf/webknossos.routes
  tools/postgres/schema-updated.sql
  tools/postgres/schema.sql
Labels: backend, bug

#2485 run task assignment without sql view
  app/controllers/TaskController.scala
  app/models/task/Task.scala
Labels: backend, bug

#2487 properly run slick transactions
  app/models/annotation/Annotation.scala
  app/models/binary/DataSetService.scala
  app/models/task/Task.scala
  app/models/user/User.scala
Labels: backend, bug

#2489 retry task assignment on transaction serialization failure
  app/models/task/Task.scala
  app/utils/SQLHelpers.scala
Labels: backend, bug

#2492 update postgres library dependencies
  project/Dependencies.scala
Labels: backend

#2493 Validating datasoure settings in the frontend
  app/assets/javascripts/dashboard/dataset/dataset_import_view.js
  app/assets/javascripts/libs/datasource.schema.json
  app/assets/javascripts/libs/datasource.types.js
  package.json
  yarn.lock
Labels: enhancement, frontend

#2498 assign highest priority tasks first, not lowest...
  app/models/task/Task.scala
Labels: backend, bug

#2499 Fix project peeking
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/dashboard/dashboard_task_list_view.js
Labels: bug, frontend

#2484 user access query: separate organizations
  app/models/user/User.scala
Labels: backend, bug

#2505 Allow Team Managers to edit datasets
  app/controllers/UserTokenController.scala
  app/models/binary/DataSet.scala
  app/models/user/User.scala
Labels: backend, team-administration

#2508 allow teammanager to edit dataset defaultconfig
  app/controllers/ConfigurationController.scala
Labels: backend, bug

#2507 update initialized task annotations instead of hacky upsert
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
Labels: backend, bug

#2513 fix: if default config has no position field, use fallback
  app/controllers/DataSetController.scala
Labels: backend, bug

#2523 Updated View Mode Informations
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/oxalis/controller/camera_controller.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/geometries/materials/node_shader.js
  app/assets/javascripts/oxalis/geometries/plane.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/accessors/flycam_accessor.js
  app/assets/javascripts/oxalis/model/helpers/nml_helpers.js
  app/assets/javascripts/oxalis/model/reducers/flycam_reducer.js
  app/assets/javascripts/oxalis/model/reducers/settings_reducer.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
  app/assets/javascripts/oxalis/model/volumetracing/volumelayer.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
  app/assets/javascripts/test/model/flycam_accessors.spec.js
  app/assets/javascripts/test/reducers/flycam_reducer.spec.js
  app/assets/javascripts/test/reducers/skeletontracing_reducer.spec.js
  app/assets/javascripts/test/sagas/save_saga.spec.js
  app/assets/javascripts/test/sagas/skeletontracing_saga.spec.js
Labels: frontend

#2525 Tasks Assignment Query: Lock task rows via FOR UPDATE
  app/models/task/Task.scala
Labels: backend, bug

#2529 undo task assignment PR 2525 since it presumably broke the production instance
  app/models/task/Task.scala
Labels: backend, bug

#2537 write optional nml filename to task creation info
  app/controllers/TaskController.scala
Labels: backend, bug

#2518 task creation api uses teamName again instead of id
  app/assets/javascripts/admin/task/task_create_bulk_view.js
  app/assets/javascripts/admin/task/task_create_form_view.js
  app/controllers/TaskController.scala
  app/models/team/Team.scala
Labels: backend, bug
