Repository scalableminds/webknossos, pull requests merged in 2018-07, with the labels that each got.

#2848 Change missing-node-id-assertion to user warning
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
Labels: frontend

#2853 Fix coloring of navbar when logged out
  app/assets/javascripts/navbar.js
Labels: frontend, low-hanging-fruit

#2855 Render Markdown in View mode
  app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
Labels: bug, frontend

#2847 Front end test coverage
  .babelrc
  .circleci/config.yml
  .gitignore
  app/assets/javascripts/oxalis/api/api_loader.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  docker-compose.yml
  package.json
  tools/test.sh
  yarn.lock
Labels: frontend, testing

#2870 remove some unused code from reactivemongo package, move bsonId reads
  app/controllers/DataSetController.scala
  app/controllers/ScriptsController.scala
  app/controllers/TaskTypeController.scala
  app/models/project/Project.scala
  app/models/team/Organization.scala
  app/models/team/TeamMembership.scala
  app/utils/SQLHelpers.scala
  util/src/main/scala/com/scalableminds/util/reactivemongo/JsonFormatHelper.scala
  util/src/main/scala/com/scalableminds/util/reactivemongo/MongoHelpers.scala
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
Labels: backend, refactoring

#2872 Move DBAccessContext classes to separate package
  app/Global.scala
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Authentication.scala
  app/controllers/DataSetController.scala
  app/controllers/InitialDataController.scala
  app/controllers/OrganizationController.scala
  app/controllers/ProjectController.scala
  app/controllers/ReportController.scala
  app/controllers/TaskController.scala
  app/controllers/TeamController.scala
  app/controllers/UserController.scala
  app/controllers/UserTokenController.scala
  app/controllers/WKDataStoreController.scala
  app/models/analytics/AnalyticsEntry.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationInformationProvider.scala
  app/models/annotation/AnnotationMerger.scala
  app/models/annotation/AnnotationMutations.scala
  app/models/annotation/AnnotationRestrictions.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/AnnotationStore.scala
  app/models/annotation/handler/AnnotationInformationHandler.scala
  app/models/annotation/handler/ProjectInformationHandler.scala
  app/models/annotation/handler/SavedTracingInformationHandler.scala
  app/models/annotation/handler/TaskInformationHandler.scala
  app/models/annotation/handler/TaskTypeInformationHandler.scala
  app/models/basics/Implicits.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStore.scala
  app/models/project/Project.scala
  app/models/task/Script.scala
  app/models/task/Task.scala
  app/models/task/TaskType.scala
  app/models/team/Organization.scala
  app/models/team/Team.scala
  app/models/team/TeamMembership.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  app/models/user/time/TimeSpan.scala
  app/models/user/time/TimeSpanDAO.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/ndstore/ND2WK.scala
  app/oxalis/security/BearerTokenAuthenticatorDAO.scala
  app/oxalis/security/CombinedAuthenticatorService.scala
  app/oxalis/security/CredentialsProvider.scala
  app/oxalis/security/URLSharing.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  app/oxalis/thirdparty/BrainTracing.scala
  app/oxalis/user/UserCache.scala
  app/utils/SQLHelpers.scala
  util/src/main/scala/com/scalableminds/util/accesscontext/AccessContext.scala
  util/src/main/scala/com/scalableminds/util/reactivemongo/DBAccess.scala
Labels: backend, refactoring

#2869 Display name for organizations
  CHANGELOG.md
  MIGRATIONS.md
  app/controllers/Authentication.scala
  app/controllers/InitialDataController.scala
  app/controllers/OrganizationController.scala
  app/models/team/Organization.scala
  conf/evolutions/015-add-organization-displayname.sql
  conf/evolutions/reversions/015-add-organization-displayname.sql
  test/db/organizations.csv
  tools/postgres/schema.sql
Labels: backend, enhancement

#2858 Screenshot test tracing view
  .gitignore
  app/assets/javascripts/test/puppeteer/dataset_rendering.screenshot.js
  app/assets/javascripts/test/puppeteer/dataset_rendering_helpers.js
  app/assets/javascripts/test/puppeteer/screenshot_helpers.js
  app/assets/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  app/assets/javascripts/test/screenshots/Cortex_knossos.png
  app/assets/javascripts/test/screenshots/ROI2017_wkw.png
  app/assets/javascripts/test/screenshots/confocal-multi_knossos.png
  app/assets/javascripts/test/screenshots/e2006_knossos.png
  app/assets/javascripts/test/screenshots/fluro-rgb_knossos.png
  app/controllers/InitialDataController.scala
  clean
  docker-compose.yml
  package.json
  yarn.lock
Labels: frontend, testing

#2884 in task deletion, also delete its annotations
  CHANGELOG.md
  MIGRATIONS.md
  app/controllers/TaskController.scala
Labels: backend, bug, urgent

#2885 In dataset upload, catch AccessDenied exception for better error reporting
  conf/messages
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
Labels: backend, enhancement

#2860 Add possibility to show random tasks
  CHANGELOG.md
  app/assets/javascripts/admin/task/task_search_form.js
  app/controllers/TaskController.scala
  app/models/task/Task.scala
Labels: backend, enhancement

#2888 Tag buildinfo
  CHANGELOG.md
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/navbar.js
  project/BuildInfoSettings.scala
Labels: enhancement, frontend

#2890 Fix buildinfo tag
  app/assets/javascripts/navbar.js
  docker-compose.yml
Labels: enhancement

#2895 in timeLogging, ignore expected failures of signalOverTime
  app/models/user/time/TimeSpanService.scala
Labels: backend, bug, urgent

#2881 Improve flow of importing a dataset
  .eslintrc.json
  CHANGELOG.md
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/dashboard/dataset/dataset_import_view.js
  app/assets/javascripts/dashboard/dataset/default_config_component.js
  app/assets/javascripts/dashboard/dataset/helper_components.js
  app/assets/javascripts/dashboard/dataset/import_general_component.js
  app/assets/javascripts/dashboard/dataset/simple_advanced_data_form.js
  app/assets/javascripts/dashboard/dataset/validation.js
  app/assets/javascripts/libs/vector_input.js
  app/assets/javascripts/messages.js
  flow-typed/npm/antd_vx.x.x.js
Labels: enhancement, frontend

#2896 use camel case for organization's displayname in JSON
  app/controllers/OrganizationController.scala
Labels: backend

#2897 Fix comment/branchpoint removal for last node of a tree
  CHANGELOG.md
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
  app/assets/javascripts/test/reducers/skeletontracing_reducer.spec.js
Labels: bug, frontend

#2861 Redesign user task list
  CHANGELOG.md
  app/assets/javascripts/admin/task/task_annotation_view.js
  app/assets/javascripts/admin/tasktype/task_type_list_view.js
  app/assets/javascripts/dashboard/dashboard_task_list_view.js
  app/assets/stylesheets/_dashboard.less
  flow-typed/npm/antd_vx.x.x.js
Labels: enhancement, frontend

#2889 Enable datastore in e2e tests and enable tests that use datastore
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/test/backend-snapshot-tests/annotations.e2e.js
  app/assets/javascripts/test/backend-snapshot-tests/tasks.e2e.js
  app/assets/javascripts/test/enzyme/e2e-setup.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  conf/messages
  docker-compose.yml
  package.json
  test/e2e/End2EndSpec.scala
  tools/test.sh
  yarn.lock
Labels: backend, frontend, testing

#2899 Update prettier + Change NML frontend download caption
  app/assets/javascripts/admin/statistic/project_progress_report_view.js
  app/assets/javascripts/admin/task/task_create_bulk_view.js
  app/assets/javascripts/dashboard/dataset/dataset_import_view.js
  app/assets/javascripts/libs/input.js
  app/assets/javascripts/libs/keyboard.js
  app/assets/javascripts/oxalis/controller/camera_controller.js
  app/assets/javascripts/oxalis/controller/combinations/volumetracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/geometries/plane.js
  app/assets/javascripts/oxalis/model/accessors/flycam_accessor.js
  app/assets/javascripts/oxalis/model/actions/view_mode_actions.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/arbitrary_cube_adapter.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bounding_box.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_traversals.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/layer_rendering_manager.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/mappings.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/texture_bucket_manager.js
  app/assets/javascripts/oxalis/model/data_connection_info.js
  app/assets/javascripts/oxalis/model/helpers/generate_dummy_trees.js
  app/assets/javascripts/oxalis/model/reducers/flycam_reducer.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  app/assets/javascripts/oxalis/model/reducers/view_mode_reducer.js
  app/assets/javascripts/oxalis/model/sagas/volumetracing_saga.js
  app/assets/javascripts/oxalis/model/volumetracing/volumelayer.js
  app/assets/javascripts/oxalis/view/action-bar/share_modal_view.js
  app/assets/javascripts/oxalis/view/arbitrary_view.js
  app/assets/javascripts/oxalis/view/right-menu/abstract_tree_renderer.js
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
  app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
  app/assets/javascripts/oxalis/view/right-menu/mapping_info_view.js
  app/assets/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
  app/assets/javascripts/oxalis/view/right_menu_view.js
  app/assets/javascripts/oxalis/view/settings/dataset_settings_view.js
  app/assets/javascripts/oxalis/view/settings/setting_input_views.js
  app/assets/javascripts/oxalis/view/settings/user_settings_view.js
  app/assets/javascripts/oxalis/view/tracing_view.js
  app/assets/javascripts/test/puppeteer/screenshot_helpers.js
  package.json
  yarn.lock
Labels: frontend

#2874 Refactor Backend: Merge ScriptSQL and Script. Also Analytics
  app/controllers/Application.scala
  app/controllers/ScriptController.scala
  app/controllers/TaskController.scala
  app/models/analytics/AnalyticsEntry.scala
  app/models/task/Script.scala
  app/models/task/Task.scala
  app/utils/SQLHelpers.scala
  conf/messages
  conf/webknossos.routes
Labels: backend, refactoring

#2876 Refactor Backend: Merge TaskTypeSQL and TaskType
  app/controllers/AnnotationIOController.scala
  app/controllers/InitialDataController.scala
  app/controllers/TaskController.scala
  app/controllers/TaskTypeController.scala
  app/models/annotation/handler/TaskTypeInformationHandler.scala
  app/models/task/Task.scala
  app/models/task/TaskType.scala
  app/oxalis/thirdparty/BrainTracing.scala
Labels: backend, refactoring

#2904 add schema versioning, show in buildinfo
  MIGRATIONS.md
  app/controllers/Application.scala
  conf/evolutions/016-add-schema-version.sql
  conf/evolutions/reversions/016-add-schema-version.sql
  tools/postgres/schema.sql
Labels: backend, enhancement, infrastructure

#2877 Refactor Backend: Merge OrganizationSQL and Organization
  app/controllers/Authentication.scala
  app/controllers/InitialDataController.scala
  app/controllers/OrganizationController.scala
  app/controllers/TaskController.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/team/Organization.scala
  app/models/team/Team.scala
  app/models/user/UserService.scala
  app/oxalis/ndstore/ND2WK.scala
Labels: backend, refactoring

#2879 Refactor Backend: merge DataStoreSQL and DataStore
  app/controllers/DataStoreController.scala
  app/controllers/InitialDataController.scala
  app/controllers/WKDataStoreController.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStore.scala
Labels: backend, refactoring

#2892 Refactor Backend: Merge TimeSpanSQL and TimeSpan
  app/controllers/AnnotationController.scala
  app/controllers/StatisticsController.scala
  app/controllers/TimeController.scala
  app/controllers/UserController.scala
  app/models/user/time/TimeSpan.scala
  app/models/user/time/TimeSpanDAO.scala
  app/models/user/time/TimeSpanService.scala
Labels: backend, refactoring

#2912 Allow decimal scale in simple import view (fixes #2911)
  CHANGELOG.md
  app/assets/javascripts/dashboard/dataset/simple_advanced_data_form.js
  app/assets/javascripts/libs/vector_input.js
Labels: frontend

#2915 Unsort comments
  CHANGELOG.md
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/tree_comment_list.js
Labels: frontend

#2921 Fix merger-mode
  CHANGELOG.md
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
Labels: frontend

#2907 Remove sbt-style Versioning (obsolete next to CI build/tag versioning)
  build.sbt
  project/BuildInfoSettings.scala
  version
Labels: backend, infrastructure

#2925 rename sbt project and binary from “oxalis” to “webknossos”
  Dockerfile
  build.sbt
  docker-compose.yml
Labels: backend, infrastructure, refactoring

#2939 organization-specific newUserMailingList and overTimeMailingList
  CHANGELOG.md
  MIGRATIONS.md
  app/controllers/Authentication.scala
  app/models/team/Organization.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/mail/DefaultMails.scala
  app/oxalis/thirdparty/BrainTracing.scala
  conf/evolutions/017-add-organization-email.sql
  conf/evolutions/reversions/017-add-organization-email.sql
  test/db/organizations.csv
  tools/postgres/schema.sql
Labels: backend, enhancement

#2948 Send Email when new Organization is created
  app/controllers/Authentication.scala
  app/oxalis/mail/DefaultMails.scala
  app/views/mail/newOrganization.scala.html
  conf/application.conf
Labels: backend, enhancement, infrastructure

#2908 Drag'n'drop import of multiple NML files
  .flowconfig
  CHANGELOG.md
  app/assets/javascripts/components/file_upload.js
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/model/actions/actions.js
  app/assets/javascripts/oxalis/model/actions/ui_actions.js
  app/assets/javascripts/oxalis/model/helpers/nml_helpers.js
  app/assets/javascripts/oxalis/model/reducers/ui_reducer.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/action-bar/merge_modal_view.js
  app/assets/javascripts/oxalis/view/nml_upload_zone_container.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
  app/assets/javascripts/oxalis/view/tracing_layout_view.js
  app/assets/stylesheets/main.less
  flow-typed/npm/antd_vx.x.x.js
  flow-typed/npm/react-dropzone_v4.x.x.js
  package.json
  yarn.lock
Labels: enhancement, frontend

#2913 Refactor Backend: Merge UserSQL and User
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Application.scala
  app/controllers/Authentication.scala
  app/controllers/ConfigurationController.scala
  app/controllers/Controller.scala
  app/controllers/DataSetController.scala
  app/controllers/InitialDataController.scala
  app/controllers/ProjectController.scala
  app/controllers/ReportController.scala
  app/controllers/ScriptController.scala
  app/controllers/StatisticsController.scala
  app/controllers/TaskController.scala
  app/controllers/TeamController.scala
  app/controllers/TimeController.scala
  app/controllers/UserController.scala
  app/controllers/UserTokenController.scala
  app/models/analytics/AnalyticsEntry.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationMerger.scala
  app/models/annotation/AnnotationMutations.scala
  app/models/annotation/AnnotationRestrictions.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/AnnotationStore.scala
  app/models/annotation/handler/AnnotationInformationHandler.scala
  app/models/annotation/handler/ProjectInformationHandler.scala
  app/models/annotation/handler/SavedTracingInformationHandler.scala
  app/models/annotation/handler/TaskInformationHandler.scala
  app/models/annotation/handler/TaskTypeInformationHandler.scala
  app/models/basics/Implicits.scala
  app/models/binary/DataSet.scala
  app/models/project/Project.scala
  app/models/task/Script.scala
  app/models/task/Task.scala
  app/models/task/TaskType.scala
  app/models/team/Team.scala
  app/models/team/TeamMembership.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  app/models/user/time/TimeSpan.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/mail/DefaultMails.scala
  app/oxalis/security/Environment.scala
  app/oxalis/security/Secured.scala
  app/oxalis/security/URLSharing.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  app/oxalis/thirdparty/BrainTracing.scala
  app/oxalis/user/ActivityMonitor.scala
  app/oxalis/user/UserCache.scala
  app/oxalis/view/SessionData.scala
  app/utils/SQLHelpers.scala
  app/views/mail/registerAdminNotify.scala.html
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
Labels: backend, refactoring

#2953 correctly use isAdminOf (boolean, not fox) + GlobalAccessContext in DataSet writes
  app/models/binary/DataSet.scala
Labels: backend, bug

#2956 use GlobalAccessContext in user publicWrites. fix id selection in create explorational
  app/controllers/UserController.scala
  app/models/annotation/AnnotationService.scala
  app/models/user/User.scala
Labels: backend, bug

#2955 Show sticky toast if progress report request fails
  CHANGELOG.md
  app/assets/javascripts/admin/statistic/project_progress_report_view.js
  app/assets/javascripts/messages.js
Labels: frontend

#2958 Refactor backend: Merge TeamSQL and Team
  app/controllers/DataSetController.scala
  app/controllers/InitialDataController.scala
  app/controllers/ReportController.scala
  app/controllers/TeamController.scala
  app/controllers/UserController.scala
  app/models/annotation/AnnotationService.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStoreType.scala
  app/models/project/Project.scala
  app/models/team/Team.scala
  app/models/team/TeamMembership.scala
  app/models/user/UserService.scala
  app/models/user/time/TimeSpan.scala
  app/oxalis/ndstore/ND2WK.scala
  app/oxalis/security/BearerTokenAuthenticatorDAO.scala
  app/utils/SQLHelpers.scala
  project/Dependencies.scala
  test/backend/NMLUnitTestSuite.scala
Labels: backend, refactoring

#2963 Color unloaded data gray, even for last zoomstep
  CHANGELOG.md
  app/assets/javascripts/oxalis/shaders/filtering.glsl.js
  app/assets/javascripts/oxalis/shaders/main_data_fragment.glsl.js
Labels: bug, frontend

#2961 Refactor backend: Merge DataSetSQL and DataSet. Remove NDStore residue
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/ConfigurationController.scala
  app/controllers/Controller.scala
  app/controllers/DataSetController.scala
  app/controllers/StatisticsController.scala
  app/controllers/TaskController.scala
  app/controllers/UserTokenController.scala
  app/controllers/WKDataStoreController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationMerger.scala
  app/models/annotation/AnnotationMutations.scala
  app/models/annotation/AnnotationService.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStoreHandler.scala
  app/models/binary/DataStoreType.scala
  app/models/configuration/DataSetConfiguration.scala
  app/models/task/Task.scala
  app/oxalis/ndstore/ND2WK.scala
  app/oxalis/ndstore/NDChannel.scala
  app/oxalis/ndstore/NDDataSet.scala
  app/oxalis/ndstore/NDProject.scala
  app/oxalis/ndstore/NDServerConnection.scala
Labels: backend, refactoring

#2968 retry bucket loading from file
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
Labels: backend, bug

#2974 synchronize data cube file access handles
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/Cube.scala
Labels: backend, bug

#2978 allow specifying groupId in createTree skeleton action
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/skeleton/updating/SkeletonUpdateActions.scala
Labels: backend, enhancement

#2935 Clean up merge modal and allow "live-merge" of explorative and project
  CHANGELOG.md
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/model/helpers/generate_dummy_trees.js
  app/assets/javascripts/oxalis/model/reducers/save_reducer.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
  app/assets/javascripts/oxalis/model/sagas/save_saga.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/action-bar/merge_modal_view.js
  app/assets/javascripts/oxalis/view/action-bar/save_button.js
  app/assets/javascripts/test/reducers/save_reducer.spec.js
  app/assets/javascripts/test/sagas/saga_integration.spec.js
  app/assets/javascripts/test/sagas/save_saga.spec.js
  app/assets/javascripts/test/sagas/skeletontracing_saga.spec.js
Labels: frontend

#2970 Fix initial loading of data for last zoomstep (#2962)
  app/assets/javascripts/oxalis/model/sagas/prefetch_saga.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  app/assets/javascripts/test/screenshots/e2006_knossos.png
Labels: bug, frontend

#2984 Backend hybrid annotations
  MIGRATIONS.md
  app/assets/javascripts/test/enzyme/e2e-setup.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/TaskController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationMerger.scala
  app/models/annotation/AnnotationMutations.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/AnnotationSettings.scala
  app/models/annotation/AnnotationStore.scala
  app/models/binary/DataStoreHandler.scala
  app/models/task/Task.scala
  conf/evolutions/018-hybrid-annotations.sql
  conf/evolutions/reversions/018-hybrid-annotations.sql
  test/db/annotations.csv
  tools/postgres/schema.sql
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/SkeletonTracingController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/TracingController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/VolumeTracingController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/TracingType.scala
Labels: backend, enhancement

#2986 include created timestamp field in user json
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.snap
  app/models/user/User.scala
Labels: backend, enhancement
