Repository scalableminds/webknossos, pull requests merged in 2018-05, with the labels that each got.

#2540 if ideal thumbnail resolution does not exist, snap to closest
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/ImageThumbnail.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
Labels: backend, bug

#2532 Use SQL trigger function to assert nonnegative openInstances
  app/models/annotation/Annotation.scala
  app/models/task/Task.scala
  app/models/user/User.scala
  app/utils/SQLHelpers.scala
  conf/evolutions_postgres/005-add-openinstances-trigger.sql
  tools/postgres/schema-updated.sql
  tools/postgres/schema.sql
Labels: backend, bug

#2544 Retrying SQL Queries: pass retry-if list in recursive call
  app/utils/SQLHelpers.scala
Labels: backend, bug

#2502 added timestamp option to UpdateActions
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/UpdateActions.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/skeleton/SkeletonTracingService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/skeleton/updating/SkeletonUpdateActions.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/volume/VolumeUpdateActions.scala
Labels: backend, enhancement

#2549 Fixed script deletion
  app/controllers/ScriptsController.scala
Labels: backend-easy, bug

#2551 in project download, get skeletons in multiple smaller requests
  app/models/annotation/AnnotationService.scala
  util/src/main/scala/com/scalableminds/util/rpc/RPCRequest.scala
Labels: backend, enhancement

#2554 use named query in findteam (was lost in merge)
  app/models/team/Team.scala
Labels: backend

#2555 add sql trigger (evolution 005) also to schema.sql
  tools/postgres/schema.sql
Labels: backend, enhancement

#2561 add tooltip to task status icons
  app/assets/javascripts/admin/task/task_list_view.js
Labels: enhancement, frontend

#2562 in script update route, dont return temporary id
  app/controllers/ScriptsController.scala
Labels: backend, backend-easy

#2572 in ensureTeamAdministration, use nonblocking version of isTeamManager
  app/controllers/Controller.scala
Labels: backend, bug

#2573 Fix team search
  app/assets/javascripts/admin/team/team_list_view.js
Labels: frontend

#2565 Further reduce number of SQL queries in project download
  app/models/annotation/AnnotationService.scala
  app/models/annotation/handler/SavedTracingInformationHandler.scala
Labels: backend

#2559 Add more E2E tests
  app/assets/javascripts/test/backend-snapshot-tests/datasets.e2e.js
  app/assets/javascripts/test/backend-snapshot-tests/misc.e2e.js
  app/assets/javascripts/test/backend-snapshot-tests/projects.e2e.js
  app/assets/javascripts/test/backend-snapshot-tests/scripts.e2e.js
  app/assets/javascripts/test/backend-snapshot-tests/users.e2e.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/projects.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/projects.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/scripts.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/scripts.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/libs/nml.spec.js.snap
  test/db_postgres/scripts.csv
  tools/test.sh
Labels: frontend, testing

#2567 unify type of datalayer name in schema
  conf/evolutions_postgres/007-unify-type-datalayer-name.sql
  tools/postgres/schema.sql
Labels: backend, enhancement

#2580 project download: fetch skeletontracings batched and sequentially
  app/models/annotation/AnnotationService.scala
Labels: backend, bug

#2587 guess bounding box from correct resolution dir. remove duplicate methods
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataFormat.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceImporter.scala
Labels: backend, bug

#2590 in update allowed teams, make team list unique
  app/models/binary/DataSet.scala
Labels: backend, bug

#2588 Update flow to 0.71, clean up flowconfig
  .flowconfig
  app/assets/javascripts/libs/input.js
  app/assets/javascripts/libs/request.js
  app/assets/javascripts/libs/resizable_buffer.js
  app/assets/javascripts/oxalis/constants.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/geometries/cube.js
  app/assets/javascripts/oxalis/model/sagas/save_saga.js
  app/assets/javascripts/test/enzyme/e2e-setup.js
  package.json
  yarn.lock
Labels: frontend, testing

#2581 logout api no longer fails if user is already logged out
  app/controllers/Authentication.scala
Labels: backend, backend-easy, enhancement

#2583 properly wait for individual steps of datasource upload
  app/assets/javascripts/admin/admin_rest_api.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceRepository.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
Labels: backend, bug, frontend

#2593 Remove some dead code from datastore
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataSource.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
Labels: backend

#2597 rename datastore application.conf to avoid wrong precedence
  .circleci/config.yml
  docker-compose.yml
  webknossos-datastore/Dockerfile
  webknossos-datastore/conf/standalone-datastore.conf
  webknossos-datastore/deployment/config/docker.conf
  webknossos-datastore/docker-compose.yml
Labels: backend, infrastructure

#2594 Task Assignment via openInstances Column
  app/controllers/ReportController.scala
  app/models/annotation/Annotation.scala
  app/models/task/Task.scala
  conf/evolutions_postgres/008-task-instances-triggers.sql
  test/db_postgres/tasks.csv
  tools/postgres/prepareTestDB.sh
  tools/postgres/schema.sql
Labels: backend, bug

#2619 clean up NMLParseResult logic
  app/controllers/AnnotationIOController.scala
  app/controllers/TaskController.scala
  app/models/annotation/nml/NmlService.scala
Labels: backend, refactoring

#2626 Fix nml-groups in nml_helpers.js (#2625)
  app/assets/javascripts/oxalis/model/helpers/nml_helpers.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/libs/nml.spec.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/libs/nml.spec.js.snap
Labels: bug, urgent

#2585 Add implicit SQL SetParameter for ObjectId. Use in UserSQLDAO
  app/models/user/User.scala
  app/utils/SQLHelpers.scala
Labels: backend, enhancement

#2623 add meaningful error message for missing NML scale
  app/controllers/AnnotationIOController.scala
  app/models/annotation/AnnotationService.scala
  conf/messages
Labels: backend, bug

#2631 prevent tree tab from grabbing focus (#2627)
  app/assets/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
Labels: bug, frontend

#2602 Refactor mapping related model code
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_loader.js
  app/assets/javascripts/oxalis/api/api_v1.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model/actions/settings_actions.js
  app/assets/javascripts/oxalis/model/binary.js
  app/assets/javascripts/oxalis/model/binary/data_cube.js
  app/assets/javascripts/oxalis/model/binary/mappings.js
  app/assets/javascripts/oxalis/model/reducers/settings_reducer.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/right-menu/mapping_info_view.js
  app/assets/javascripts/test/api/api_skeleton_latest.spec.js
  app/assets/javascripts/test/api/api_v2.spec.js
  app/assets/javascripts/test/helpers/apiHelpers.js
Labels: enhancement, frontend

#2621 Refactor model part 1
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/admin/dataset/dataset_add_view.js
  app/assets/javascripts/admin/dataset/dataset_remote_view.js
  app/assets/javascripts/admin/dataset/dataset_upload_view.js
  app/assets/javascripts/dashboard/advanced_dataset/dataset_action_view.js
  app/assets/javascripts/dashboard/dataset_view.js
  app/assets/javascripts/dashboard/gallery_dataset_view.js
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_loader.js
  app/assets/javascripts/oxalis/api/api_v1.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/controller/combinations/volumetracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/geometries/volumegeometry.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/accessors/flycam_accessor.js
  app/assets/javascripts/oxalis/model/actions/settings_actions.js
  app/assets/javascripts/oxalis/model/binary.js
  app/assets/javascripts/oxalis/model/binary/bucket_builder.js
  app/assets/javascripts/oxalis/model/binary/data_cube.js
  app/assets/javascripts/oxalis/model/binary/layers/layer.js
  app/assets/javascripts/oxalis/model/binary/layers/nd_store_layer.js
  app/assets/javascripts/oxalis/model/binary/layers/wk_layer.js
  app/assets/javascripts/oxalis/model/binary/mappings.js
  app/assets/javascripts/oxalis/model/binary/pullqueue.js
  app/assets/javascripts/oxalis/model/binary/pushqueue.js
  app/assets/javascripts/oxalis/model/binary/wkstore_adapter.js
  app/assets/javascripts/oxalis/model/reducers/settings_reducer.js
  app/assets/javascripts/oxalis/model/sagas/update_actions.js
  app/assets/javascripts/oxalis/model/sagas/volumetracing_saga.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/polygons/polygon_factory.js
  app/assets/javascripts/oxalis/view/polygons/tlt.js
  app/assets/javascripts/oxalis/view/right-menu/mapping_info_view.js
  app/assets/javascripts/oxalis/view/settings/user_settings_view.js
  app/assets/javascripts/router.js
  app/assets/javascripts/test/api/api_skeleton_latest.spec.js
  app/assets/javascripts/test/api/api_v2.spec.js
  app/assets/javascripts/test/api/api_volume_latest.spec.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  app/assets/javascripts/test/model/binary/layers/wkstore_adapter.spec.js
  app/assets/javascripts/test/model/binary/pullqueue.spec.js
  app/assets/javascripts/test/model/flycam_accessors.spec.js
  app/assets/javascripts/test/model/model.spec.js
Labels: frontend

#2614 organization admins can now see all TaskTypes of their organization
  app/models/task/TaskType.scala
Labels: backend, bug

#2657 Remove more Mongo Residue
  conf/application.conf
  package.json
  test/db/analytics.csv
  test/db/annotations.csv
  test/db/annotations.json
  test/db/bearerTokenAuthenticators.json
  test/db/dataSet_allowedTeams.csv
  test/db/dataSet_layers.csv
  test/db/dataSet_resolutions.csv
  test/db/dataSets.csv
  test/db/dataSets.json
  test/db/dataStores.csv
  test/db/dataStores.json
  test/db/dataTokens.json
  test/db/mturkSQS.json
  test/db/organizations.csv
  test/db/projects.csv
  test/db/projects.json
  test/db/scripts.csv
  test/db/system.indexes.json
  test/db/taskTypes.csv
  test/db/taskTypes.json
  test/db/tasks.csv
  test/db/tasks.json
  test/db/teams.csv
  test/db/teams.json
  test/db/timeSpans.csv
  test/db/timeSpans.json
  test/db/tokens.csv
  test/db/user_dataSetConfigurations.csv
  test/db/user_experiences.csv
  test/db/user_team_roles.csv
  test/db/users.csv
  test/db/users.json
  test/frontend/End2EndSpec.scala
  tools/postgres/prepareTestDB.sh
Labels: backend, infrastructure, refactoring

#2644 Show the mapping view iff a segmentation layer exists
  app/assets/javascripts/oxalis/view/right_menu_view.js
Labels: frontend

#2659 corrected subject line of reset password email
  app/oxalis/mail/DefaultMails.scala
Labels: backend, backend-easy, enhancement

#2662 Secure docker login in CI
  .circleci/config.yml
Labels: enhancement, infrastructure

#2642 Tree search
  app/assets/javascripts/admin/help/keyboardshortcut_view.js
  app/assets/javascripts/libs/input.js
  app/assets/javascripts/libs/shortcut_component.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
  app/assets/javascripts/oxalis/view/right-menu/tree_search_popover.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
  flow-typed/npm/antd_vx.x.x.js
Labels: frontend

#2660 Enable NML downloads even if Datasource is unusable (write Scale -1)
  app/controllers/AnnotationIOController.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/nml/NmlWriter.scala
Labels: backend, enhancement

#2666 add yarn comments enable-autologin and disable-autologin
  package.json
Labels: Epic

#2651 Fix e2e-test timetracking
  app/assets/javascripts/test/backend-snapshot-tests/projects.e2e.js
  app/assets/javascripts/test/backend-snapshot-tests/teamstructure.e2e.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/projects.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/projects.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.snap
  test/db/taskTypes.csv
  test/db/tasks.csv
Labels: backend, bug
