Repository scalableminds/webknossos, pull requests merged in 2018-11, with the labels that each got.

#3421 Even if initialData is disabled, insert local stores
  CHANGELOG.md
  app/Startup.scala
  app/controllers/InitialDataController.scala
Labels: backend, bug

#3415 Add recommended configuration to TaskTypes (backend only)
  MIGRATIONS.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.snap
  app/controllers/TaskTypeController.scala
  app/models/task/TaskType.scala
  conf/evolutions/033-tasktype-recommendedConfiguration.sql
  conf/evolutions/reversions/033-tasktype-recommendedConfiguration.sql
  test/db/taskTypes.csv
  tools/postgres/schema.sql
Labels: backend

#3425 remove -d (debug) from backend-tests in CI
  docker-compose.yml
Labels: CI, Epic

#3409 Fix bucket-collection related rendering bug
  CHANGELOG.md
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/layer_rendering_manager.js
Labels: frontend

#3406 Ensure that resolutions array is dense
  CHANGELOG.md
  app/assets/javascripts/oxalis/model_initialization.js
  flow-typed/npm/lodash_v4.x.x.js
Labels: frontend

#3416 Remove BaseDirService that watched binaryData symlinks
  CHANGELOG.md
  MIGRATIONS.md
  conf/application.conf
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreConfig.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreModule.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BaseDirService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/conf/standalone-datastore.conf
Labels: backend, enhancement, refactoring

#3430 In yarn refresh-schema, also invalidate Tables.scala
  package.json
Labels: backend

#3407 Only provide shortcut for tree search and not for comment search
  CHANGELOG.md
  app/assets/javascripts/oxalis/view/right-menu/search_popover.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
Labels: frontend

#3333 Reduce the free space between viewports in tracing
  app/assets/javascripts/navbar.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/layouting/default_layout_configs.js
  app/assets/javascripts/oxalis/view/layouting/golden_layout_adapter.js
  app/assets/javascripts/oxalis/view/layouting/layout_persistence.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
Labels: Epic, enhancement, frontend

#3445 Refresh screenshots
  app/assets/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  app/assets/javascripts/test/screenshots/Cortex_knossos.png
  app/assets/javascripts/test/screenshots/ROI2017_wkw.png
  app/assets/javascripts/test/screenshots/confocal-multi_knossos.png
  app/assets/javascripts/test/screenshots/dsA_2.png
  app/assets/javascripts/test/screenshots/e2006_knossos.png
  app/assets/javascripts/test/screenshots/fluro-rgb_knossos.png
Labels: testing

#3443 Fix: Deleting a layout bug
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/stylesheets/trace_view/_action_bar.less
Labels: bug, frontend

#3437 Fix guessed dataset boundingbox for non-zero-aligned datasets
  CHANGELOG.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataFormat.scala
Labels: backend, bug

#3451 Hotfix for editing TaskTypes
  CHANGELOG.md
  app/assets/javascripts/admin/tasktype/task_type_create_view.js
Labels: backend, bug, frontend

#3431 Script to merge volume tracing into on-disk segmentation
  tools/merge-volume-into-data-layer/.gitignore
  tools/merge-volume-into-data-layer/main.py
  tools/merge-volume-into-data-layer/requirements.txt
Labels: backend

#3428 Fix docker uid/gid + binaryData permissions. Persist postgres db
  .gitignore
  CHANGELOG.md
  Dockerfile
  README.md
  conf/evolutions/reversions/033-tasktype-recommendedConfiguration.sql
  docker-compose.yml
  start-docker.sh
Labels: backend, infrastructure

#3455 Fix rgb support
  CHANGELOG.md
  app/assets/javascripts/oxalis/shaders/main_data_fragment.glsl.js
Labels: bug

#3464 Enable /api/switch Cross-Organization
  app/controllers/Authentication.scala
Labels: backend, bug

#3469 Circleci-notify: linkify PR number
  .circleci/slack-notification.sh
Labels: infrastructure

#3476 (Backend only) Add project priority to progress report json
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/timetracking.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/timetracking.e2e.js.snap
  app/controllers/ReportController.scala
Labels: backend, enhancement

#3479 Better errors for screenshot tests
  app/assets/javascripts/test/puppeteer/dataset_rendering_helpers.js
  app/assets/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  app/assets/javascripts/test/screenshots/ROI2017_wkw.png
  app/assets/javascripts/test/screenshots/confocal-multi_knossos.png
  app/assets/javascripts/test/screenshots/dsA_2.png
Labels: testing

#3480 Simple fix to speed up dataset gallery
  app/assets/javascripts/dashboard/gallery_dataset_view.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
Labels: enhancement

#3427 Added script to apply all new evolutions
  package.json
  tools/postgres/apply_evolutions.sh
Labels: backend, infrastructure

#3483 Fix regression in texture_access shader
  app/assets/javascripts/oxalis/shaders/texture_access.glsl.js
Labels: bug

#3367 Store Meshes in Postgres
  MIGRATIONS.md
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/libs/request.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/controller/scene_controller_provider.js
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/geometries/arbitrary_plane.js
  app/assets/javascripts/oxalis/model/actions/annotation_actions.js
  app/assets/javascripts/oxalis/model/actions/ui_actions.js
  app/assets/javascripts/oxalis/model/mesh_store.js
  app/assets/javascripts/oxalis/model/reducers/annotation_reducer.js
  app/assets/javascripts/oxalis/model/reducers/reducer_helpers.js
  app/assets/javascripts/oxalis/model/reducers/ui_reducer.js
  app/assets/javascripts/oxalis/model/sagas/handle_mesh_changes.js
  app/assets/javascripts/oxalis/model/sagas/root_saga.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/javascripts/oxalis/view/arbitrary_view.js
  app/assets/javascripts/oxalis/view/components/button_component.js
  app/assets/javascripts/oxalis/view/layouting/default_layout_configs.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
  app/assets/javascripts/oxalis/view/plane_view.js
  app/assets/javascripts/oxalis/view/right-menu/meshes_view.js
  app/assets/javascripts/test/fixtures/skeletontracing_server_objects.js
  app/assets/javascripts/test/fixtures/tasktracing_server_objects.js
  app/assets/javascripts/test/fixtures/volumetracing_server_objects.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  app/assets/stylesheets/main.less
  app/controllers/MeshController.scala
  app/models/annotation/AnnotationService.scala
  app/models/mesh/Mesh.scala
  conf/evolutions/033-tasktype-recommendedConfiguration.sql
  conf/evolutions/034-meshes.sql
  conf/evolutions/reversions/032-scratch-datastores.sql
  conf/evolutions/reversions/034-meshes.sql
  conf/messages
  conf/webknossos.latest.routes
  tools/postgres/schema.sql
Labels: backend, frontend, new feature

#3487 thumbnails: correctly use zoom value if specified
  app/controllers/DataSetController.scala
  app/models/binary/DataStoreRpcClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/ImageThumbnail.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend, bug, datastore-changes

#3482 add annotation dataset foreign key
  MIGRATIONS.md
  conf/evolutions/035-add-annotation-dataset-foreign-key.sql
  conf/evolutions/reversions/035-add-annotation-dataset-foreign-key.sql
  tools/postgres/schema.sql
Labels: backend

#3441 Optimize performance for the list request /api/datasets
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  app/controllers/DataSetController.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/team/Team.scala
  app/models/user/UserService.scala
  docker-compose.yml
  docs/rest_api.md
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
Labels: backend, refactoring

#3497 Fix click/trace offset in orthogonal mode
  app/assets/javascripts/oxalis/constants.js
  app/assets/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/model/accessors/view_mode_accessor.js
  app/assets/javascripts/oxalis/view/layouting/layout_canvas_adapter.js
  app/assets/javascripts/oxalis/view/scalebar.js
  app/assets/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  app/assets/javascripts/test/screenshots/Cortex_knossos.png
  app/assets/javascripts/test/screenshots/ROI2017_wkw.png
  app/assets/javascripts/test/screenshots/confocal-multi_knossos.png
  app/assets/javascripts/test/screenshots/dsA_2.png
  app/assets/javascripts/test/screenshots/e2006_knossos.png
  app/assets/javascripts/test/screenshots/fluro-rgb_knossos.png
Labels: bug

#3466 Add Recommended Configuration to Task Types
  CHANGELOG.md
  MIGRATIONS.md
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/admin/tasktype/recommended_configuration_view.js
  app/assets/javascripts/admin/tasktype/task_type_create_view.js
  app/assets/javascripts/dashboard/dataset/dataset_import_view.js
  app/assets/javascripts/dashboard/dataset/validation.js
  app/assets/javascripts/libs/render_independently.js
  app/assets/javascripts/libs/user_settings.schema.json
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/model/sagas/root_saga.js
  app/assets/javascripts/oxalis/model/sagas/task_saga.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/recommended_configuration_modal.js
  app/assets/javascripts/oxalis/view/settings/setting_input_views.js
  app/assets/javascripts/test/backend-snapshot-tests/tasktypes.e2e.js
  app/assets/javascripts/test/enzyme/snapshot.e2e.js
  app/assets/javascripts/test/fixtures/tasktracing_server_objects.js
  app/assets/javascripts/test/libs/schema.spec.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.snap
  app/controllers/InitialDataController.scala
  app/controllers/UserController.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  conf/evolutions/036-add-lastTaskTypeId-to-user.sql
  conf/evolutions/reversions/036-add-lastTaskTypeId-to-user.sql
  conf/webknossos.latest.routes
  test/db/users.csv
  tools/postgres/schema.sql
  tools/test.sh
Labels: frontend
