Repository scalableminds/webknossos, pull requests merged in 2018-09, with the labels that each got.

#3133 Showing welcome header when there are no organisations
  CHANGELOG.md
  app/assets/javascripts/dashboard/spotlight_view.js
  app/assets/javascripts/messages.js
Labels: enhancement, frontend

#3066 Allow to activate a tree group
  CHANGELOG.md
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/model/accessors/skeletontracing_accessor.js
  app/assets/javascripts/oxalis/model/actions/skeletontracing_actions.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
  app/assets/javascripts/oxalis/model/sagas/skeletontracing_saga.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
  app/assets/javascripts/oxalis/view/right-menu/tree_hierarchy_view_helpers.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
  app/assets/javascripts/test/api/api_skeleton_latest.spec.js
  app/assets/javascripts/test/reducers/skeletontracing_reducer.spec.js
Labels: frontend

#3131 Relocating to dashboard after importing a dataset
  app/assets/javascripts/router.js
Labels: enhancement, frontend-easy

#3149 Fix regression which caused buckets not to load sometimes in view mode
  CHANGELOG.md
  app/assets/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_plane.js
  app/assets/javascripts/oxalis/model/sagas/prefetch_saga.js
  app/assets/javascripts/test/puppeteer/dataset_rendering.screenshot.js
  app/assets/javascripts/test/screenshots/dsA_2.png
Labels: frontend

#3145 When splitting a tree, the "original" tree should keep its name
  CHANGELOG.md
  app/assets/javascripts/oxalis/model/bucket_data_handling/mappings.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  app/assets/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
  app/assets/javascripts/test/reducers/skeletontracing_reducer.spec.js
  app/assets/javascripts/test/sagas/skeletontracing_saga.spec.js
Labels: frontend

#3156 Remove remaining instances of Play.current
  app/controllers/Authentication.scala
  app/controllers/DataSetController.scala
  app/models/annotation/AnnotationStore.scala
  app/models/annotation/TemporaryAnnotationStore.scala
  app/models/annotation/nml/NmlService.scala
  app/models/basics/TemporaryStore.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStoreHandler.scala
  app/oxalis/thirdparty/BrainTracing.scala
  app/utils/SQLHelpers.scala
  util/src/main/scala/com/scalableminds/util/auth/AccessToken.scala
  util/src/main/scala/com/scalableminds/util/auth/GithubOAuth.scala
  util/src/main/scala/com/scalableminds/util/auth/OAuth2Info.scala
  util/src/main/scala/com/scalableminds/util/auth/Session.scala
  util/src/main/scala/com/scalableminds/util/rpc/RPC.scala
  util/src/main/scala/com/scalableminds/util/rpc/RPCRequest.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceRepository.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/WebKnossosServer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/TemporaryStore.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/TemporaryTracingStore.scala
Labels: backend, refactoring

#3158 Datastore Health endpoint sends Ok as text, if Ok
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Application.scala
Labels: Epic, backend, datastore-changes, enhancement

#3153 Fix dashboard task, annotation list sorting
  CHANGELOG.md
  app/assets/javascripts/dashboard/dashboard_task_list_view.js
  app/assets/javascripts/dashboard/explorative_annotations_view.js
  app/assets/javascripts/oxalis/model/sagas/skeletontracing_saga.js
  app/assets/javascripts/test/sagas/skeletontracing_saga.spec.js
Labels: bug, frontend

#3167 fix race condition dependent bug of loading feature toggles
  CHANGELOG.md
  app/assets/javascripts/main.js
Labels: frontend

#3174 Make AnnotationStore singleton
  CHANGELOG.md
  app/WebKnossosModule.scala
Labels: backend, bug

#3181 Ask for confirmation when resetting task
  CHANGELOG.md
  app/assets/javascripts/dashboard/dashboard_task_list_view.js
  app/assets/javascripts/messages.js
Labels: frontend

#3178 Auto-clear checkboxes in user list view after changing experience domains
  CHANGELOG.md
  app/assets/javascripts/admin/user/user_list_view.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
Labels: frontend

#3162 Offload gzip compression and bucket loading/decoding/serializing to web workers
  .eslintrc.json
  .flowconfig
  CHANGELOG.md
  app/assets/javascripts/libs/handle_http_status.js
  app/assets/javascripts/libs/request.js
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/oxalis/model/accessors/dataset_accessor.js
  app/assets/javascripts/oxalis/model/accessors/flycam_accessor.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
  app/assets/javascripts/oxalis/model/reducers/flycam_reducer.js
  app/assets/javascripts/oxalis/view/settings/user_settings_view.js
  app/assets/javascripts/oxalis/workers/byte_array_to_base64.worker.js
  app/assets/javascripts/oxalis/workers/comlink_wrapper.js
  app/assets/javascripts/oxalis/workers/compress.worker.js
  app/assets/javascripts/oxalis/workers/decode_four_bit.worker.js
  app/assets/javascripts/oxalis/workers/fetch_buffer.worker.js
  app/assets/javascripts/oxalis/workers/headers_transfer_handler.js
  app/assets/javascripts/oxalis/workers/readme.md
  app/assets/javascripts/test/model/flycam_accessors.spec.js
  package.json
  webpack.config.js
  yarn.lock
Labels: frontend

#3171 play25 fix content-disposition and content-type for nml/zip downloads
  app/controllers/AnnotationIOController.scala
Labels: backend, refactoring

#3168 play25 logging
  app/controllers/AnnotationIOController.scala
  conf/application-logger.xml
  conf/logback.xml
  conf/logger_prod.xml
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
Labels: backend, refactoring

#3160 Play25 silhouette4
  app/ErrorHandler.scala
  app/SilhouetteModule.scala
  app/Startup.scala
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Application.scala
  app/controllers/Authentication.scala
  app/controllers/ConfigurationController.scala
  app/controllers/Controller.scala
  app/controllers/DataSetController.scala
  app/controllers/DataStoreController.scala
  app/controllers/InitialDataController.scala
  app/controllers/ProjectController.scala
  app/controllers/ReportController.scala
  app/controllers/ScriptController.scala
  app/controllers/StatisticsController.scala
  app/controllers/TaskController.scala
  app/controllers/TaskTypeController.scala
  app/controllers/TeamController.scala
  app/controllers/TimeController.scala
  app/controllers/UserController.scala
  app/controllers/UserTokenController.scala
  app/controllers/WKDataStoreController.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  app/oxalis/security/BearerTokenAuthenticatorRepository.scala
  app/oxalis/security/CombinedAuthenticatorService.scala
  app/oxalis/security/CredentialsProvider.scala
  app/oxalis/security/PasswordHasher.scala
  app/oxalis/security/Secured.scala
  app/oxalis/security/Token.scala
  app/oxalis/security/UserAuthInfoRepository.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  app/oxalis/security/WkSilhouetteEnvironment.scala
  app/utils/ErrorHandler.scala
  app/utils/WkConf.scala
  conf/application-logger.xml
  conf/application.conf
  conf/logback.xml
  conf/logger_prod.xml
  project/Dependencies.scala
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
  yarn.lock
Labels: backend, refactoring

#3125 Upgrade to Play 2.5 and Silhouette 4
  MIGRATIONS.md
  app/ErrorHandler.scala
  app/SilhouetteModule.scala
  app/Startup.scala
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Application.scala
  app/controllers/Authentication.scala
  app/controllers/ConfigurationController.scala
  app/controllers/Controller.scala
  app/controllers/DataSetController.scala
  app/controllers/DataStoreController.scala
  app/controllers/InitialDataController.scala
  app/controllers/ProjectController.scala
  app/controllers/ReportController.scala
  app/controllers/ScriptController.scala
  app/controllers/StatisticsController.scala
  app/controllers/TaskController.scala
  app/controllers/TaskTypeController.scala
  app/controllers/TeamController.scala
  app/controllers/TimeController.scala
  app/controllers/UserController.scala
  app/controllers/UserTokenController.scala
  app/controllers/WKDataStoreController.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStoreHandler.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  app/oxalis/security/BearerTokenAuthenticatorRepository.scala
  app/oxalis/security/CombinedAuthenticatorService.scala
  app/oxalis/security/CredentialsProvider.scala
  app/oxalis/security/PasswordHasher.scala
  app/oxalis/security/Secured.scala
  app/oxalis/security/Token.scala
  app/oxalis/security/UserAuthInfoRepository.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  app/oxalis/security/WkSilhouetteEnvironment.scala
  app/utils/ErrorHandler.scala
  app/utils/WkConf.scala
  conf/application.conf
  conf/logback.xml
  conf/logger_dev.xml
  conf/logger_prod.xml
  docker-compose.yml
  project/Dependencies.scala
  project/plugins.sbt
  util/src/main/scala/com/scalableminds/util/mvc/ExtendedController.scala
  util/src/main/scala/com/scalableminds/util/tools/ExtendedTypes.scala
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
  webknossos-datastore/app/DsRequestHandler.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Controller.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPC.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/WebKnossosServer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/FossilDBClient.scala
  webknossos-datastore/conf/logback-docker.xml
  webknossos-datastore/conf/logback.xml
  webknossos-datastore/conf/standalone-datastore.conf
Labels: backend, refactoring

#3199 remove color from logging change root level to INFO for datastore
  conf/logback.xml
  webknossos-datastore/conf/logback.xml
Labels: backend, bug

#3195 Per-Dataset Health Api Request
  app/controllers/DataSetController.scala
  conf/webknossos.routes
Labels: backend, enhancement

#3141 Renamed soma clicking
  CHANGELOG.md
  app/assets/javascripts/admin/tasktype/task_type_create_view.js
  app/assets/javascripts/admin/tasktype/task_type_list_view.js
  app/assets/javascripts/oxalis/view/settings/user_settings_view.js
Labels: enhancement, frontend-easy

#3200 Upgrade flow to 0.80
  app/assets/javascripts/dashboard/dataset/helper_components.js
  package.json
  yarn.lock
Labels: frontend

#3121 Streamline password reset flow
  app/assets/javascripts/admin/auth/finish_reset_password_view.js
  app/assets/javascripts/admin/auth/start_reset_password_view.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/view/settings/user_settings_view.js
  app/assets/javascripts/router.js
  app/views/mail/resetPassword.scala.html
Labels: backend, frontend

#3206 Enable LRU sorting
  CHANGELOG.md
  app/assets/javascripts/dashboard/advanced_dataset/advanced_dataset_view.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
Labels: frontend

#3208 Auto remove generated flow-check files on git checkout
  package.json
  yarn.lock
Labels: frontend

#3214 use new secret key config key in standalone-datastore.conf
  webknossos-datastore/conf/standalone-datastore.conf
Labels: backend, datastore-changes, refactoring

#3077 Redesign change user experience modal
  CHANGELOG.md
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/admin/user/experience_modal_view.js
  app/assets/javascripts/admin/user/user_list_view.js
  app/assets/javascripts/components/select_experience_domain.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
  app/assets/stylesheets/_admin.less
  app/assets/stylesheets/main.less
  flow-typed/npm/antd_vx.x.x.js
Labels: enhancement, frontend

#3227 Improve nml parsing error messages for missing strings
  CHANGELOG.md
  app/assets/javascripts/oxalis/model/helpers/nml_helpers.js
Labels: frontend

#3219 Fix dashboard URLs for admin view
  CHANGELOG.md
  app/assets/javascripts/dashboard/dashboard_view.js
  app/assets/javascripts/router.js
Labels: bug, frontend

#3070 Custom viewports
  CHANGELOG.md
  app/assets/javascripts/admin/help/keyboardshortcut_view.js
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/constants.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/combinations/volumetracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/renderer.js
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/geometries/materials/node_shader.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/geometries/skeleton.js
  app/assets/javascripts/oxalis/model/accessors/view_mode_accessor.js
  app/assets/javascripts/oxalis/model/actions/view_mode_actions.js
  app/assets/javascripts/oxalis/model/reducers/view_mode_reducer.js
  app/assets/javascripts/oxalis/model/volumetracing/volumelayer.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/action-bar/dataset_position_view.js
  app/assets/javascripts/oxalis/view/action-bar/save_button.js
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/javascripts/oxalis/view/action-bar/view_modes_view.js
  app/assets/javascripts/oxalis/view/arbitrary_view.js
  app/assets/javascripts/oxalis/view/input_catcher.js
  app/assets/javascripts/oxalis/view/input_catchers.js
  app/assets/javascripts/oxalis/view/layouting/default_layout_configs.js
  app/assets/javascripts/oxalis/view/layouting/golden_layout_adapter.js
  app/assets/javascripts/oxalis/view/layouting/golden_layout_helpers.js
  app/assets/javascripts/oxalis/view/layouting/layout_canvas_adapter.js
  app/assets/javascripts/oxalis/view/layouting/layout_persistence.js
  app/assets/javascripts/oxalis/view/layouting/portal_utils.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
  app/assets/javascripts/oxalis/view/plane_view.js
  app/assets/javascripts/oxalis/view/recording_switch.js
  app/assets/javascripts/oxalis/view/right-menu/abstract_tree_renderer.js
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
  app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
  app/assets/javascripts/oxalis/view/right-menu/mapping_info_view.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
  app/assets/javascripts/oxalis/view/right_menu_view.js
  app/assets/javascripts/oxalis/view/settings/user_settings_view.js
  app/assets/javascripts/oxalis/view/td_view_controls.js
  app/assets/javascripts/oxalis/view/tracing_layout_view.js
  app/assets/javascripts/oxalis/view/tracing_view.js
  app/assets/javascripts/router.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
  app/assets/stylesheets/goldenlayout_overwrites.less
  app/assets/stylesheets/main.less
  app/assets/stylesheets/trace_view/_right_menu.less
  app/assets/stylesheets/trace_view/_tracing_view.less
  app/models/configuration/UserConfiguration.scala
  package.json
  webpack.config.js
  yarn.lock
Labels: frontend

#3231 Speed up CI
  .circleci/config.yml
  .circleci/not-on-master.sh
  .flowconfig
  package.json
  webpack.config.js
  yarn.lock
Labels: CI

#3234 Don't report coverage for master builds
  .circleci/config.yml
  .circleci/not-on-master.sh
Labels: CI

#3215 Add button for collapsing all comments
  CHANGELOG.md
  app/assets/javascripts/oxalis/view/components/markdown_modal.js
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
Labels: frontend

#3194 Add UI to restore previous versions of a tracing
  CHANGELOG.md
  app/assets/javascripts/admin/admin_rest_api.js
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/controller/url_manager.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/actions/annotation_actions.js
  app/assets/javascripts/oxalis/model/actions/ui_actions.js
  app/assets/javascripts/oxalis/model/reducers/annotation_reducer.js
  app/assets/javascripts/oxalis/model/reducers/ui_reducer.js
  app/assets/javascripts/oxalis/model/sagas/skeletontracing_saga.js
  app/assets/javascripts/oxalis/model/sagas/update_actions.js
  app/assets/javascripts/oxalis/model_initialization.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/javascripts/oxalis/view/action_bar_view.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
  app/assets/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
  app/assets/javascripts/oxalis/view/version_view.js
  app/assets/stylesheets/trace_view/_tracing_view.less
  docs/tracing_ui.md
  package.json
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/FossilDBClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/tracings/skeleton/SkeletonTracingService.scala
  yarn.lock
Labels: backend, datastore-changes, frontend

#3222 Prevent browser from loading dragged file when drag-area is missed
  CHANGELOG.md
  app/assets/javascripts/components/disable_generic_dnd.js
  app/assets/javascripts/router.js
Labels: frontend

#3224 Add stacked bar charts to progress report table
  CHANGELOG.md
  app/assets/javascripts/admin/statistic/project_progress_report_view.js
  app/assets/javascripts/components/stacked_bar_chart.js
Labels: frontend

#3229 Hide login in navbar when corresponding feature flag is enabled
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/navbar.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  conf/application.conf
Labels: frontend

#3239 Fix hard-source breaking master
  .flowconfig
  package.json
  yarn.lock
Labels: CI

#3228 Use AND search instead of OR everyhwere (fixes #3197)
  CHANGELOG.md
  app/assets/javascripts/admin/project/project_list_view.js
  app/assets/javascripts/admin/scripts/script_list_view.js
  app/assets/javascripts/admin/tasktype/task_type_list_view.js
  app/assets/javascripts/admin/team/team_list_view.js
  app/assets/javascripts/admin/user/user_list_view.js
  app/assets/javascripts/dashboard/advanced_dataset/advanced_dataset_view.js
  app/assets/javascripts/libs/utils.js
Labels: frontend

#3244 Don't error in postcheckout hook if there are no flow-check files
  package.json
Labels: frontend

#3238 datastore Dockerfile: chown after COPY
  webknossos-datastore/Dockerfile
Labels: infrastructure

#3245 Respect resolutions when copying segmentation slice
  CHANGELOG.md
  app/assets/javascripts/oxalis/model/sagas/volumetracing_saga.js
Labels: bug, frontend

#3246 Show reset layout option in view mode
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/javascripts/oxalis/view/action_bar_view.js
Labels: frontend

#3233 Experience domain field in task creation as select component
  CHANGELOG.md
  app/assets/javascripts/admin/task/task_create_form_view.js
  app/assets/javascripts/admin/user/experience_modal_view.js
  app/assets/javascripts/components/select_experience_domain.js
  app/assets/javascripts/messages.js
Labels: enhancement, frontend

#3250 Tweak colors and rounding in project progress report
  app/assets/javascripts/admin/statistic/project_progress_report_view.js
  app/assets/javascripts/components/stacked_bar_chart.js
Labels: frontend

#3253 fix test.sh when not calling prepare before first run
  tools/test.sh
Labels: bug, frontend, testing

#3164 Show fallback data for missing buckets
  app/assets/javascripts/libs/request.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/pullqueue.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
  app/assets/javascripts/oxalis/shaders/coords.glsl.js
  app/assets/javascripts/oxalis/shaders/main_data_fragment.glsl.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/settings/dataset_settings_view.js
  app/assets/javascripts/oxalis/view/settings/setting_input_views.js
  app/assets/javascripts/oxalis/workers/fetch_buffer_with_headers.worker.js
  app/assets/javascripts/test/helpers/apiHelpers.js
  app/assets/javascripts/test/model/binary/layers/wkstore_adapter.spec.js
  app/assets/javascripts/test/model/binary/pullqueue.spec.js
  app/models/configuration/DataSetConfiguration.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
Labels: backend, datastore-changes, enhancement, frontend

#3258 fix missing-buckets header for cors
  app/assets/javascripts/libs/request.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
Labels: frontend

#3257 Decrease total instances
  MIGRATIONS.md
  conf/evolutions/026-decrease-total-instance.sql
  conf/evolutions/reversions/026-decrease-total-instance.sql
  tools/postgres/schema.sql
Labels: backend

#3242 Allow adding STL files to 3D scene
  CHANGELOG.md
  app/assets/javascripts/libs/parse_stl_buffer.js
  app/assets/javascripts/libs/read_file.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
  docs/images/stl_mesh.png
  docs/tracing_ui.md
Labels: frontend

#3254 Auto-focus/highlight relevant domains in experience modal and allow copy&paste
  CHANGELOG.md
  app/assets/javascripts/admin/user/experience_modal_view.js
  app/assets/javascripts/admin/user/user_list_view.js
  app/assets/javascripts/components/highlightable_row.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
  app/assets/stylesheets/main.less
  flow-typed/npm/antd_vx.x.x.js
Labels: frontend

#3270 Allow accessing missing-buckets-header in CORS requests
  CHANGELOG.md
  webknossos-datastore/app/DsRequestHandler.scala
Labels: backend, datastore-changes

#3261 Non-public datasets accessed using a token do honor default settings
  app/controllers/ConfigurationController.scala
Labels: backend

#3262 Make sure texture is not updated too early since these updates get lost silently
  CHANGELOG.md
  app/assets/javascripts/libs/UpdatableTexture.js
  app/assets/javascripts/libs/utils.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/texture_bucket_manager.js
  app/assets/javascripts/oxalis/model/data_layer.js
  app/assets/javascripts/test/model/texture_bucket_manager.spec.js
Labels: frontend

#3267 Ensure that volume labeling works for 'missing buckets'
  CHANGELOG.md
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/data_cube.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/temporal_bucket_manager.js
  app/assets/javascripts/oxalis/view/action_bar_view.js
Labels: frontend

#3272 Do not line wrap comments
  CHANGELOG.md
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/comment.js
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
  app/assets/javascripts/oxalis/view/right-menu/comment_tab/tree_with_comments.js
Labels: bug, frontend

#3268 Make copy-to-my-account button an async button
  app/assets/javascripts/components/async_clickables.js
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
Labels: frontend

#3256 Shrink viewport gaps
  CHANGELOG.md
  app/assets/javascripts/oxalis/view/arbitrary_view.js
  app/assets/javascripts/oxalis/view/input_catcher.js
  app/assets/javascripts/oxalis/view/layouting/default_layout_configs.js
  app/assets/javascripts/oxalis/view/layouting/golden_layout_adapter.js
  app/assets/javascripts/oxalis/view/layouting/layout_persistence.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
  app/assets/javascripts/oxalis/view/plane_view.js
  app/assets/stylesheets/goldenlayout_overwrites.less
  app/assets/stylesheets/trace_view/_tracing_view.less
Labels: frontend

#3273 Allow missing buckets header
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
Labels: backend, datastore-changes, planned

#3213 remove unused annotation readonly route
  app/controllers/AnnotationController.scala
  app/models/annotation/AnnotationRestrictions.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/handler/SavedTracingInformationHandler.scala
  conf/webknossos.routes
Labels: backend, refactoring

#3218 update error messages
  app/assets/javascripts/test/backend-snapshot-tests/teamstructure.e2e.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.snap
  app/controllers/Authentication.scala
  app/controllers/TaskController.scala
  conf/messages
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
Labels: planned

#3277 remove the bucket-loading retry workaround
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/Cube.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
Labels: backend, datastore-changes, refactoring

#3282 Improve handling of layout dimensions for golden layout and canvas
  app/assets/javascripts/oxalis/view/arbitrary_view.js
  app/assets/javascripts/oxalis/view/layouting/golden_layout_adapter.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
  app/assets/javascripts/oxalis/view/plane_view.js
  app/assets/stylesheets/trace_view/_tracing_view.less
Labels: frontend

#3276 Fix screenshot tests for real
  app/assets/javascripts/libs/request.js
  app/assets/javascripts/oxalis/view/arbitrary_view.js
  app/assets/javascripts/oxalis/view/layouting/golden_layout_adapter.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
  app/assets/javascripts/oxalis/view/plane_view.js
  app/assets/javascripts/test/puppeteer/dataset_rendering.screenshot.js
  app/assets/javascripts/test/puppeteer/dataset_rendering_helpers.js
  app/assets/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  app/assets/javascripts/test/screenshots/Cortex_knossos.png
  app/assets/javascripts/test/screenshots/ROI2017_wkw.png
  app/assets/javascripts/test/screenshots/confocal-multi_knossos.png
  app/assets/javascripts/test/screenshots/dsA_2.png
  app/assets/javascripts/test/screenshots/e2006_knossos.png
  app/assets/javascripts/test/screenshots/fluro-rgb_knossos.png
  app/assets/stylesheets/trace_view/_tracing_view.less
  package.json
Labels: planned, testing

#3275 Upgrade to Babel 7
  .babelrc
  .flowconfig
  app/assets/javascripts/libs/diffable_map.js
  app/assets/javascripts/test/api/api_skeleton_latest.spec.js
  app/assets/javascripts/test/api/api_v2.spec.js
  app/assets/javascripts/test/backend-snapshot-tests/tasks.e2e.js
  app/assets/javascripts/test/libs/diffable_map.spec.js
  app/assets/javascripts/test/model/binary/cube.spec.js
  app/assets/javascripts/test/puppeteer/dataset_rendering.screenshot.js
  app/assets/javascripts/test/sagas/skeletontracing_saga.spec.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
  package.json
  tools/test.sh
  webpack.config.js
  yarn.lock
Labels: enhancement, frontend

#3283 Dont brush outside viewport
  CHANGELOG.md
  app/assets/javascripts/libs/mjs.js
  app/assets/javascripts/oxalis/model/sagas/volumetracing_saga.js
  app/assets/javascripts/oxalis/model/volumetracing/volumelayer.js
  app/assets/javascripts/test/sagas/volumetracing_saga.spec.js
Labels: bug, frontend
