Repository scalableminds/webknossos, pull requests merged in 2019-12, with the labels that each got.

#4346 Jump to the center of the bounding box if find-data doesn't find data
  CHANGELOG.md
  frontend/javascripts/libs/toast.js
  frontend/javascripts/oxalis/model/sagas/root_saga.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
Labels: automerge

#4345 Disable volume shortcuts in read-only mode
  CHANGELOG.md
  frontend/javascripts/oxalis/model/reducers/volumetracing_reducer.js
  frontend/javascripts/oxalis/view/action-bar/volume_actions_view.js
Labels: automerge

#4344 Fix conversion to dense resolution in case of anisotropic, partial resolutions
  CHANGELOG.md
  frontend/javascripts/oxalis/model_initialization.js
  frontend/javascripts/test/model/model_resolutions.spec.js
Labels: automerge

#4304 Shared annotations
  CHANGELOG.md
  MIGRATIONS.md
  app/controllers/AnnotationController.scala
  app/controllers/TeamController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
  app/models/binary/DataSet.scala
  conf/evolutions/049-annotation-listed-teams.sql
  conf/evolutions/reversions/048-annotation-listed-teams.sql
  conf/webknossos.latest.routes
  docs/dashboard.md
  docs/images/shared_annotations_tab.png
  docs/images/sharing_modal.png
  docs/sharing.md
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/api_flow_types.js
  frontend/javascripts/components/text_with_description.js
  frontend/javascripts/dashboard/dashboard_view.js
  frontend/javascripts/dashboard/dataset/team_selection_component.js
  frontend/javascripts/dashboard/explorative_annotations_view.js
  frontend/javascripts/dashboard/shared_annotations_view.js
  frontend/javascripts/messages.js
  frontend/javascripts/navbar.js
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.js
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  frontend/javascripts/oxalis/view/components/editable_text_label.js
  tools/postgres/schema.sql
Labels: backend, frontend

#4349 adds y-axis scale to the histogram view
  CHANGELOG.md
  frontend/javascripts/oxalis/view/settings/histogram_view.js
Labels: frontend, frontend-easy

#4369 Clip long dataset status before writing to db
  app/models/binary/DataSet.scala
Labels: automerge, backend, bug

#4375 cleanup imprint
  frontend/javascripts/components/legal.js
Labels: automerge

#4331 Fix task list access restrictions
  CHANGELOG.md
  app/controllers/ProjectController.scala
  app/models/task/Task.scala
  app/utils/SQLHelpers.scala
Labels: backend

#4376 Fix nightly
  .circleci/config.yml
  conf/application.conf
  docs/rest_api.md
  frontend/javascripts/test/puppeteer/dataset_rendering.screenshot.js
  tools/test-iframe-page.html
  tools/volume-stress-test/volume-stress-client.sh
Labels: automerge

#4352 Fix Android panning to move in plane
  frontend/javascripts/libs/input.js
Labels: bug, frontend

#4380 Sanitize layer names for glsl code
  frontend/javascripts/oxalis/geometries/materials/plane_material_factory.js
Labels: bug

#4370 Improving the selection of the next active tree after tree deletion
  CHANGELOG.md
  frontend/javascripts/dashboard/advanced_dataset/dataset_table.js
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
Labels: enhancement, frontend
