Repository scalableminds/webknossos, pull requests merged in 2019-10, with the labels that each got.

#4290 Remove different-dataset-warning when importing NML
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/view/right-menu/trees_tab_view.js
Labels: automerge

#4288 Improve fossildb conflict error message
  frontend/javascripts/messages.js
Labels: automerge, frontend

#4294 configure register mail
  app/controllers/Authentication.scala
  app/oxalis/mail/DefaultMails.scala
  app/views/mail/register.scala.html
Labels: automerge, backend, low-pri

#4291 Don't provide shortcut for comment search
  CHANGELOG.md
  frontend/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
Labels: automerge

#4300 change biovision to voxelytics
  docs/datasets.md
  frontend/javascripts/pages/frontpage/pricing_view.js
Labels: automerge

#4301 Ask user to login if dataset not found
  CHANGELOG.md
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/DataSetController.scala
  app/models/annotation/AnnotationService.scala
  conf/messages
Labels: UX, backend

#4303 Fix missing uint64 voxel type in evolution
  CHANGELOG.md
  MIGRATIONS.md
  conf/evolutions/046-fix-missing-voxel-type.sql
  conf/evolutions/reversions/046-fix-missing-voxel-type.sql
  tools/postgres/schema.sql
Labels: automerge, backend

#4306 Update time logging
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/SkeletonTracingController.scala
Labels: backend

#4307 Added Layer 4 Publication to docs
  docs/publications.md
Labels: automerge, documentation

#4309 19.11.0: update changelog and migration guide
  CHANGELOG.md
  MIGRATIONS.md
Labels: automerge

#4310 Investigate tracingstore perf
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreConfig.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/SkeletonTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/TracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/slacknotification/SlackNotificationService.scala
  webknossos-tracingstore/conf/standalone-tracingstore.conf
Labels: backend
