Repository scalableminds/webknossos, pull requests merged in 2019-02, with the labels that each got.

#3719 Fix checkbox selection for trees
  CHANGELOG.md
  app/assets/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
Labels: frontend

#3722 Edge collection tests
  app/assets/javascripts/libs/diffable_map.js
  app/assets/javascripts/oxalis/model/edge_collection.js
  app/assets/javascripts/test/model/edge_collection.spec.js
Labels: testing

#3723 Update prettier
  package.json
  yarn.lock
Labels: frontend

#3716 Allow to import NMLs which were created for different datasets
  CHANGELOG.md
  app/assets/javascripts/libs/async_confirm.js
  app/assets/javascripts/messages.js
  app/assets/javascripts/oxalis/model/helpers/nml_helpers.js
  app/assets/javascripts/oxalis/view/right-menu/trees_tab_view.js
Labels: frontend

#3727 fix element class conversion to/from protobuf
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/ProtoGeometryImplicits.scala
Labels: backend, bug, datastore-changes

#3724 Do not show task modals in read-only tasks
  CHANGELOG.md
  app/assets/javascripts/oxalis/model/sagas/task_saga.js
Labels: frontend-easy

#3712 Add Volume Tasks
  CHANGELOG.md
  MIGRATIONS.md
  app/assets/javascripts/admin/api_flow_types.js
  app/assets/javascripts/admin/task/task_create_form_view.js
  app/assets/javascripts/admin/tasktype/task_type_create_view.js
  app/assets/javascripts/admin/tasktype/task_type_list_view.js
  app/assets/javascripts/dashboard/dashboard_task_list_view.js
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/model/accessors/dataset_accessor.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/data_cube.js
  app/assets/javascripts/oxalis/model/reducers/reducer_helpers.js
  app/assets/javascripts/oxalis/model_initialization.js
  app/assets/javascripts/oxalis/view/action_bar_view.js
  app/assets/javascripts/test/backend-snapshot-tests/tasktypes.e2e.js
  app/assets/javascripts/test/fixtures/tasktracing_server_objects.js
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.snap
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  app/assets/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
  app/controllers/AnnotationIOController.scala
  app/controllers/TaskController.scala
  app/controllers/TaskTypeController.scala
  app/models/annotation/AnnotationMerger.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/TracingStoreRpcClient.scala
  app/models/annotation/nml/NmlParser.scala
  app/models/annotation/nml/NmlWriter.scala
  app/models/task/TaskType.scala
  conf/evolutions/039-add-tasktype-tracingtype.sql
  conf/evolutions/reversions/039-add-tasktype-tracingtype.sql
  conf/messages
  test/backend/NMLUnitTestSuite.scala
  test/db/taskTypes.csv
  tools/postgres/schema.sql
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/SkeletonTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/TracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingType.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
  webknossos-tracingstore/proto/SkeletonTracing.proto
  webknossos-tracingstore/proto/VolumeTracing.proto
Labels: backend, datastore-changes, frontend, volume

#3729 Exponential backoff for retrying saving
  app/assets/javascripts/oxalis/api/api_latest.js
  app/assets/javascripts/oxalis/api/api_v2.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/model.js
  app/assets/javascripts/oxalis/model/actions/save_actions.js
  app/assets/javascripts/oxalis/model/sagas/save_saga.js
  app/assets/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  app/assets/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
  app/assets/javascripts/oxalis/view/version_list.js
  app/assets/javascripts/test/sagas/save_saga.spec.js
Labels: frontend

#3750 Refactor bucket counting
  app/assets/javascripts/libs/ThreeDMap.js
  app/assets/javascripts/oxalis/constants.js
  app/assets/javascripts/oxalis/controller.js
  app/assets/javascripts/oxalis/controller/camera_controller.js
  app/assets/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  app/assets/javascripts/oxalis/controller/scene_controller.js
  app/assets/javascripts/oxalis/controller/td_controller.js
  app/assets/javascripts/oxalis/controller/url_manager.js
  app/assets/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
  app/assets/javascripts/oxalis/controller/viewmodes/plane_controller.js
  app/assets/javascripts/oxalis/geometries/materials/plane_material_factory.js
  app/assets/javascripts/oxalis/model/accessors/dataset_accessor.js
  app/assets/javascripts/oxalis/model/accessors/flycam_accessor.js
  app/assets/javascripts/oxalis/model/accessors/view_mode_accessor.js
  app/assets/javascripts/oxalis/model/actions/settings_actions.js
  app/assets/javascripts/oxalis/model/actions/view_mode_actions.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/flight_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/oblique_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/layer_rendering_manager.js
  app/assets/javascripts/oxalis/model/bucket_data_handling/pullqueue.js
  app/assets/javascripts/oxalis/model/reducers/view_mode_reducer.js
  app/assets/javascripts/oxalis/model/sagas/isosurface_saga.js
  app/assets/javascripts/oxalis/model/sagas/prefetch_saga.js
  app/assets/javascripts/oxalis/shaders/main_data_fragment.glsl.js
  app/assets/javascripts/oxalis/shaders/utils.glsl.js
  app/assets/javascripts/oxalis/store.js
  app/assets/javascripts/oxalis/view/action-bar/dataset_position_view.js
  app/assets/javascripts/oxalis/view/action-bar/view_modes_view.js
  app/assets/javascripts/oxalis/view/action_bar_view.js
  app/assets/javascripts/oxalis/view/arbitrary_view.js
  app/assets/javascripts/oxalis/view/input_catcher.js
  app/assets/javascripts/oxalis/view/layouting/default_layout_configs.js
  app/assets/javascripts/oxalis/view/layouting/tracing_layout_view.js
  app/assets/javascripts/oxalis/view/plane_view.js
  app/assets/javascripts/oxalis/view/settings/dataset_settings_view.js
  app/assets/javascripts/oxalis/view/settings/user_settings_view.js
  flow-typed/npm/js-priority-queue_vx.x.x.js
Labels: refactoring

#3756 Fix nocache attribute in main html template
  app/views/main.scala.html
Labels: backend, bug, frontend

#3731 Mark active node with a halo
  CHANGELOG.md
  frontend/javascripts/oxalis/geometries/materials/node_shader.js
  frontend/javascripts/oxalis/shaders/main_data_fragment.glsl.js
Labels: frontend

#3720 List Currently Available Mappings
  .eslintrc.json
  CHANGELOG.md
  flow-typed/npm/antd_vx.x.x.js
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/api_flow_types.js
  frontend/javascripts/libs/progress_callback.js
  frontend/javascripts/oxalis/api/api_latest.js
  frontend/javascripts/oxalis/api/api_v2.js
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
  frontend/javascripts/oxalis/model/actions/actions.js
  frontend/javascripts/oxalis/model/actions/dataset_actions.js
  frontend/javascripts/oxalis/model/actions/settings_actions.js
  frontend/javascripts/oxalis/model/bucket_data_handling/mappings.js
  frontend/javascripts/oxalis/model/data_layer.js
  frontend/javascripts/oxalis/model/reducers/dataset_reducer.js
  frontend/javascripts/oxalis/model/reducers/settings_reducer.js
  frontend/javascripts/oxalis/model_initialization.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js
  frontend/stylesheets/trace_view/_right_menu.less
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/MappingProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceImporter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend, datastore-changes, frontend

#3758 Fix connected tree test in nml parser
  CHANGELOG.md
  frontend/javascripts/oxalis/model/helpers/nml_helpers.js
Labels: bug, frontend

#3762 Only limit pane width for segmentation tab
  frontend/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
  frontend/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
  frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js
  frontend/javascripts/oxalis/view/right-menu/meshes_view.js
  frontend/javascripts/oxalis/view/right-menu/trees_tab_view.js
  frontend/stylesheets/trace_view/_right_menu.less
Labels: frontend

#3759 Fix some issues with batch saving
  frontend/javascripts/oxalis/model/reducers/save_reducer.js
  frontend/javascripts/oxalis/model/sagas/save_saga.js
  frontend/javascripts/test/sagas/save_saga.spec.js
Labels: bug, frontend

#3746 Fix URL hash change
  CHANGELOG.md
  frontend/javascripts/oxalis/controller/url_manager.js
Labels: frontend

#3766 Cancelled Annotations should not be viewable
  app/controllers/AnnotationController.scala
  conf/messages
Labels: backend, bug

#3764 re-report datasource json on dataset reload trigger
  frontend/javascripts/admin/admin_rest_api.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend, datastore-changes

#3775 Increase Akka Request Timeouts
  conf/application.conf
Labels: backend, bug

#3777 Check whether golden layout is initialized before calling toConfig
  frontend/javascripts/oxalis/view/layouting/golden_layout_adapter.js
Labels: bug

#3772 Fix timeline chart by explicitly setting start and end time
  CHANGELOG.md
  frontend/javascripts/admin/time/time_line_view.js
  package.json
  yarn.lock
Labels: bug

#3782 Snapshot test volume and hybrid tracings
  frontend/javascripts/test/backend-snapshot-tests/annotations.e2e.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
Labels: testing

#3783 Fix rendering artifacts in tasks that only allow flight mode
  CHANGELOG.md
  frontend/javascripts/oxalis/controller/scene_controller.js
  frontend/javascripts/oxalis/geometries/cube.js
Labels: bug, frontend

#3784 Avoid unhandled rejection which leads to [Object object] error
  frontend/javascripts/libs/error_handling.js
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.js
Labels: frontend

#3790 Do not investigate failed bucket requests
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/libs/error_handling.js
Labels: bug

#3792 Switch TaskType Summary and Project name in Dashboard Task List View
  CHANGELOG.md
  frontend/javascripts/dashboard/dashboard_task_list_view.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
Labels: frontend

#3799 Better logging of unhandledrejection errors
  frontend/javascripts/libs/error_handling.js
  frontend/javascripts/libs/request.js
  frontend/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
Labels: enhancement

#3794 In Transfer Tasks Modal, show User Name
  app/controllers/ProjectController.scala
  app/models/project/Project.scala
  frontend/javascripts/admin/api_flow_types.js
  frontend/javascripts/admin/project/project_create_view.js
  frontend/javascripts/admin/project/project_list_view.js
  frontend/javascripts/admin/project/transfer_all_tasks_modal.js
  frontend/javascripts/admin/scripts/script_create_view.js
  frontend/javascripts/admin/statistic/statistic_view.js
  frontend/javascripts/admin/task/task_search_form.js
  frontend/javascripts/admin/time/time_line_view.js
  frontend/javascripts/admin/user/user_list_view.js
  frontend/javascripts/admin/user/user_selection_component.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
Labels: backend, frontend

#3802 fix binarydata docker permissions
  README.md
  docs/getting_started.md
  start-docker.sh
Labels: infrastructure

#3752 Create org from register form and register from onboarding
  frontend/javascripts/admin/auth/registration_view.js
  frontend/javascripts/admin/onboarding.js
  frontend/stylesheets/antd_overwrites.less
  frontend/stylesheets/goldenlayout_overwrites.less
  frontend/stylesheets/main.less
Labels: frontend

#3788 Clean up: Remove Volume Version-Freezing code
  conf/application.conf
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreConfig.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/TracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/conf/standalone-tracingstore.conf
Labels: backend, refactoring

#3767 Silently ignore duplicate tracing save requests
  CHANGELOG.md
  frontend/javascripts/libs/uid_generator.js
  frontend/javascripts/oxalis/model/reducers/save_reducer.js
  frontend/javascripts/oxalis/model/sagas/save_saga.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/test/helpers/saveHelpers.js
  frontend/javascripts/test/sagas/save_saga.spec.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/TemporaryStore.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/SkeletonTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/TracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/UpdateActions.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/SkeletonTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: backend

#3682 Route to find data
  CHANGELOG.md
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend, frontend

#3815 Send the find data request to the datastore
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
Labels: bug, frontend

#3814 Optional dataset tokens
  app/controllers/UserTokenController.scala
  conf/webknossos.latest.routes
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AccessTokenService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataStoreWkRpcClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreWkRpcClient.scala
Labels: backend, datastore-changes

#3828 Add eslint-plugin-eslint-comments and fix issues
  .eslintrc.json
  frontend/javascripts/admin/scripts/script_list_view.js
  frontend/javascripts/admin/task/task_annotation_view.js
  frontend/javascripts/admin/task/task_list_view.js
  frontend/javascripts/admin/tasktype/task_type_list_view.js
  frontend/javascripts/admin/team/team_list_view.js
  frontend/javascripts/admin/user/user_list_view.js
  frontend/javascripts/components/async_clickables.js
  frontend/javascripts/components/highlightable_row.js
  frontend/javascripts/dashboard/advanced_dataset/advanced_dataset_view.js
  frontend/javascripts/dashboard/advanced_dataset/dataset_access_list_view.js
  frontend/javascripts/dashboard/advanced_dataset/dataset_action_view.js
  frontend/javascripts/dashboard/dashboard_task_list_view.js
  frontend/javascripts/dashboard/dashboard_view.js
  frontend/javascripts/dashboard/explorative_annotations_view.js
  frontend/javascripts/libs/keyboard.js
  frontend/javascripts/libs/parse_stl_buffer.js
  frontend/javascripts/libs/request.js
  frontend/javascripts/libs/resizable_buffer.js
  frontend/javascripts/libs/stl_exporter.js
  frontend/javascripts/libs/utils.js
  frontend/javascripts/libs/vector_input.js
  frontend/javascripts/navbar.js
  frontend/javascripts/oxalis/model/actions/actions.js
  frontend/javascripts/oxalis/model/actions/flycam_actions.js
  frontend/javascripts/oxalis/model/actions/save_actions.js
  frontend/javascripts/oxalis/model/actions/settings_actions.js
  frontend/javascripts/oxalis/model/actions/ui_actions.js
  frontend/javascripts/oxalis/model/actions/user_actions.js
  frontend/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/flight_bucket_picker.js
  frontend/javascripts/oxalis/model/bucket_data_handling/bucket_traversals.js
  frontend/javascripts/oxalis/model/reducers/reducer_helpers.js
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.js
  frontend/javascripts/oxalis/view/action-bar/user_scripts_modal_view.js
  frontend/javascripts/oxalis/view/right-menu/comment_tab/comment.js
  frontend/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
  frontend/javascripts/oxalis/view/right-menu/comment_tab/tree_with_comments.js
  frontend/javascripts/oxalis/view/right-menu/meshes_view.js
  frontend/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
  frontend/javascripts/oxalis/view/settings/setting_input_views.js
  frontend/javascripts/router.js
  frontend/javascripts/test/reducers/save_reducer.spec.js
  frontend/javascripts/test/reducers/volumetracing_reducer.spec.js
  frontend/javascripts/test/sagas/skeletontracing_saga.spec.js
  frontend/javascripts/test/sagas/volumetracing_saga.spec.js
  package.json
  tools/proxy/proxy.js
  yarn.lock
Labels: frontend

#3827 Make brush size a user setting
  CHANGELOG.md
  frontend/javascripts/admin/tasktype/recommended_configuration_view.js
  frontend/javascripts/libs/user_settings.schema.json
  frontend/javascripts/oxalis/controller/viewmodes/plane_controller.js
  frontend/javascripts/oxalis/geometries/materials/plane_material_factory.js
  frontend/javascripts/oxalis/model/actions/volumetracing_actions.js
  frontend/javascripts/oxalis/model/reducers/volumetracing_reducer.js
  frontend/javascripts/oxalis/model/volumetracing/volumelayer.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/settings/user_settings_view.js
  frontend/stylesheets/_admin.less
Labels: frontend

#3644 Enabled arbitrary mode in view only mode
  CHANGELOG.md
  frontend/javascripts/oxalis/view/action_bar_view.js
  frontend/javascripts/oxalis/view/layouting/default_layout_configs.js
  frontend/javascripts/oxalis/view/layouting/tracing_layout_view.js
Labels: frontend, frontend-easy

#3778 Refine publication view
  conf/application.conf
  frontend/javascripts/admin/api_flow_types.js
  frontend/javascripts/dashboard/advanced_dataset/advanced_dataset_view.js
  frontend/javascripts/dashboard/advanced_dataset/dataset_table.js
  frontend/javascripts/dashboard/dashboard_view.js
  frontend/javascripts/dashboard/dataset/dataset_import_view.js
  frontend/javascripts/dashboard/dataset_view.js
  frontend/javascripts/dashboard/publication_card.js
  frontend/javascripts/dashboard/publication_view.js
  frontend/javascripts/dashboard/spotlight_view.js
  frontend/javascripts/libs/format_utils.js
  frontend/javascripts/navbar.js
  frontend/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
  frontend/javascripts/router.js
  frontend/javascripts/test/backend-snapshot-tests/annotations.e2e.js
  frontend/javascripts/test/enzyme/snapshot.e2e.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/enzyme/snapshot.e2e.js.snap
  frontend/stylesheets/_dashboard.less
  frontend/stylesheets/antd_overwrites.less
  frontend/stylesheets/main.less
Labels: frontend

#3830 Make active node a bit smaller and remove active-node-animation
  frontend/javascripts/oxalis/geometries/materials/node_shader.js
  frontend/javascripts/oxalis/geometries/skeleton.js
Labels: frontend

#3822 Update error codes
  .circleci/slack-notification.sh
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Authentication.scala
  app/controllers/ConfigurationController.scala
  app/controllers/DataSetController.scala
  app/controllers/MeshController.scala
  app/controllers/ProjectController.scala
  app/controllers/ReportController.scala
  app/controllers/ScriptController.scala
  app/controllers/TaskController.scala
  app/controllers/TaskTypeController.scala
  app/controllers/TeamController.scala
  app/controllers/TimeController.scala
  app/controllers/UserController.scala
  app/controllers/WKDataStoreController.scala
  app/models/mesh/Mesh.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBClient.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: backend

#3837 default publication for development
  app/controllers/InitialDataController.scala
  app/models/binary/DataSetService.scala
  app/models/binary/Publication.scala
Labels: backend

#3847 Update screenshots to use the correct font
  frontend/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  frontend/javascripts/test/screenshots/2017-05-31_mSEM_scMS109_bk_100um_v01-aniso.png
  frontend/javascripts/test/screenshots/Cortex_knossos.png
  frontend/javascripts/test/screenshots/ROI2017_wkw.png
  frontend/javascripts/test/screenshots/ROI2017_wkw_fallback.png
  frontend/javascripts/test/screenshots/confocal-multi_knossos.png
  frontend/javascripts/test/screenshots/dsA_2.png
  frontend/javascripts/test/screenshots/e2006_knossos.png
  frontend/javascripts/test/screenshots/fluro-rgb_knossos.png
Labels: testing
