Repository scalableminds/webknossos, pull requests merged in 2020-10, with the labels that each got.

#4803 make decimal position input possible
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/action-bar/dataset_position_view.js
  frontend/javascripts/oxalis/view/components/input_component.js
Labels: frontend

#4846 Create organization folder lazily
  CHANGELOG.unreleased.md
  app/controllers/Authentication.scala
  conf/messages
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend, hacktoberfest-accepted

#4837 Drag'n'drop hybrid import
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/model/actions/volumetracing_actions.js
  frontend/javascripts/oxalis/model/reducers/volumetracing_reducer.js
  frontend/javascripts/oxalis/model/reducers/volumetracing_reducer_helpers.js
  frontend/javascripts/oxalis/model/sagas/save_saga.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/right-menu/trees_tab_view.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  frontend/javascripts/oxalis/view/version_entry.js
  package.json
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/UnsignedInteger.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeUpdateActions.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
  yarn.lock
Labels: backend, frontend

#4822 Continuous brush strokes
  CHANGELOG.unreleased.md
  frontend/javascripts/libs/drawing.js
  frontend/javascripts/oxalis/model/sagas/volumetracing_saga.js
  frontend/javascripts/oxalis/model/volumetracing/volumelayer.js
Labels: frontend

#4847 Find data for volumes
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataFinder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: backend, frontend, hacktoberfest-accepted

#4851 Skip reverted buckets
  CHANGELOG.unreleased.md
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingBucketHelper.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: backend

#4862 add admins and dataset managers to dataset access list
  CHANGELOG.unreleased.md
  app/controllers/DataSetController.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  frontend/javascripts/dashboard/advanced_dataset/dataset_access_list_view.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/projects.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/projects.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/scripts.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/scripts.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
Labels: backend, frontend

#4864 fix scala compiler warnings
  app/controllers/TaskController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/AgglomerateFileCache.scala
Labels: automerge, backend, refactoring

#4866 include creation info in task csv
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/task/task_create_form_view.js
Labels: automerge, frontend

#4867 word break in upload zone nml filename
  frontend/javascripts/oxalis/view/nml_upload_zone_container.js
Labels: automerge, frontend

#4869 Do not show toasts for bucket errors but notify airbrake instead
  frontend/javascripts/libs/request.js
  frontend/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.js
Labels: automerge

#4874 Ignore ResizeObserver error
  frontend/javascripts/libs/error_handling.js
Labels: automerge

#4870 Some smaller performance improvements
  frontend/javascripts/libs/mjs.js
  frontend/javascripts/oxalis/controller/camera_controller.js
  frontend/javascripts/oxalis/controller/scene_controller.js
  frontend/javascripts/oxalis/geometries/arbitrary_plane.js
  frontend/javascripts/oxalis/geometries/cube.js
  frontend/javascripts/oxalis/geometries/materials/plane_material_factory.js
  frontend/javascripts/oxalis/geometries/plane.js
  frontend/javascripts/oxalis/model/accessors/flycam_accessor.js
  frontend/javascripts/oxalis/model/bucket_data_handling/bucket.js
  frontend/javascripts/oxalis/model/bucket_data_handling/data_cube.js
  frontend/javascripts/oxalis/model/bucket_data_handling/pullqueue.js
  frontend/javascripts/oxalis/model/bucket_data_handling/texture_bucket_manager.js
  frontend/javascripts/oxalis/model/reducers/save_reducer.js
  frontend/javascripts/oxalis/view/layouting/layout_persistence.js
  frontend/javascripts/oxalis/view/right-menu/abstract_tree_tab_view.js
  frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js
  frontend/javascripts/oxalis/view/right-menu/trees_tab_view.js
  frontend/javascripts/oxalis/view/settings/user_settings_view.js
  frontend/javascripts/test/model/binary/layers/wkstore_adapter.spec.js
  frontend/javascripts/test/model/binary/pullqueue.spec.js
  frontend/javascripts/test/model/binary/temporal_bucket_manager.spec.js
  frontend/javascripts/test/model/texture_bucket_manager.spec.js
  package.json
  yarn.lock
Labels: automerge

#4872 Backend NML Parser: Performance Improvements
  CHANGELOG.unreleased.md
  app/models/annotation/nml/NmlParser.scala
  build.sbt
  conf/application.conf
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  tools/proxy/proxy.js
Labels: backend, performance

#4856 max-width for layers in dataset table
  frontend/javascripts/dashboard/advanced_dataset/dataset_table.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
Labels: automerge

#4860 resumable dataset upload
  CHANGELOG.unreleased.md
  app/WebKnossosModule.scala
  conf/messages
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/api_flow_types.js
  frontend/javascripts/admin/dataset/dataset_upload_view.js
  frontend/javascripts/messages.js
  package.json
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreModule.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/SampleDataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
  yarn.lock
Labels: backend, frontend

#4881 Don't crash in arbitrary *view* mode when invoking skeleton-shortcuts
  frontend/javascripts/oxalis/controller/viewmodes/arbitrary_controller.js
Labels: automerge

#4826 Call Long-Running Jobs from webKnossos
  app/WebKnossosModule.scala
  app/controllers/JobsController.scala
  app/utils/SQLHelpers.scala
  app/utils/WkConf.scala
  conf/application.conf
  conf/evolutions/056-add-jobs.sql
  conf/evolutions/reversions/056-add-jobs.sql
  conf/messages
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/api_flow_types.js
  frontend/javascripts/admin/dataset/dataset_add_boss_view.js
  frontend/javascripts/admin/dataset/dataset_add_neuroglancer_view.js
  frontend/javascripts/admin/dataset/dataset_add_view.js
  frontend/javascripts/admin/dataset/dataset_upload_view.js
  frontend/javascripts/admin/job/job_list_view.js
  frontend/javascripts/admin/onboarding.js
  frontend/javascripts/navbar.js
  frontend/javascripts/router.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  tools/postgres/schema.sql
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/SampleDataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
Labels: backend

#4896 Release 20.11
  CHANGELOG.released.md
  CHANGELOG.unreleased.md
  MIGRATIONS.released.md
Labels: automerge

#4897 Improve group expansion handling in the tree view
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
  frontend/javascripts/oxalis/view/right-menu/tree_hierarchy_view_helpers.js
Labels: automerge, frontend

#4898 Add measurement tools for trees in tree tab
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/api/api_latest.js
  frontend/javascripts/oxalis/view/right-menu/trees_tab_view.js
Labels: automerge

#4899 Fix unwanted group expansions
  frontend/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
Labels: automerge, bug

#4892 Organization restricted datastore
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/WKDataStoreController.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStore.scala
  conf/evolutions/058-add-onlyAllowedOrganization.sql
  conf/evolutions/reversions/058-add-onlyAllowedOrganization.sql
  conf/messages
  test/db/dataStores.csv
  tools/postgres/schema.sql
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
Labels: backend
