Repository scalableminds/webknossos, pull requests merged in 2020-01, with the labels that each got.

#4393 fix exit-codes for postgres-scripts
  tools/postgres/ensure_db.sh
  tools/postgres/ensure_schema.sh
Labels: automerge, infrastructure

#4395 bump fossildb version to 0.1.19
  docker-compose.yml
  fossildb/version
Labels: backend

#4397 update changelog and migration guide for 20.01.0 release
  CHANGELOG.md
  MIGRATIONS.md
Labels: automerge

#4389 better error message if no mag dir was found
  CHANGELOG.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataFormat.scala
Labels: backend

#4388 fix and refactor deactivating unreported datasets
  CHANGELOG.md
  app/controllers/WKDataStoreController.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
Labels: backend, bug, refactoring

#4381 Better default value for upper limit of intenstity range for uint16 layers
  CHANGELOG.md
  frontend/javascripts/dashboard/dataset/dataset_import_view.js
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
  frontend/javascripts/oxalis/model/reducers/settings_reducer.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  frontend/javascripts/oxalis/view/settings/histogram_view.js
Labels: bug

#4403 Fix deactivating datasets
  CHANGELOG.md
  app/controllers/WKDataStoreController.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  webknossos-datastore/conf/standalone-datastore.conf
  webknossos-tracingstore/conf/standalone-tracingstore.conf
Labels: backend

#4315 Finer Annotation visibility control
  CHANGELOG.md
  MIGRATIONS.md
  app/controllers/AnnotationController.scala
  app/controllers/LegacyApiController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationRestrictions.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/AnnotationVisibility.scala
  app/models/task/Task.scala
  conf/evolutions/050-add-annotation-visibility-enum.sql
  conf/evolutions/reversions/050-add-annotation-visibility-enum.sql
  conf/webknossos.versioned.routes
  docs/datasets.md
  docs/images/sharing_modal.png
  docs/images/sharing_modal_link.png
  docs/images/sharing_modal_team.png
  docs/images/sharing_modal_visibility.png
  docs/images/tracing_ui_sharing.png
  docs/rest_api.md
  docs/sharing.md
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/api_flow_types.js
  frontend/javascripts/dashboard/dataset/team_selection_component.js
  frontend/javascripts/oxalis/default_state.js
  frontend/javascripts/oxalis/model/actions/annotation_actions.js
  frontend/javascripts/oxalis/model/helpers/deep_update_test.js
  frontend/javascripts/oxalis/model/reducers/annotation_reducer.js
  frontend/javascripts/oxalis/model/reducers/reducer_helpers.js
  frontend/javascripts/oxalis/model/sagas/annotation_saga.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.js
  frontend/javascripts/pages/frontpage/pricing_view.js
  frontend/javascripts/router.js
  frontend/javascripts/test/backend-snapshot-tests/annotations.e2e.js
  frontend/javascripts/test/fixtures/skeletontracing_server_objects.js
  frontend/javascripts/test/fixtures/tasktracing_server_objects.js
  frontend/javascripts/test/fixtures/volumetracing_server_objects.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  test/db/annotations.csv
  tools/postgres/schema.sql
Labels: backend, frontend

#4409 fix share modal for private annotations
  CHANGELOG.md
  app/controllers/AnnotationController.scala
  app/models/annotation/Annotation.scala
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.js
Labels: bug, frontend

#4382 Add option to invert the color value
  CHANGELOG.md
  frontend/javascripts/dashboard/dataset/dataset_import_view.js
  frontend/javascripts/libs/datasource.schema.json
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/geometries/materials/plane_material_factory.js
  frontend/javascripts/oxalis/model/reducers/settings_reducer.js
  frontend/javascripts/oxalis/shaders/main_data_fragment.glsl.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  frontend/javascripts/oxalis/view/settings/setting_input_views.js
  frontend/javascripts/test/puppeteer/dataset_rendering.screenshot.js
  frontend/stylesheets/_general.less
Labels: enhancement, frontend

#4411 Fix shared teams error for read only tracings
  CHANGELOG.md
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.js
Labels: frontend

#4404 Task creation can use task id
  CHANGELOG.md
  app/controllers/TaskController.scala
  conf/messages
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/task/task_create_form_view.js
Labels: backend, frontend

#4416 Fix renaming of annotations in tracing view
  CHANGELOG.md
  frontend/javascripts/oxalis/view/components/editable_text_label.js
Labels: automerge, frontend
