Repository scalableminds/webknossos, pull requests merged in 2020-12, with the labels that each got.

#4933 Refactor Task Creation in Backend
  app/controllers/AnnotationIOController.scala
  app/controllers/Controller.scala
  app/controllers/TaskController.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/nml/NmlResults.scala
  app/models/annotation/nml/NmlService.scala
  app/models/task/CompletionStatus.scala
  app/models/task/Task.scala
  app/models/task/TaskCreationParameters.scala
  app/models/task/TaskCreationResult.scala
  app/models/task/TaskCreationService.scala
  app/models/task/TaskService.scala
  app/models/task/TaskType.scala
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
  util/src/main/scala/com/scalableminds/util/tools/JsonHelper.scala
Labels: automerge, backend, refactoring

#4962 Persist the selected overwrite-mode for hybrids and volume tracings
  CHANGELOG.unreleased.md
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/default_state.js
  frontend/javascripts/oxalis/model/actions/volumetracing_actions.js
  frontend/javascripts/oxalis/model/reducers/volumetracing_reducer.js
  frontend/javascripts/oxalis/model/reducers/volumetracing_reducer_helpers.js
  frontend/javascripts/oxalis/model/sagas/volumetracing_saga.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/action-bar/volume_actions_view.js
  frontend/javascripts/test/sagas/volumetracing_saga.spec.js
  frontend/javascripts/types/schemas/user_settings.schema.js
Labels: automerge

#4965 Fix stack overflow in comments tab for trees with many comments
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
Labels: automerge

#4959 Treat zero layer dataset as unusable
  CHANGELOG.unreleased.md
  app/models/binary/DataSet.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
Labels: backend

#4982 Allow Parsing NML Nodes Without Radius Attribute
  CHANGELOG.unreleased.md
  app/models/annotation/nml/NmlParser.scala
  conf/application.conf
  frontend/javascripts/oxalis/default_state.js
  frontend/javascripts/oxalis/model/helpers/nml_helpers.js
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/test/reducers/skeletontracing_reducer.spec.js
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/SkeletonElementDefaults.scala
Labels: automerge, backend

#4977 Fix single file uploads
  CHANGELOG.unreleased.md
  util/src/main/scala/com/scalableminds/util/io/PathUtils.scala
  util/src/main/scala/com/scalableminds/util/io/ZipIO.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
Labels: backend

#5002 Remove note on bulk task format change
  frontend/javascripts/messages.js
Labels: frontend, low-hanging-fruit
