Repository scalableminds/webknossos, pull requests merged in 2020-04, with the labels that each got.

#4513 Update react sortable tree to maybe resolve rendering bug
  package.json
  yarn.lock
Labels: bug, frontend

#4517 Longer, and bash-style retries for smoke tests in CI
  .circleci/config.yml
Labels: testing

#4515 Replace brain.png with brain.svg
  frontend/javascripts/components/brain_spinner.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  public/images/brain.png
  public/images/brain.svg
  public/images/brain_hd.png
  public/images/brain_hd.svg
Labels: automerge

#4516 Reload all layers when render missing data black is changed
  CHANGELOG.md
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  frontend/javascripts/oxalis/view/settings/setting_input_views.js
Labels: enhancement, frontend

#4510 Add option to hide unmapped segments in segmentation tab
  CHANGELOG.md
  frontend/javascripts/oxalis/model/actions/settings_actions.js
  frontend/javascripts/oxalis/model/reducers/settings_reducer.js
  frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js
  frontend/javascripts/oxalis/view/settings/merger_mode_modal_view.js
Labels: frontend, new feature

#4521 Readd brain_hd.svg which is used on the features page of wk demo
  frontend/javascripts/pages/frontpage/features_view.js
  public/images/brain_white.svg
Labels: automerge

#4520 Update 20.04.0 release
  CHANGELOG.md
Labels: automerge

#4532 Make mappings field in datasource optional
  CHANGELOG.md
  app/models/binary/DataSet.scala
  frontend/javascripts/libs/datasource.schema.json
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/MappingProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceImporter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/FallbackLayerAdapter.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingLayer.scala
Labels: backend

#4537 Move generic view route all the way down to avoid url mismatches
  frontend/javascripts/router.js
Labels: bug, frontend

#4534 Backup old datasource-properties upon change
  CHANGELOG.md
  frontend/javascripts/router.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
Labels: backend

#4531 Enable hdf5 mapping in isosurface computation
  CHANGELOG.md
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/oxalis/model/data_layer.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/DataRequests.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/IsosurfaceService.scala
Labels: automerge, backend

#4545 Fix segmentation opacity in recommended tasktype
  CHANGELOG.md
  frontend/javascripts/admin/tasktype/recommended_configuration_view.js
  frontend/javascripts/libs/user_settings.schema.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/geometries/plane.js
  frontend/javascripts/oxalis/model/sagas/task_saga.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/new_task_description_modal.js
Labels: automerge

#4542 Fix group sorting when there are no trees
  CHANGELOG.md
  frontend/javascripts/oxalis/view/right-menu/tree_hierarchy_view_helpers.js
Labels: automerge, bug

#4557 Dataset info tab: break long dataset names
  frontend/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
Labels: frontend

#4556 fix shader compilation error and invisible color layers in certain circumstances
  CHANGELOG.md
  frontend/javascripts/oxalis/geometries/materials/plane_material_factory.js
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
Labels: automerge

#4559 Fix registration for setups with one organization
  CHANGELOG.md
  MIGRATIONS.md
  conf/application.conf
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/api_flow_types.js
  frontend/javascripts/admin/auth/registration_form.js
  frontend/javascripts/admin/auth/registration_view.js
  frontend/javascripts/admin/onboarding.js
  frontend/javascripts/pages/frontpage/pricing_view.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/teams.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/teams.e2e.js.snap
Labels: automerge

#4563 allow creating tree groups even for single nml upload
  CHANGELOG.md
  app/models/annotation/nml/NmlService.scala
Labels: backend

#4568 Refine wording in task creation report view
  frontend/javascripts/admin/task/task_create_form_view.js
Labels: automerge, frontend

#4574 show seconds in timeline view tooltip
  frontend/javascripts/admin/time/time_line_view.js
Labels: frontend

#4575 redirect / to dashboard when logged-in and on demo
  frontend/javascripts/router.js
Labels: automerge

#4580 Use Client Timestamp for info/finish timetracking
  CHANGELOG.unreleased.md
  app/controllers/AnnotationController.scala
  app/controllers/LegacyApiController.scala
  app/models/user/time/TimeSpanService.scala
  conf/webknossos.latest.routes
  conf/webknossos.versioned.routes
  docs/rest_api.md
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/test/helpers/apiHelpers.js
  frontend/javascripts/test/model/model.spec.js
Labels: automerge, backend

#4584 Fix histogram if data is missing
  CHANGELOG.unreleased.md
  conf/messages
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala
Labels: automerge, backend

#4571 Ensure that accessed data is always non-negative in shader
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/shaders/texture_access.glsl.js
Labels: automerge

#4544 Warn if outside of bounding box
  CHANGELOG.unreleased.md
  frontend/javascripts/libs/error_handling.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/controller/td_controller.js
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
  frontend/javascripts/oxalis/view/action-bar/dataset_position_view.js
Labels: automerge, bug, enhancement, frontend

#4543 Add sharing modal for view mode
  CHANGELOG.unreleased.md
  flow-typed/npm/react-redux_v7.x.x.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.js
  frontend/javascripts/oxalis/view/action-bar/share_view_dataset_modal_view.js
  frontend/javascripts/oxalis/view/action-bar/view_dataset_actions_view.js
  frontend/javascripts/oxalis/view/action_bar_view.js
  package.json
  yarn.lock
Labels: enhancement, frontend
