Repository scalableminds/webknossos, pull requests merged in 2020-02, with the labels that each got.

#4412 Redo - Higher histogramm range uint16
  CHANGELOG.md
  frontend/javascripts/dashboard/dataset/dataset_import_view.js
  frontend/javascripts/oxalis/default_state.js
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
  frontend/javascripts/oxalis/model/actions/settings_actions.js
  frontend/javascripts/oxalis/model/reducers/settings_reducer.js
  frontend/javascripts/oxalis/model/sagas/load_histogram_data_saga.js
  frontend/javascripts/oxalis/model/sagas/root_saga.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  frontend/javascripts/oxalis/view/settings/histogram_view.js
  frontend/javascripts/test/helpers/apiHelpers.js
Labels: discussion, frontend

#4428 Move evolution 50 to release 20.02 in MIGRATIONS.md
  MIGRATIONS.md
Labels: automerge

#4430 Remove wkconnect from default docker-compose setup
  README.md
  docker-compose.yml
  start-docker.sh
Labels: automerge

#4413 Make navbar scrollable and add info that fallback layer is excluded
  CHANGELOG.md
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/project/project_list_view.js
  frontend/javascripts/admin/task/task_annotation_view.js
  frontend/javascripts/admin/task/task_list_view.js
  frontend/javascripts/admin/tasktype/task_type_list_view.js
  frontend/javascripts/dashboard/dashboard_task_list_view.js
  frontend/javascripts/dashboard/explorative_annotations_view.js
  frontend/javascripts/messages.js
  frontend/javascripts/navbar.js
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  frontend/javascripts/oxalis/view/action_bar_view.js
  frontend/javascripts/oxalis/view/version_list.js
Labels: enhancement, frontend

#4435 Remove invariant that a tree is always needed
  flow-typed/npm/antd_vx.x.x.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/model/actions/skeletontracing_actions.js
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
  frontend/javascripts/oxalis/model/sagas/save_saga.js
  frontend/javascripts/oxalis/model/sagas/skeletontracing_saga.js
  frontend/javascripts/oxalis/view/right-menu/trees_tab_view.js
  frontend/javascripts/test/geometries/skeleton.spec.js
  frontend/javascripts/test/reducers/skeletontracing_reducer.spec.js
  frontend/javascripts/test/sagas/skeletontracing_saga.spec.js
Labels: automerge, refactoring

#4440 Fix screenshot test
  frontend/javascripts/test/screenshots/float_test_dataset.png
Labels: automerge

#4424 Best-effort rendering when GPU does not support full dataset
  CHANGELOG.md
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/default_state.js
  frontend/javascripts/oxalis/geometries/materials/plane_material_factory.js
  frontend/javascripts/oxalis/model.js
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
  frontend/javascripts/oxalis/model/actions/settings_actions.js
  frontend/javascripts/oxalis/model/bucket_data_handling/data_rendering_logic.js
  frontend/javascripts/oxalis/model/reducers/settings_reducer.js
  frontend/javascripts/oxalis/model/sagas/dataset_saga.js
  frontend/javascripts/oxalis/model/sagas/root_saga.js
  frontend/javascripts/oxalis/model_initialization.js
  frontend/javascripts/oxalis/shaders/main_data_fragment.glsl.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  frontend/javascripts/test/model/binary/data_rendering_logic.spec.js
Labels: automerge

#4445 Make TimeSpanService EagerSingleton
  CHANGELOG.md
  app/WebKnossosModule.scala
Labels: automerge, backend, bug

#4446 Easier docker-based server installation
  CHANGELOG.md
  README.md
  docker-compose.yml
  docs/getting_started.md
  docs/hello.md
  docs/index.md
  docs/installation.md
  tools/hosting/docker-compose.yml
Labels: automerge

#4447 Remove the 'move-around' instruction in the data-reloading notification
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
Labels: automerge

#4451 Fix default intensity for uint24 layers
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
Labels: automerge

#4450 Docs on symlinks
  docs/datasets.md
Labels: automerge

#4456 update changelog and migration guide for release 20.03.0
  CHANGELOG.md
  MIGRATIONS.md
Labels: automerge

#4415 Undo finish task
  CHANGELOG.md
  app/controllers/AnnotationController.scala
  app/models/annotation/AnnotationService.scala
  app/utils/WkConf.scala
  conf/application.conf
  conf/messages
  frontend/javascripts/admin/api_flow_types.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.js
  frontend/javascripts/test/backend-snapshot-tests/annotations.e2e.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
Labels: backend, frontend
