Repository scalableminds/webknossos, pull requests merged in 2020-03, with the labels that each got.

#4421 Try importing every file as nml and protobuf before failing
  CHANGELOG.md
  frontend/javascripts/dashboard/advanced_dataset/dataset_action_view.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
  frontend/javascripts/oxalis/model_initialization.js
  frontend/javascripts/oxalis/view/right-menu/trees_tab_view.js
Labels: bug, enhancement, frontend

#4433 Disable node creation with right mouse when brushing
  CHANGELOG.md
  frontend/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  frontend/javascripts/oxalis/controller/scene_controller.js
  frontend/javascripts/oxalis/geometries/crosshair.js
Labels: bug, frontend

#4466 Disallow editing description of someone else’s annotation
  CHANGELOG.md
  app/controllers/AnnotationController.scala
  frontend/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
Labels: automerge, backend, frontend

#4464 Reduce default dataset reporting interval from 10 to 1 minute
  CHANGELOG.md
  MIGRATIONS.md
  conf/application.conf
  webknossos-datastore/conf/standalone-datastore.conf
Labels: automerge

#4467 Avoid volume mode in hybrid tracings
  CHANGELOG.md
  frontend/javascripts/admin/auth/login_form.js
  frontend/javascripts/components/brain_spinner.js
  frontend/javascripts/oxalis/controller.js
  frontend/javascripts/oxalis/model_initialization.js
  frontend/stylesheets/main.less
Labels: bug, frontend

#4476 Clearer error message if histogram call fails
  conf/messages
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala
Labels: automerge, backend

#4482 Update Public URIs on Startup from Config
  CHANGELOG.md
  app/controllers/InitialDataController.scala
  app/models/annotation/TracingStore.scala
  clean
Labels: backend

#4357 Set default view configuration in datasource properties json
  CHANGELOG.md
  MIGRATIONS.md
  app/controllers/ConfigurationController.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/configuration/DataSetConfiguration.scala
  conf/evolutions/051-add-source-view-configuration.sql
  conf/evolutions/reversions/049-annotation-listed-teams.sql
  conf/evolutions/reversions/051-add-source-view-configuration.sql
  frontend/javascripts/admin/api_flow_types.js
  frontend/javascripts/admin/tasktype/recommended_configuration_view.js
  frontend/javascripts/dashboard/dataset/dataset_import_view.js
  frontend/javascripts/dashboard/dataset/default_config_component.js
  frontend/javascripts/libs/datasource.schema.json
  frontend/javascripts/libs/user_settings.schema.js
  frontend/javascripts/oxalis/api/api_latest.js
  frontend/javascripts/oxalis/controller.js
  frontend/javascripts/oxalis/controller/scene_controller.js
  frontend/javascripts/oxalis/default_state.js
  frontend/javascripts/oxalis/geometries/materials/plane_material_factory.js
  frontend/javascripts/oxalis/merger_mode.js
  frontend/javascripts/oxalis/model.js
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
  frontend/javascripts/oxalis/model/bucket_data_handling/layer_rendering_manager.js
  frontend/javascripts/oxalis/model/reducers/settings_reducer.js
  frontend/javascripts/oxalis/model/sagas/annotation_saga.js
  frontend/javascripts/oxalis/model/sagas/dataset_saga.js
  frontend/javascripts/oxalis/model/sagas/prefetch_saga.js
  frontend/javascripts/oxalis/model/sagas/volumetracing_saga.js
  frontend/javascripts/oxalis/shaders/main_data_fragment.glsl.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  frontend/javascripts/test/puppeteer/dataset_rendering.screenshot.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  test/db/dataSet_layers.csv
  test/db/dataSets.csv
  tools/postgres/schema.sql
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosDataFormat.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataFormat.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataSource.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/InboxDataSource.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceImporter.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/FallbackLayerAdapter.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingLayer.scala
Labels: automerge, backend, frontend

#4470 Also load up to three fallback layers for 'best quality first'
  CHANGELOG.md
  frontend/javascripts/oxalis/model/bucket_data_handling/loading_strategy_logic.js
  frontend/javascripts/test/model/flycam_accessors.spec.js
Labels: automerge, frontend

#4437 Check if task team is allowed for dataset
  CHANGELOG.md
  app/models/annotation/Annotation.scala
  app/models/task/Task.scala
Labels: backend

#4487 Revert "Check if task team is allowed for dataset"
  CHANGELOG.md
  app/models/annotation/Annotation.scala
  app/models/task/Task.scala
Labels: automerge

#4465 Allow Overwriting Missing Datasets From Different Datastore
  CHANGELOG.md
  app/models/binary/DataSetService.scala
Labels: automerge, backend

#4493 Update changelog and migration guide for release 20.04.0
  CHANGELOG.md
  MIGRATIONS.md
Labels: automerge

#4494 Update screenshot in screenshot test
  frontend/javascripts/test/screenshots/ROI2017_wkw_fallback.png
Labels: automerge

#4480 Fix displayed segment
  CHANGELOG.md
  frontend/javascripts/oxalis/model/bucket_data_handling/data_cube.js
  frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js
Labels: bug, frontend

#4496 Revert "Fix task dataset check "
  app/models/annotation/Annotation.scala
  app/models/task/Task.scala
Labels: automerge, backend

#4497 Fix import of new datasets
  CHANGELOG.md
  frontend/javascripts/dashboard/dataset/dataset_import_view.js
Labels: automerge

#4489 Enable wrap-in-group option when importing single NML
  CHANGELOG.md
  frontend/javascripts/oxalis/view/nml_upload_zone_container.js
Labels: automerge, frontend

#4500 Add extensive logging for finish calls, allow double finish requests
  app/controllers/AnnotationController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationRestrictions.scala
  app/models/annotation/AnnotationService.scala
  app/models/user/User.scala
  app/oxalis/security/URLSharing.scala
  util/src/main/scala/com/scalableminds/util/accesscontext/AccessContext.scala
Labels: automerge, backend

#4504 Anonymize Request Error Logging
  app/oxalis/security/UserAwareRequestLogging.scala
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
Labels: backend, bug

#4495 Undo finish via API
  CHANGELOG.md
  frontend/javascripts/oxalis/api/api_latest.js
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.js
Labels: automerge, frontend

#4501 Check wK write permission before organization creation
  CHANGELOG.md
  app/controllers/Authentication.scala
  conf/messages
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend

#4505 Remove compile warning
  app/controllers/LegacyApiController.scala
Labels: automerge, backend, refactoring

#4507 Allow floats as rotation parameters
  CHANGELOG.md
  frontend/javascripts/libs/vector_input.js
  frontend/javascripts/oxalis/view/action-bar/dataset_position_view.js
Labels: frontend

#4506 no modal for empty tree-group deletion
  CHANGELOG.md
  frontend/javascripts/oxalis/view/right-menu/trees_tab_view.js
Labels: frontend

#4473 Increase performance of comments tab
  CHANGELOG.md
  frontend/javascripts/oxalis/geometries/cube.js
  frontend/javascripts/oxalis/model/helpers/nml_helpers.js
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
  frontend/javascripts/oxalis/view/right-menu/comment_tab/comment.js
  frontend/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
Labels: automerge, enhancement, frontend, performance

#4491 Add task configurations download as csv
  CHANGELOG.md
  frontend/javascripts/admin/task/task_create_form_view.js
  frontend/javascripts/admin/task/task_list_view.js
  frontend/javascripts/admin/task/task_search_form.js
  frontend/javascripts/messages.js
Labels: enhancement, frontend
