Repository scalableminds/webknossos, pull requests merged in 2020-09, with the labels that each got.

#4778 UI improvement for 2D data
  CHANGELOG.released.md
  frontend/javascripts/oxalis/controller/viewmodes/plane_controller.js
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
  frontend/javascripts/oxalis/view/layouting/default_layout_configs.js
  frontend/javascripts/oxalis/view/layouting/layout_persistence.js
  frontend/javascripts/oxalis/view/layouting/tracing_layout_view.js
Labels: enhancement, frontend

#4804 add debug output in case of lz4 decompression exception
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingBucketHelper.scala
Labels: automerge, backend

#4805 do not try to decompress reverted buckets
  CHANGELOG.unreleased.md
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingBucketHelper.scala
Labels: automerge, backend, bug

#4784 Shortcuts for navigating to next/prev node
  CHANGELOG.unreleased.md
  docs/keyboard_shortcuts.md
  frontend/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  frontend/javascripts/oxalis/model/accessors/skeletontracing_accessor.js
  frontend/javascripts/oxalis/model/actions/skeletontracing_actions.js
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  frontend/javascripts/oxalis/store.js
Labels: frontend, new feature

#4815 Fix tooltip glitch
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/components/editable_text_label.js
Labels: bug

#4780 Add fill tool
  CHANGELOG.unreleased.md
  docs/keyboard_shortcuts.md
  frontend/javascripts/libs/utils.js
  frontend/javascripts/oxalis/controller/combinations/volumetracing_plane_controller.js
  frontend/javascripts/oxalis/model/actions/volumetracing_actions.js
  frontend/javascripts/oxalis/model/bucket_data_handling/bucket.js
  frontend/javascripts/oxalis/model/bucket_data_handling/data_cube.js
  frontend/javascripts/oxalis/model/sagas/root_saga.js
  frontend/javascripts/oxalis/model/sagas/volumetracing_saga.js
  frontend/javascripts/oxalis/model/volumetracing/volumelayer.js
Labels: frontend, new feature

#4816 Fix empty tree list and some tree list errors
  CHANGELOG.unreleased.md
  frontend/javascripts/libs/error_handling.js
  frontend/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
  package.json
  yarn.lock
Labels: automerge, bug

#4802 Histogram float range shows decimal places
  frontend/javascripts/oxalis/view/settings/histogram_view.js
Labels: frontend

#4827 Avoid the word »hybrid« in task type creation view
  frontend/javascripts/admin/tasktype/task_type_create_view.js
Labels: automerge, frontend, hybrid

#4828 specifies initial selected dataset in publication tile
  frontend/javascripts/dashboard/publication_card.js
Labels: automerge

#4567 isosurfaces for volume tracings
  .prettierrc
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/libs/ThreeDMap.js
  frontend/javascripts/oxalis/api/api_latest.js
  frontend/javascripts/oxalis/controller/combinations/segmentation_plane_controller.js
  frontend/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  frontend/javascripts/oxalis/controller/combinations/volumetracing_plane_controller.js
  frontend/javascripts/oxalis/controller/scene_controller.js
  frontend/javascripts/oxalis/controller/viewmodes/plane_controller.js
  frontend/javascripts/oxalis/default_state.js
  frontend/javascripts/oxalis/model/actions/annotation_actions.js
  frontend/javascripts/oxalis/model/reducers/ui_reducer.js
  frontend/javascripts/oxalis/model/sagas/effect-generators.js.flow
  frontend/javascripts/oxalis/model/sagas/isosurface_saga.js
  frontend/javascripts/oxalis/model/sagas/volumetracing_saga.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/settings/dataset_settings_view.js
  frontend/javascripts/oxalis/view/td_view_controls.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreModule.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/DataRequests.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/requests/DataServiceRequests.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/IsosurfaceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/IsosurfaceServiceHolder.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: automerge, backend, frontend, new feature

#4723 Pass through nml errors in task creation
  CHANGELOG.unreleased.md
  app/controllers/TaskController.scala
Labels: automerge, backend

#4830 Drop overlaps when saving timespans
  CHANGELOG.released.md
  app/models/user/time/TimeSpanService.scala
Labels: automerge, backend, bug

#4832 Release 20.10
  CHANGELOG.released.md
  CHANGELOG.unreleased.md
  MIGRATIONS.released.md
Labels: automerge

#4834 filter nan values when generating histogram
  CHANGELOG.unreleased.md
  app/models/user/time/TimeSpanService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataConverter.scala
Labels: backend, bug
