Repository scalableminds/webknossos, pull requests merged in 2021-01, with the labels that each got.

#4993 Address Unused Warnings
  app/controllers/AnnotationIOController.scala
  app/controllers/Application.scala
  app/controllers/Authentication.scala
  app/controllers/Controller.scala
  app/controllers/DataSetController.scala
  app/controllers/JobsController.scala
  app/controllers/MaintenanceController.scala
  app/controllers/OrganizationController.scala
  app/controllers/ReportController.scala
  app/controllers/SitemapController.scala
  app/controllers/TimeController.scala
  app/controllers/UserTokenController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/nml/NmlService.scala
  app/models/binary/DataStoreRpcClient.scala
  app/models/task/Script.scala
  app/models/task/Task.scala
  app/models/task/TaskCreationService.scala
  app/models/task/TaskType.scala
  app/oxalis/mail/DefaultMails.scala
  app/oxalis/security/CombinedAuthenticatorService.scala
  app/oxalis/security/UserAwareRequestLogging.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  util/src/main/scala/com/scalableminds/util/io/ZipIO.scala
  util/src/main/scala/com/scalableminds/util/mvc/ExtendedController.scala
  util/src/main/scala/com/scalableminds/util/mvc/Filter.scala
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
  util/src/main/scala/com/scalableminds/util/tools/Math.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Application.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Controller.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/StandaloneDatastore.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosDataFormat.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWBucketStreamSink.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/InboxDataSource.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AccessTokenService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceImporter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/MappingParser.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreConfig.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreWkRpcClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/StandaloneTracingstore.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/MergedVolume.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeDataZipHelper.scala
Labels: backend, refactoring

#5003 Upgrade Saxophone XML Parser to 0.7.1
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/helpers/nml_helpers.js
  package.json
  webpack.config.js
  yarn.lock
Labels: frontend

#5016 Improve hint in version view
  frontend/javascripts/oxalis/view/version_entry.js
Labels: automerge

#5010 Ensure that bucket picker respect RAM-limit for buckets
  frontend/javascripts/oxalis/constants.js
  frontend/javascripts/oxalis/model/bucket_data_handling/data_cube.js
  frontend/javascripts/oxalis/model/bucket_data_handling/data_rendering_logic.js
  frontend/javascripts/test/model/binary/cube.spec.js
Labels: automerge

#5030 Fix that agglomerate skeleton button was clickable in view or read-only mode
  frontend/javascripts/oxalis/view/right-menu/mapping_info_view.js
Labels: bug

#5035 change debug logging to info for agglomerate skeleton perf
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AgglomerateService.scala
Labels: automerge, backend

#5031 More bucket batching
  frontend/javascripts/oxalis/model/bucket_data_handling/pullqueue.js
Labels: automerge

#5017 Disable brush in mags higher than mag8
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/accessors/volumetracing_accessor.js
  frontend/javascripts/oxalis/model/reducers/volumetracing_reducer_helpers.js
  frontend/javascripts/oxalis/model/sagas/root_saga.js
  frontend/javascripts/oxalis/model/sagas/volumetracing_saga.js
  frontend/javascripts/oxalis/view/action-bar/volume_actions_view.js
Labels: automerge

#5047 Allow handling dataset configurations for datasets not normally visible
  CHANGELOG.unreleased.md
  app/controllers/ConfigurationController.scala
  app/models/configuration/DataSetConfigurationService.scala
  app/models/user/UserService.scala
Labels: backend, bug

#4999 cleanup erroneous uploads
  CHANGELOG.unreleased.md
  app/controllers/WKDataStoreController.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  conf/webknossos.latest.routes
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/DataSetDeleter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceRepository.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataStoreWkRpcClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
Labels: backend

#4950 Add context menu for nodes
  CHANGELOG.unreleased.md
  docs/images/context_menu.png
  docs/skeleton_annotation.md
  frontend/javascripts/libs/mjs.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/api/api_latest.js
  frontend/javascripts/oxalis/controller.js
  frontend/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  frontend/javascripts/oxalis/controller/viewmodes/plane_controller.js
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
  frontend/javascripts/oxalis/view/action-bar/volume_actions_view.js
  frontend/javascripts/oxalis/view/layouting/tracing_layout_view.js
  frontend/javascripts/oxalis/view/node_context_menu.js
  frontend/javascripts/oxalis/view/right-menu/tree_hierarchy_view.js
  frontend/stylesheets/trace_view/_tracing_view.less
Labels: automerge, frontend, new feature

#5048 Remove es6-promise and whatwg-fetch polyfill
  frontend/javascripts/main.js
  package.json
  yarn.lock
Labels: automerge

#5006 Suppress Warnings in Generated Files
  build.sbt
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataSource.scala
Labels: automerge, backend, refactoring

#5012 Address Unused Warnings
  app/controllers/AnnotationIOController.scala
  app/controllers/Application.scala
  app/controllers/Authentication.scala
  app/controllers/Controller.scala
  app/controllers/DataSetController.scala
  app/controllers/JobsController.scala
  app/controllers/MaintenanceController.scala
  app/controllers/OrganizationController.scala
  app/controllers/ReportController.scala
  app/controllers/SitemapController.scala
  app/controllers/TimeController.scala
  app/controllers/UserTokenController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/nml/NmlService.scala
  app/models/binary/DataStoreRpcClient.scala
  app/models/task/Script.scala
  app/models/task/Task.scala
  app/models/task/TaskCreationService.scala
  app/models/task/TaskType.scala
  app/oxalis/mail/DefaultMails.scala
  app/oxalis/security/CombinedAuthenticatorService.scala
  app/oxalis/security/UserAwareRequestLogging.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  util/src/main/scala/com/scalableminds/util/io/ZipIO.scala
  util/src/main/scala/com/scalableminds/util/mvc/ExtendedController.scala
  util/src/main/scala/com/scalableminds/util/mvc/Filter.scala
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
  util/src/main/scala/com/scalableminds/util/tools/Math.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Application.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Controller.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/StandaloneDatastore.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosDataFormat.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWBucketStreamSink.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/InboxDataSource.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AccessTokenService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceImporter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/MappingParser.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreConfig.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreWkRpcClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/StandaloneTracingstore.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/MergedVolume.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeDataZipHelper.scala
Labels: automerge, backend, refactoring

#4944 Improve Dataset Settings to not adapt suggestion automatically
  CHANGELOG.unreleased.md
  frontend/javascripts/dashboard/dataset/dataset_cache_provider.js
  frontend/javascripts/dashboard/dataset/dataset_import_view.js
  frontend/javascripts/dashboard/dataset/simple_advanced_data_form.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/model_initialization.js
  frontend/javascripts/test/model/flycam_accessors.spec.js
  frontend/javascripts/types/api_flow_types.js
  frontend/javascripts/types/schemas/datasource.schema.js
  frontend/javascripts/types/schemas/datasource.schema.json
  frontend/javascripts/types/schemas/datasource.types.js
  frontend/javascripts/types/validation.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/InboxDataSource.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
Labels: automerge, enhancement, frontend

#5050 Disable fill tool for higher mags
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/accessors/volumetracing_accessor.js
  frontend/javascripts/oxalis/view/action-bar/volume_actions_view.js
Labels: automerge, bug, frontend

#5055 Disable parallel dataset upload requests for now
  frontend/javascripts/admin/admin_rest_api.js
Labels: automerge, bug, urgent

#5073 Run snapshot tests without concurrency for deterministic ordering
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/projects.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/projects.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/scripts.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/scripts.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/teams.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/teams.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/timetracking.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/timetracking.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.snap
  test/e2e/End2EndSpec.scala
  tools/test.sh
Labels: backend, infrastructure, testing

#5064 Repair Unused DBAccessContexts
  app/Startup.scala
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Authentication.scala
  app/controllers/DataSetController.scala
  app/controllers/InitialDataController.scala
  app/controllers/OrganizationController.scala
  app/controllers/ProjectController.scala
  app/controllers/ReportController.scala
  app/controllers/ScriptController.scala
  app/controllers/StatisticsController.scala
  app/controllers/TaskTypeController.scala
  app/controllers/TeamController.scala
  app/controllers/UserTokenController.scala
  app/controllers/WKDataStoreController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/TracingStore.scala
  app/models/annotation/handler/AnnotationInformationHandler.scala
  app/models/annotation/handler/ProjectInformationHandler.scala
  app/models/annotation/handler/SavedTracingInformationHandler.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStore.scala
  app/models/configuration/DataSetConfigurationService.scala
  app/models/mesh/Mesh.scala
  app/models/project/Project.scala
  app/models/task/Script.scala
  app/models/task/Task.scala
  app/models/task/TaskType.scala
  app/models/team/Organization.scala
  app/models/team/Team.scala
  app/models/user/Invite.scala
  app/models/user/MultiUser.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  app/models/user/time/TimeSpan.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/security/BearerTokenAuthenticatorRepository.scala
  app/oxalis/security/CombinedAuthenticatorService.scala
  app/oxalis/security/Token.scala
  app/oxalis/security/URLSharing.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  app/utils/SQLHelpers.scala
  util/src/main/scala/com/scalableminds/util/io/PathUtils.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreModule.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AgglomerateService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend, refactoring, security

#5070 Disallow deactivating oneself
  CHANGELOG.unreleased.md
  app/controllers/UserController.scala
  conf/messages
  frontend/javascripts/test/backend-snapshot-tests/users.e2e.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/projects.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/projects.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/scripts.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/scripts.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/teams.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/teams.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/timetracking.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/timetracking.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.snap
  test/e2e/End2EndSpec.scala
  tools/test.sh
Labels: backend

#5084 Allow remote origin for GET api/datasets/
  app/controllers/DataSetController.scala
Labels: automerge, backend

#5086 Fix permission for listing public datasets
  app/controllers/DataSetController.scala
Labels: backend, bug

#5092 Add userinfos SQL view for easier debugging
  MIGRATIONS.unreleased.md
  conf/evolutions/061-userinfos-view.sql
  conf/evolutions/reversions/061-userinfos-view.sql
  tools/postgres/schema.sql
Labels: backend

#5098 Ensure thumbnails for public datasets are accessible
  app/controllers/DataSetController.scala
Labels: automerge, backend, bug

#5095 Fix nightly
  frontend/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  frontend/javascripts/test/screenshots/2017-05-31_mSEM_scMS109_bk_100um_v01-aniso.png
  frontend/javascripts/test/screenshots/Cortex_knossos.png
  frontend/javascripts/test/screenshots/ROI2017_wkw.png
  frontend/javascripts/test/screenshots/ROI2017_wkw_fallback.png
  frontend/javascripts/test/screenshots/confocal-multi_knossos.png
  frontend/javascripts/test/screenshots/dsA_2.png
  frontend/javascripts/test/screenshots/e2006_knossos.png
  frontend/javascripts/test/screenshots/float_test_dataset.png
  frontend/javascripts/test/screenshots/fluro-rgb_knossos.png
Labels: automerge

#5091 Add separate `register` route
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/auth/authentication_modal.js
  frontend/javascripts/admin/auth/login_form.js
  frontend/javascripts/admin/auth/registration_view.js
  frontend/javascripts/admin/auth/spotlight_registration_form.js
  frontend/javascripts/dashboard/spotlight_view.js
  frontend/javascripts/router.js
  package.json
Labels: automerge

#5102 Make isosurfaces more robust
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/reducers/annotation_reducer.js
  frontend/javascripts/oxalis/model/sagas/isosurface_saga.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/right-menu/meshes_view.js
Labels: automerge

#5107 Make settings background white again
  frontend/stylesheets/antd_overwrites.less
Labels: automerge
