Repository scalableminds/webknossos, pull requests merged in 2021-11, with the labels that each got.

#5797 Fix that data was not rendered when zoomed in too much
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/accessors/flycam_accessor.js
  frontend/javascripts/oxalis/model/bucket_data_handling/bucket_picker_strategies/orthogonal_bucket_picker.js
  frontend/javascripts/oxalis/model/bucket_data_handling/prefetch_strategy_plane.js
Labels: bug, automerge

#5751 Update installation instructions for ubuntu 20.04
  README.md
Labels: documentation

#5824 Correctly propagate project tracing time as Long instead of Int
  CHANGELOG.unreleased.md
  app/controllers/ProjectController.scala
  app/models/project/Project.scala
  app/models/task/Task.scala
Labels: bug, backend

#5767 Add bounding box tool
  CHANGELOG.unreleased.md
  frontend/javascripts/libs/window.js
  frontend/javascripts/oxalis/constants.js
  frontend/javascripts/oxalis/controller/combinations/bounding_box_handlers.js
  frontend/javascripts/oxalis/controller/combinations/move_handlers.js
  frontend/javascripts/oxalis/controller/combinations/skeleton_handlers.js
  frontend/javascripts/oxalis/controller/combinations/tool_controls.js
  frontend/javascripts/oxalis/controller/scene_controller.js
  frontend/javascripts/oxalis/controller/viewmodes/plane_controller.js
  frontend/javascripts/oxalis/geometries/cube.js
  frontend/javascripts/oxalis/model/accessors/tool_accessor.js
  frontend/javascripts/oxalis/model/accessors/tracing_accessor.js
  frontend/javascripts/oxalis/model/accessors/view_mode_accessor.js
  frontend/javascripts/oxalis/model/actions/annotation_actions.js
  frontend/javascripts/oxalis/model/actions/skeletontracing_actions.js
  frontend/javascripts/oxalis/model/actions/ui_actions.js
  frontend/javascripts/oxalis/model/actions/volumetracing_actions.js
  frontend/javascripts/oxalis/model/reducers/annotation_reducer.js
  frontend/javascripts/oxalis/model/reducers/reducer_helpers.js
  frontend/javascripts/oxalis/model/reducers/ui_reducer.js
  frontend/javascripts/oxalis/model/sagas/annotation_tool_saga.js
  frontend/javascripts/oxalis/model/sagas/root_saga.js
  frontend/javascripts/oxalis/model/sagas/save_saga.js
  frontend/javascripts/oxalis/model/sagas/volumetracing_saga.js
  frontend/javascripts/oxalis/model_initialization.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/action-bar/toolbar_view.js
  frontend/javascripts/oxalis/view/components/setting_input_views.js
  frontend/javascripts/oxalis/view/context_menu.js
  frontend/javascripts/oxalis/view/layouting/tracing_layout_view.js
  frontend/javascripts/oxalis/view/right-border-tabs/bounding_box_tab.js
  frontend/javascripts/oxalis/view/version_entry.js
  frontend/javascripts/test/fixtures/volumetracing_object.js
  frontend/javascripts/test/reducers/volumetracing_reducer.spec.js
  frontend/javascripts/test/sagas/annotation_tool_saga.spec.js
  frontend/javascripts/test/sagas/volumetracing_saga_integration.spec.js
  package.json
  public/images/bounding-box.svg
  public/images/new-bounding-box.svg
  yarn.lock
Labels: frontend, new feature

#5848 Admins can share annotations with all teams of organization
  CHANGELOG.unreleased.md
  app/controllers/AnnotationController.scala
  conf/messages
Labels: bug, backend

#5843 move /srv/webknossos to /webknossos in the dockerfiles
  CHANGELOG.unreleased.md
  Dockerfile
  MIGRATIONS.unreleased.md
  docker-compose.yml
  docs/datasets.md
  tools/binary_data/download_knossos_data.py
  tools/binary_data/generate_voronoi_cubes.py
  tools/binary_data/grabData.sh
  tools/binary_data/knossos_to_wkw.py
  tools/binary_data/segmentation-deploy.sh
  tools/dev_deployment/refresh_schema.sh
  tools/hosting/docker-compose.yml
  webknossos-datastore/Dockerfile
  webknossos-datastore/deployment/docker-compose.yml
  webknossos-tracingstore/Dockerfile
  webknossos-tracingstore/deployment/docker-compose.yml
Labels: automerge

#5853 Fix initial min/max values of a histogram of a color layer
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/sagas/load_histogram_data_saga.js
Labels: bug, frontend

#5860 Send Slack notification if bucket loading requests are too slow
  MIGRATIONS.unreleased.md
  app/oxalis/telemetry/SlackNotificationService.scala
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreConfig.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/slacknotification/DSSlackNotificationService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/slacknotification/SlackClient.scala
  webknossos-datastore/conf/standalone-datastore.conf
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreConfig.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreModule.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/SkeletonTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/TracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/slacknotification/TSSlackNotificationService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingDataStore.scala
Labels: backend

#5834 Rework for webknossos-worker as client-only
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/WebKnossosModule.scala
  app/controllers/InitialDataController.scala
  app/controllers/JobsController.scala
  app/controllers/WKRemoteWorkerController.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStore.scala
  app/models/job/Job.scala
  app/models/job/JobManualState.scala
  app/models/job/JobState.scala
  app/models/job/JobStatus.scala
  app/models/job/Worker.scala
  app/oxalis/telemetry/SlackNotificationService.scala
  app/utils/SQLHelpers.scala
  app/utils/WkConf.scala
  conf/application.conf
  conf/evolutions/077-workers.sql
  conf/evolutions/reversions/077-workers.sql
  conf/messages
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/dataset/dataset_upload_view.js
  package.json
  test/db/dataStores.csv
  tools/postgres/schema.sql
  tools/postgres/set_jobs.sh
  tools/postgres/toggle_jobs.sh
  util/src/main/scala/com/scalableminds/util/mvc/Formatter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/IntervalScheduler.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/slacknotification/SlackClient.scala
Labels: backend, jobs

#5868 Do not use datastore actor system in WorkerLivenessService
  app/models/job/Worker.scala
Labels: bug, backend

#5871 Fix datastore selection when starting convert-to-wkw jobs
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/dataset/dataset_add_boss_view.js
  frontend/javascripts/admin/dataset/dataset_add_neuroglancer_view.js
  frontend/javascripts/admin/dataset/dataset_components.js
  frontend/javascripts/admin/dataset/dataset_upload_view.js
Labels: bug
