Repository scalableminds/webknossos, pull requests merged in 2021-05, with the labels that each got.

#5208 Clean up config
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/Startup.scala
  app/controllers/Application.scala
  app/controllers/AuthenticationController.scala
  app/controllers/InitialDataController.scala
  app/controllers/JobsController.scala
  app/controllers/OrganizationController.scala
  app/models/binary/DataSetService.scala
  app/models/task/TaskService.scala
  app/models/user/Invite.scala
  app/models/user/UserCache.scala
  app/models/user/UserService.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/telemetry/SlackNotificationService.scala
  app/oxalis/thirdparty/BrainTracing.scala
  app/utils/StoreModules.scala
  app/utils/WkConf.scala
  app/views/main.scala.html
  conf/application.conf
  util/src/main/scala/com/scalableminds/util/mail/Mailer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreConfig.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AgglomerateService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataServiceHolder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataStoreWkRpcClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/MappingService.scala
  webknossos-datastore/conf/standalone-datastore.conf
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreConfig.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/slacknotification/SlackClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/slacknotification/SlackNotificationService.scala
  webknossos-tracingstore/conf/standalone-tracingstore.conf
Labels: backend, infrastructure, refactoring

#5449 Increase initialTeams timeout from 5m to 1h
  app/controllers/WKDataStoreController.scala
  app/models/binary/DataSetService.scala
  conf/messages
Labels: backend

#5426 Register new demo instance users with mailchimp
  app/Startup.scala
  app/controllers/AuthenticationController.scala
  app/models/user/Invite.scala
  app/models/user/UserService.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/mail/DefaultMails.scala
  app/oxalis/mail/Mail.scala
  app/oxalis/mail/MailchimpClient.scala
  app/oxalis/mail/Mailer.scala
  app/utils/WkConf.scala
  app/views/mail/newAdminWKOrg.scala.html
  app/views/mail/newUserWKOrg.scala.html
  conf/application.conf
  util/src/main/scala/com/scalableminds/util/security/SCrypt.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
Labels: backend

#5457 Fix two bugs related to transferring task instances
  CHANGELOG.unreleased.md
  app/models/task/Task.scala
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/project/transfer_all_tasks_modal.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
Labels: backend, bug, frontend

#5462 Link to Dataset Settings from Viewer
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/right-menu/dataset_info_tab_view.js
  frontend/stylesheets/main.less
Labels: frontend

#5464 Fix screenshot tests
  frontend/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  frontend/javascripts/test/screenshots/2017-05-31_mSEM_scMS109_bk_100um_v01-aniso.png
  frontend/javascripts/test/screenshots/Multi-Channel-Test.png
  frontend/javascripts/test/screenshots/ROI2017_wkw.png
  frontend/javascripts/test/screenshots/ROI2017_wkw_fallback.png
  frontend/javascripts/test/screenshots/ROI2017_wkw_with_mapping_astrocyte.png
  frontend/javascripts/test/screenshots/dsA_2.png
  frontend/javascripts/test/screenshots/float_test_dataset.png
Labels: automerge, testing

#5456 Log durations for health checks
  app/controllers/Application.scala
  app/oxalis/security/UserAwareRequestLogging.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/Application.scala
Labels: backend

#5458 Fix histogram sampling for tiny datasets
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala
Labels: backend, bug

#5483 Multi-NML Upload: allow for only some to have Orga Attribute
  CHANGELOG.unreleased.md
  app/controllers/AnnotationIOController.scala
Labels: backend, bug

#5484 Relabel too-high tree ids in backend
  CHANGELOG.unreleased.md
  app/models/annotation/TracingStoreRpcClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/SkeletonTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/SkeletonTracingService.scala
Labels: backend, bug

#5485 Pass token to wkw conversion job
  app/controllers/JobsController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/BucketProvider.scala
Labels: backend, jobs

#5487 Use bbox topleft instead of 0,0,0 in histogram position sampling
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/FindDataService.scala
Labels: backend

#5488 Include superuser hint in slack job notifications
  app/controllers/JobsController.scala
Labels: backend

#5494 Pass through URL Params in Proxy
  app/controllers/DemoProxyController.scala
Labels: backend

#5461 Highlight active tree and active node in comment tab
  frontend/javascripts/oxalis/view/right-menu/comment_tab/comment.js
  frontend/javascripts/oxalis/view/right-menu/comment_tab/comment_tab_view.js
  frontend/javascripts/oxalis/view/right-menu/comment_tab/tree_with_comments.js
  frontend/stylesheets/react_sortable_tree_overwrites.less
  frontend/stylesheets/trace_view/_right_menu.less
Labels: frontend

#5502 Adapt local docker-compose service to new config format
  docker-compose.yml
Labels: bug, infrastructure

#5345 Load precomputed meshes
  CHANGELOG.unreleased.md
  conf/messages
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/oxalis/controller/combinations/segmentation_plane_controller.js
  frontend/javascripts/oxalis/controller/scene_controller.js
  frontend/javascripts/oxalis/default_state.js
  frontend/javascripts/oxalis/model/actions/annotation_actions.js
  frontend/javascripts/oxalis/model/actions/flycam_actions.js
  frontend/javascripts/oxalis/model/actions/segmentation_actions.js
  frontend/javascripts/oxalis/model/reducers/annotation_reducer.js
  frontend/javascripts/oxalis/model/sagas/handle_mesh_changes.js
  frontend/javascripts/oxalis/model/sagas/isosurface_saga.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/node_context_menu.js
  frontend/javascripts/oxalis/view/right-menu/meshes_view.js
  frontend/javascripts/oxalis/view/right-menu/meshes_view_helper.js
  frontend/stylesheets/trace_view/_tracing_view.less
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/MeshFileService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/MeshFileCache.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend, frontend, new feature

#5490 Improve error message & more frontend analytics
  frontend/javascripts/admin/dataset/dataset_upload_view.js
  frontend/javascripts/dashboard/advanced_dataset/dataset_action_view.js
  frontend/javascripts/dashboard/dataset/dataset_import_view.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/controller.js
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.js
  frontend/javascripts/oxalis/view/layouting/default_layout_configs.js
  frontend/javascripts/oxalis/view/layouting/flex_layout_wrapper.js
Labels: automerge, bug, frontend

#5512 Update backend protobuf dependency
  build.sbt
  project/Dependencies.scala
  project/DependencyResolvers.scala
  project/plugins.sbt
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Controller.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/TracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingMigrationService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/UpdateActions.scala
Labels: backend, dependencies, security

#5505 Add tags to mailchimp for some user interactions
  app/controllers/AnnotationController.scala
  app/controllers/AuthenticationController.scala
  app/controllers/DataSetController.scala
  app/controllers/WKDataStoreController.scala
  app/oxalis/mail/MailchimpClient.scala
  app/oxalis/mail/MailchimpTag.scala
Labels: backend

#5507 Schedule fetching job status updates
  app/controllers/JobsController.scala
  app/models/user/UserService.scala
Labels: backend

#5510 Add jobs/worker status route
  app/WebKnossosModule.scala
  app/controllers/JobsController.scala
  app/models/job/Job.scala
  conf/webknossos.latest.routes
Labels: backend, infrastructure, new feature, refactoring

#5513 Increase threshold for slow request slack notifications from 5 to 10s
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
Labels: backend

#5528 Fix needsConversion detection in dataset upload
  frontend/javascripts/admin/dataset/dataset_upload_view.js
Labels: bug, frontend, urgent
