Repository scalableminds/webknossos, pull requests merged in 2021-09, with the labels that each got.

#5693 Create openAPI schema for parts of the REST API using Swagger
  CHANGELOG.unreleased.md
  app/RequestHandler.scala
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Application.scala
  app/controllers/Controller.scala
  app/controllers/DataSetController.scala
  app/controllers/DataStoreController.scala
  app/controllers/OrganizationController.scala
  conf/application.conf
  conf/routes
  project/Dependencies.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
Labels: backend, infrastructure

#5710 Add shortcuts K and L for toggling sidebars
  CHANGELOG.unreleased.md
  docs/keyboard_shortcuts.md
  frontend/javascripts/oxalis/view/components/border_toggle_button.js
  frontend/javascripts/oxalis/view/layouting/flex_layout_wrapper.js
Labels: frontend, low-hanging-fruit

#5718 Fix volume version restore for untouched buckets
  CHANGELOG.unreleased.md
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBClient.scala
Labels: bug, backend

#5721 Fix isMappingEnabled api method
  frontend/javascripts/oxalis/api/api_latest.js
Labels: bug

#5716 minor Swagger Schema updates
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/DataSetController.scala
  app/controllers/DataStoreController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
Labels: automerge

#5724 Fix unsafe integer usage by using string keys instead
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/geometries/skeleton.js
Labels: bug, automerge

#5743 Fix CI
  frontend/javascripts/admin/time/time_line_view.js
Labels: automerge

#5744 add links to top-level doc files
  docs/CHANGELOG.released.md
  docs/MIGRATIONS.released.md
  docs/code-readme.md
Labels: automerge
