Repository scalableminds/webknossos, pull requests merged in 2021-02, with the labels that each got.

#5097 Store Uploader ID with Dataset
  MIGRATIONS.unreleased.md
  app/controllers/WKDataStoreController.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  conf/evolutions/062-dataset-uploader.sql
  conf/evolutions/reversions/062-dataset-uploader.sql
  conf/messages
  test/db/dataSets.csv
  tools/postgres/schema.sql
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataStoreWkRpcClient.scala
Labels: automerge, backend

#5051 Fewer error messages in view mode
  frontend/javascripts/oxalis/model/sagas/save_saga.js
  frontend/javascripts/oxalis/model/sagas/settings_saga.js
  frontend/javascripts/test/sagas/save_saga.spec.js
Labels: automerge, frontend

#5115 Fix project usersWithActiveTasks query
  CHANGELOG.unreleased.md
  app/models/project/Project.scala
Labels: automerge, backend, bug

#5110 Add novelUserExperienceinfos field to multiUser
  app/controllers/UserController.scala
  app/models/user/MultiUser.scala
  app/models/user/UserService.scala
  conf/evolutions/063-novelUserExperienceinfos.sql
  conf/evolutions/reversions/063-novelUserExperienceinfos.sql
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.snap
  test/db/multiusers.csv
  tools/postgres/schema.sql
Labels: backend

#5119 Fix nightly
  frontend/javascripts/test/puppeteer/dataset_rendering.screenshot.js
  frontend/javascripts/test/screenshots/ROI2017_wkw_with_mapping_astrocyte.png
  frontend/javascripts/test/screenshots/ROI2017_wkw_with_mapping_axons.png
Labels: automerge

#5083 Proxy some URIs for Demo Instance
  app/RequestHandler.scala
  app/controllers/DemoProxyController.scala
  app/utils/WkConf.scala
  conf/application.conf
  frontend/javascripts/navbar.js
  frontend/javascripts/router.js
  util/src/main/scala/com/scalableminds/util/tools/ConfigReader.scala
Labels: backend, new feature

#5085 Drop support for Knossos cubes
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  README.md
  docs/data_formats.md
  docs/datasets.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Controller.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/Cube.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosDataFormat.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/knossos/KnossosDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataFormat.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataFormatHelper.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/IntervalScheduler.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/DataRequests.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/ImageThumbnail.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/requests/DataServiceRequests.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataStoreWkRpcClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/IsosurfaceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/CumsumParser.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/DataCubeCache.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/TemporaryStore.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/FallbackLayerAdapter.scala
Labels: backend

#5126 Hotfix release 21.02.1
  CHANGELOG.released.md
  MIGRATIONS.released.md
Labels: automerge

#5131 Adapt nightly to dropping knossos-support
  frontend/javascripts/test/puppeteer/dataset_rendering.screenshot.js
  frontend/javascripts/test/screenshots/Cortex_knossos.png
  frontend/javascripts/test/screenshots/Multi-Channel-Test.png
  frontend/javascripts/test/screenshots/confocal-multi_knossos.png
  frontend/javascripts/test/screenshots/e2006_knossos.png
  frontend/javascripts/test/screenshots/fluro-rgb_knossos.png
Labels: automerge

#5139 Nicer email sender names
  conf/application.conf
Labels: automerge

#5123 Fix Lookup for Initial Datastore
  app/controllers/InitialDataController.scala
  app/models/annotation/TracingStore.scala
  app/models/binary/DataStore.scala
Labels: automerge, backend

#5124 Ignore Carriage Return When Diffing Schemas
  tools/postgres/diff_schema.js
Labels: automerge, backend, bug, infrastructure

#5121 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: automerge

#5099 Implement new "welcome header"
  MIGRATIONS.unreleased.md
  app/controllers/UserController.scala
  app/models/user/MultiUser.scala
  app/models/user/UserService.scala
  conf/application.conf
  conf/evolutions/063-novelUserExperienceinfos.sql
  conf/evolutions/reversions/063-novelUserExperienceinfos.sql
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/auth/registration_view.js
  frontend/javascripts/admin/onboarding.js
  frontend/javascripts/admin/welcome_ui.js
  frontend/javascripts/dashboard/dashboard_task_list_view.js
  frontend/javascripts/dashboard/dashboard_view.js
  frontend/javascripts/dashboard/dataset_view.js
  frontend/javascripts/dashboard/explorative_annotations_view.js
  frontend/javascripts/dashboard/publication_view.js
  frontend/javascripts/dashboard/shared_annotations_view.js
  frontend/javascripts/dashboard/spotlight_view.js
  frontend/javascripts/features.js
  frontend/javascripts/libs/utils.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/view/layouting/tracing_layout_view.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.snap
  frontend/javascripts/types/api_flow_types.js
  frontend/stylesheets/_dashboard.less
  frontend/stylesheets/main.less
  test/db/multiusers.csv
  tools/postgres/schema.sql
Labels: automerge

#5141 adds contact link
  frontend/javascripts/navbar.js
Labels: automerge

#5143 Email templates
  app/oxalis/mail/DefaultMails.scala
  app/utils/WkConf.scala
  app/views/mail/emailBaseTemplate.scala.html
  app/views/mail/newAdminWKOrg.scala.html
  app/views/mail/newUser.scala.html
  app/views/mail/newUserWKOrg.scala.html
  app/views/mail/validateUser.scala.html
Labels: automerge

#5112 Re center option
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/tasktype/recommended_configuration_view.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/api/api_latest.js
  frontend/javascripts/oxalis/controller/combinations/skeletontracing_plane_controller.js
  frontend/javascripts/oxalis/default_state.js
  frontend/javascripts/oxalis/store.js
  frontend/javascripts/oxalis/view/settings/user_settings_view.js
  frontend/javascripts/types/schemas/user_settings.schema.js
Labels: frontend

#5154 Update sample_datasets_modal.js
  frontend/javascripts/dashboard/dataset/sample_datasets_modal.js
Labels: automerge

#5142 Avoid more null-errors in isosurface and mesh handling
  .flowconfig
  CHANGELOG.unreleased.md
  frontend/javascripts/libs/error_handling.js
  frontend/javascripts/oxalis/model/sagas/handle_mesh_changes.js
  frontend/javascripts/oxalis/model/sagas/isosurface_saga.js
  frontend/javascripts/oxalis/model/sagas/root_saga.js
  frontend/javascripts/oxalis/view/right-menu/meshes_view.js
Labels: automerge

#5152 Fix multiuser email lookup
  CHANGELOG.unreleased.md
  app/controllers/UserController.scala
  app/models/user/MultiUser.scala
Labels: automerge, backend, bug

#5149 Separate Experience Domains By Organization
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/InitialDataController.scala
  app/controllers/TaskController.scala
  app/models/task/Task.scala
  app/models/task/TaskCreationService.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  conf/evolutions/064-experienceDomains-per-orga.sql
  conf/evolutions/reversions/064-experienceDomains-per-orga.sql
  tools/postgres/schema.sql
Labels: backend, security

#5151 Allow Superusers to Join Organizations Unlisted
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/InitialDataController.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  conf/evolutions/065-unlisted-superusers.sql
  conf/evolutions/reversions/065-unlisted-superusers.sql
  test/db/users.csv
  tools/postgres/schema.sql
Labels: automerge, backend

#5162 add help block
  frontend/javascripts/admin/dataset/dataset_upload_view.js
Labels: enhancement, frontend

#5164 Allow accessing dataset admin view configuration via sharing token
  CHANGELOG.unreleased.md
  app/controllers/ConfigurationController.scala
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/oxalis/model_initialization.js
Labels: automerge, backend, bug

#5167 Indicate loading state in tab title during loading
  frontend/javascripts/oxalis/view/layouting/tracing_layout_view.js
Labels: UX

#5081 Improve upload UI
  CHANGELOG.unreleased.md
  flow-typed/npm/antd_vx.x.x.js
  frontend/javascripts/admin/dataset/dataset_add_view.js
  frontend/javascripts/admin/dataset/dataset_components.js
  frontend/javascripts/admin/dataset/dataset_upload_view.js
  frontend/javascripts/admin/onboarding.js
  frontend/javascripts/dashboard/dataset/team_selection_component.js
  frontend/javascripts/libs/utils.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/view/right-menu/trees_tab_view.js
  frontend/stylesheets/_general.less
  package.json
  public/images/folder.svg
  yarn.lock
Labels: enhancement, frontend

#5174 Increase Standalone Stores Request Timeout
  CHANGELOG.unreleased.md
  webknossos-datastore/conf/standalone-datastore.conf
  webknossos-tracingstore/conf/standalone-tracingstore.conf
Labels: backend

#5156 Send Analytics Events in Backend
  CHANGELOG.unreleased.md
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/Authentication.scala
  app/controllers/DataSetController.scala
  app/controllers/JobsController.scala
  app/controllers/WKDataStoreController.scala
  app/controllers/WKTracingStoreController.scala
  app/models/analytics/AnalyticsService.scala
  app/utils/WkConf.scala
  conf/application.conf
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/oxalis/model/sagas/effect-generators.js.flow
  frontend/javascripts/oxalis/model/sagas/isosurface_saga.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/DataRequests.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataStoreWkRpcClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreWkRpcClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
Labels: backend, new feature

#5193 Fix public annotation sharing
  app/controllers/AnnotationController.scala
Labels: automerge, backend, bug, urgent

#5194 Fix Dataset Tiff Conversion
  frontend/javascripts/admin/dataset/dataset_upload_view.js
Labels: bug, frontend

#5200 Reload page when the next task is loaded which has a different script
  CHANGELOG.unreleased.md
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/api/api_latest.js
Labels: automerge

#5196 Add snapshot test: public annotations viewable while logged out
  frontend/javascripts/test/backend-snapshot-tests/annotations.e2e.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  test/db/annotations.csv
Labels: backend, testing

#5198 Fix “merging” a single volume annotation
  CHANGELOG.unreleased.md
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/SkeletonTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: backend, bug

#5207 add proxy uris to sitemap.xml
  app/RequestHandler.scala
  app/controllers/SitemapController.scala
  app/utils/SitemapWriter.scala
Labels: backend, enhancement

#5216 in datasets table, make _publication a foreign key
  MIGRATIONS.released.md
  MIGRATIONS.unreleased.md
  conf/evolutions/065-unlisted-superusers.sql
  conf/evolutions/066-publications-foreign-key.sql
  conf/evolutions/reversions/066-publications-foreign-key.sql
  tools/postgres/schema.sql
Labels: backend
