Repository scalableminds/webknossos, pull requests merged in 2021-12, with the labels that each got.

#5874 adds swagger.json to all routes files
  conf/noDS.noTS.routes
  conf/noDS.routes
  conf/noTS.routes
Labels: automerge

#5832 Add tags for datasets
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/DataSetController.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  conf/evolutions/079-add-dataset-tags.sql
  conf/evolutions/reversions/079-add-dataset-tags.sql
  frontend/javascripts/dashboard/advanced_dataset/dataset_action_view.js
  frontend/javascripts/dashboard/advanced_dataset/dataset_table.js
  frontend/javascripts/dashboard/dataset/dataset_cache_provider.js
  frontend/javascripts/dashboard/dataset_view.js
  frontend/javascripts/dashboard/explorative_annotations_view.js
  frontend/javascripts/oxalis/default_state.js
  frontend/javascripts/oxalis/view/components/categorization_label.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  frontend/javascripts/types/api_flow_types.js
  test/db/dataSets.csv
  tools/postgres/schema.sql
Labels: backend, frontend

#5889 Fix dataset upload for >2GB files
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
Labels: bug, backend

#5831 Uploads survive backend restarts
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/WKRemoteDataStoreController.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  conf/application.conf
  conf/webknossos.latest.routes
  docker-compose.yml
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/dataset/dataset_upload_view.js
  project/Dependencies.scala
  tools/hosting/docker-compose.yml
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreConfig.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Application.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/SampleDataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/DataStoreRedisStore.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/RedisTemporaryStore.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
  webknossos-datastore/conf/standalone-datastore.conf
  webknossos-datastore/deployment/config/datastore-docker.conf
  webknossos-datastore/deployment/docker-compose.yml
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreRedisStore.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/Application.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/SkeletonTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: backend

#5893 Fix tree group ids when splitting unconnected tree in NML upload
  CHANGELOG.unreleased.md
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/MultiComponentTreeSplitter.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/TreeUtils.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/TreeValidator.scala
Labels: bug, backend

#5886 Refactor and unify restrictions handling in skeletontracing reducer
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.js
Labels: automerge

#5890 Make access token check explicit in data/tracing stores
  app/controllers/UserTokenController.scala
  app/controllers/WKRemoteDataStoreController.scala
  app/controllers/WKRemoteTracingStoreController.scala
  app/controllers/WKRemoteWorkerController.scala
  app/models/annotation/TracingStore.scala
  app/models/binary/DataStore.scala
  conf/webknossos.latest.routes
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AccessTokenService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/SkeletonTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/TracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: backend, infrastructure, refactoring

#5863 In dataset upload, enable symlinking layers of existing datasets
  CHANGELOG.unreleased.md
  app/controllers/WKRemoteDataStoreController.scala
  conf/messages
  frontend/javascripts/admin/dataset/dataset_upload_view.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/SampleDataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
Labels: backend, new feature

#5900 Swagger: fix nickname for datasetReserveUpload
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
Labels: automerge

#5901 Swagger: annotate body of dataset upload reserve/finish
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
Labels: automerge

#5904 Fix job run error message for foreign organization
  app/controllers/JobsController.scala
Labels: backend

#5913 Upgrade to log4j 2.17.0
  project/Dependencies.scala
Labels: automerge
