Repository scalableminds/webknossos, pull requests merged in 2022-09, with the labels that each got.

#6440 Remove wrongly-typed field from Mailchimp tag response
  app/oxalis/mail/MailchimpClient.scala
Labels: bug, backend

#6441 Remove some more return statements from scala code
  app/models/job/Job.scala
  app/oxalis/mail/MailchimpClient.scala
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
Labels: backend, refactoring

#6442 extensive error logging for mailchimp tagging
  app/oxalis/mail/MailchimpTicker.scala
Labels: backend

#6444 Skip fetching lastActivity for multiusers with zero active users
  app/oxalis/mail/MailchimpTicker.scala
Labels: backend

#6431 Make Annotation Zarr Endponits Compatible With Standard WK Auth
  app/controllers/AnnotationPrivateLinkController.scala
  app/controllers/AuthenticationController.scala
  app/controllers/UserTokenController.scala
  app/controllers/WKRemoteDataStoreController.scala
  app/models/annotation/AnnotationService.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  conf/webknossos.latest.routes
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/OmeNgffHeader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/annotation/AnnotationSource.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteTracingstoreClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
Labels: enhancement, backend

#6445 In e2e tests, disable datastore filesystem watcher
  docker-compose.yml
Labels: backend, testing

#6447 Use toMagLiteral convenience function for ZarrMag path default
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrDataLayers.scala
Labels: backend, refactoring

#6361 Min-Cut on Agglomerate Graph
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/oxalis/model/actions/skeletontracing_actions.tsx
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer_helpers.ts
  frontend/javascripts/oxalis/model/sagas/proofread_saga.ts
  frontend/javascripts/oxalis/view/context_menu.tsx
  package.json
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: backend, new feature

#6446 Fix duplicate route for Editable Mapping annotations
  CHANGELOG.unreleased.md
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: enhancement, backend, proofreading

#6453 Link to dataset view mode from settings page
  frontend/javascripts/dashboard/dataset/dataset_settings_view.tsx
Labels: frontend

#6452 Add placeholder text when task search table is empty
  frontend/javascripts/admin/task/task_list_view.tsx
  frontend/javascripts/dashboard/dashboard_task_list_view.tsx
Labels: enhancement, frontend

#6458 Fix isosurface loading for volume annotations with mappings
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/StandaloneDatastore.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataServiceHolder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/IsosurfaceService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/StandaloneTracingstore.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: bug, backend

#6433 Fix clip histogram button if ideal mag does not exist
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/api/api_latest.ts
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.ts
  frontend/javascripts/oxalis/model/sagas/clip_histogram_saga.ts
Labels: bug, frontend

#6472 Avoid int overflows for agglomerate tree id
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AgglomerateService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
Labels: bug, backend

#6473 Omit wk token in buildinfo
  app/controllers/Application.scala
Labels: backend, security

#6471 WIP: Docs for Proofreading tool
  DEV_INSTALL.md
  README.md
  docs/data_formats.md
  docs/datasets.md
  docs/export.md
  docs/images/download_dialog.gif
  docs/images/zarr_links.jpeg
  docs/jobs.md
  docs/proof_reading.md
  docs/sharing.md
  docs/skeleton_annotation.md
  docs/terminology.md
  docs/tooling.md
  docs/volume_annotation.md
Labels: documentation

#6461 Short links
  .circleci/slack-notification.sh
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/ShortLinkController.scala
  app/models/shortlinks/ShortLink.scala
  conf/evolutions/088-shortlinks.sql
  conf/evolutions/reversions/088-shortlinks.sql
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/components/redirect.tsx
  frontend/javascripts/libs/error_handling.ts
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/share_view_dataset_modal_view.tsx
  frontend/javascripts/router.tsx
  frontend/javascripts/types/api_flow_types.ts
  tools/postgres/schema.sql
Labels: backend

#6475 Skip building datastore jar in CI
  .circleci/config.yml
  app/controllers/Application.scala
Labels: backend, CI

#6476 In CI, Assert no Warnings From Scala Compiler
  .circleci/config.yml
  build.sbt
Labels: backend, CI

#6478 Some cleanup in annotation sql queries
  app/controllers/AnnotationController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/AnnotationType.scala
  app/models/task/TaskService.scala
  app/utils/SQLHelpers.scala
Labels: backend, refactoring

#6416 Voxelytics routes
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/WebKnossosModule.scala
  app/controllers/VoxelyticsController.scala
  app/models/voxelytics/ElasticsearchClient.scala
  app/models/voxelytics/VoxelyticsDAO.scala
  app/models/voxelytics/VoxelyticsLogLevel.scala
  app/models/voxelytics/VoxelyticsRunState.scala
  app/models/voxelytics/VoxelyticsService.scala
  app/models/voxelytics/WorkflowDescription.scala
  app/models/voxelytics/WorkflowEvents.scala
  app/utils/SQLHelpers.scala
  app/utils/WkConf.scala
  conf/application.conf
  conf/evolutions/089-voxelytics.sql
  conf/evolutions/reversions/089-voxelytics.sql
  conf/messages
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/voxelytics/artifacts_view.tsx
  frontend/javascripts/admin/voxelytics/dag_view.tsx
  frontend/javascripts/admin/voxelytics/log_tab.tsx
  frontend/javascripts/admin/voxelytics/statistics_tab.tsx
  frontend/javascripts/admin/voxelytics/task_list_view.tsx
  frontend/javascripts/admin/voxelytics/task_view.tsx
  frontend/javascripts/admin/voxelytics/workflow_list_view.tsx
  frontend/javascripts/admin/voxelytics/workflow_view.tsx
  frontend/javascripts/libs/format_utils.ts
  frontend/javascripts/libs/react_hooks.ts
  frontend/javascripts/navbar.tsx
  frontend/javascripts/router.tsx
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  frontend/javascripts/types/api_flow_types.ts
  frontend/stylesheets/dark.less
  frontend/stylesheets/main.less
  frontend/stylesheets/react_ansi_overwrites.less
  package.json
  project/Dependencies.scala
  tools/postgres/schema.sql
  tsconfig.json
  util/src/main/scala/com/scalableminds/util/mvc/ExtendedController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
  yarn.lock
Labels: backend, new feature, automerge

#6489 update snapshots after voxelyticsEnabled changed
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
Labels: automerge

#6414 Make Largest Segment ID Optional
  CHANGELOG.unreleased.md
  app/controllers/AnnotationIOController.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/nml/NmlParser.scala
  app/models/annotation/nml/NmlVolumeTag.scala
  app/models/annotation/nml/NmlWriter.scala
  app/models/binary/DataSet.scala
  app/models/binary/ExploreRemoteLayerService.scala
  conf/messages
  docs/datasets.md
  docs/volume_annotation.md
  frontend/javascripts/admin/dataset/dataset_add_zarr_view.tsx
  frontend/javascripts/admin/welcome_ui.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx
  frontend/javascripts/libs/render_independently.ts
  frontend/javascripts/libs/render_independently.tsx
  frontend/javascripts/libs/utils.ts
  frontend/javascripts/oxalis/controller/viewmodes/plane_controller.tsx
  frontend/javascripts/oxalis/model/accessors/volumetracing_accessor.ts
  frontend/javascripts/oxalis/model/actions/skeletontracing_actions.tsx
  frontend/javascripts/oxalis/model/actions/volumetracing_actions.ts
  frontend/javascripts/oxalis/model/reducers/volumetracing_reducer.ts
  frontend/javascripts/oxalis/model/reducers/volumetracing_reducer_helpers.ts
  frontend/javascripts/oxalis/model/sagas/mapping_saga.ts
  frontend/javascripts/oxalis/model/sagas/task_saga.tsx
  frontend/javascripts/oxalis/model/sagas/update_actions.ts
  frontend/javascripts/oxalis/model/sagas/volumetracing_saga.tsx
  frontend/javascripts/oxalis/store.ts
  frontend/javascripts/oxalis/view/action-bar/toolbar_view.tsx
  frontend/javascripts/oxalis/view/largest_segment_id_modal.tsx
  frontend/javascripts/oxalis/view/new_task_description_modal.tsx
  frontend/javascripts/oxalis/view/remove_tree_modal.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/dataset_info_tab_view.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/skeleton_tab_view.tsx
  frontend/javascripts/oxalis/view/statusbar.tsx
  frontend/javascripts/test/fixtures/volumetracing_object.ts
  frontend/javascripts/test/reducers/volumetracing_reducer.spec.ts
  frontend/javascripts/types/api_flow_types.ts
  frontend/javascripts/types/schemas/datasource.schema.ts
  frontend/javascripts/types/schemas/datasource.types.ts
  test/backend/Dummies.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/n5/N5DataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataFormat.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/proto/VolumeTracing.proto
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/FallbackLayerAdapter.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingDefaults.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeUpdateActions.scala
Labels: enhancement, backend, frontend

#6483 Make version history view paginated
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.tsx
  frontend/javascripts/oxalis/view/version_list.tsx
  frontend/javascripts/oxalis/view/version_view.tsx
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/SkeletonTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/SkeletonTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: enhancement, backend, frontend

#6492 SQL schema cleanup
  MIGRATIONS.unreleased.md
  conf/evolutions/090-cleanup.sql
  conf/evolutions/reversions/090-cleanup.sql
  tools/postgres/schema.sql
Labels: backend, refactoring

#6498 Fix sql evolution 090 (defer not null constraint)
  conf/evolutions/090-cleanup.sql
Labels: backend

#6501 voxel³ -> voxel
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.ts
Labels: automerge

#6515 Always return 404 for Failures in Zarr Streaming
  CHANGELOG.unreleased.md
  util/src/main/scala/com/scalableminds/util/mvc/ExtendedController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingZarrStreamingController.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: bug, backend
