Repository scalableminds/webknossos, pull requests merged in 2022-08, with the labels that each got.

#6360 refactor backend: unify dataclass constructor naming
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/AuthenticationController.scala
  app/controllers/DataSetController.scala
  app/controllers/JobsController.scala
  app/controllers/LegacyApiController.scala
  app/controllers/MeshController.scala
  app/controllers/ProjectController.scala
  app/controllers/ReportController.scala
  app/controllers/ScriptController.scala
  app/controllers/TaskController.scala
  app/controllers/TaskTypeController.scala
  app/controllers/TeamController.scala
  app/controllers/TimeController.scala
  app/controllers/UserController.scala
  app/controllers/UserTokenController.scala
  app/controllers/WKRemoteDataStoreController.scala
  app/controllers/WKRemoteWorkerController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationIdentifier.scala
  app/models/annotation/AnnotationInformationProvider.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/organization/Organization.scala
  app/models/task/TaskCreationService.scala
  app/models/task/TaskType.scala
  app/models/team/Team.scala
  app/models/user/User.scala
  app/models/user/UserService.scala
  app/models/user/time/TimeSpan.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  app/utils/SQLHelpers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/ParsedMappingCache.scala
Labels: backend, refactoring

#6359 Skip current directory “.” in zarr directory listings
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
Labels: backend

#6355 Add layer name to jobs table entry of tiff export job
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/job/job_list_view.tsx
  frontend/javascripts/types/api_flow_types.ts
Labels: enhancement, frontend, jobs

#6314 Auto save changes in sharing modal
  CHANGELOG.unreleased.md
  frontend/javascripts/messages.ts
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.tsx
Labels: enhancement, frontend, discussion

#6364 Links to datasets added.
  docs/publications.md
Labels: automerge

#6358 Remove most return statements from scala code
  app/controllers/AnnotationIOController.scala
  app/controllers/LegacyApiController.scala
  app/controllers/UserTokenController.scala
  app/models/task/TaskCreationService.scala
  app/models/task/TaskService.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/mail/MailchimpClient.scala
  app/utils/SQLHelpers.scala
  test/backend/SkeletonUpdateActionsUnitTestSuite.scala
  util/src/main/scala/com/scalableminds/util/io/PathUtils.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/slacknotification/TSSlackNotificationService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: backend, refactoring

#6362 Remember the forcefully disabled tool and reenable it if possible
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/action-bar/toolbar_view.tsx
Labels: enhancement, frontend, new feature

#6363 Fix Zarr Segmentation Layer json parsing
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
Labels: bug, backend, zarr

#6373 Initialize volume layer name with fallback segmentation name
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/oxalis/view/left-border-tabs/modals/add_volume_layer_modal.tsx
Labels: enhancement, frontend

#6378 fix closing of annotation share modal
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.tsx
Labels: bug, frontend

#6380 Show reload layer button only to those with permission
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/left-border-tabs/layer_settings_tab.tsx
Labels: bug, enhancement, frontend, automerge

#6369 Isosurfaces for volume annotation layers with fallback segmentation
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/sagas/isosurface_saga.ts
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/RemoteFallbackLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingBucketHelper.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: enhancement, backend, automerge

#6381 Return 404 for not-found zarr chunks
  CHANGELOG.unreleased.md
  conf/messages
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
Labels: automerge

#6370 Allow to extrude segment instead of interpolate (similar to the old "copy from previous slice" feature)
  CHANGELOG.unreleased.md
  docs/volume_annotation.md
  frontend/javascripts/oxalis/constants.ts
  frontend/javascripts/oxalis/default_state.ts
  frontend/javascripts/oxalis/model/actions/volumetracing_actions.ts
  frontend/javascripts/oxalis/model/sagas/volume/volume_interpolation_saga.ts
  frontend/javascripts/oxalis/model/sagas/volumetracing_saga.tsx
  frontend/javascripts/oxalis/store.ts
  frontend/javascripts/oxalis/view/action-bar/toolbar_view.tsx
  frontend/javascripts/test/reducers/volumetracing_reducer.spec.ts
  frontend/javascripts/types/schemas/user_settings.schema.ts
Labels: automerge

#6384 Fix job export link in slack notification
  app/models/job/Job.scala
Labels: bug, backend

#6386 adds button for duplicating annotations
  CHANGELOG.unreleased.md
  docs/tracing_ui.md
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.tsx
Labels: frontend, automerge

#6382 Dataset Upload: Improve heuristic to detect mag/layer-only dir
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataFormat.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
Labels: bug, backend

#6377 Filter datasets by organization, use that in task creation view
  CHANGELOG.unreleased.md
  app/controllers/DataSetController.scala
  app/controllers/ProjectController.scala
  app/controllers/UserController.scala
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/task/task_create_form_view.tsx
  frontend/javascripts/test/backend-snapshot-tests/datasets.e2e.ts
  util/src/main/scala/com/scalableminds/util/mvc/Filter.scala
Labels: bug, backend, frontend, new feature

#6388 Fix uint16 grayscale to rgb conversion for thumbnails
  util/src/main/scala/com/scalableminds/util/image/ImageCreator.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/requests/Cuboid.scala
Labels: bug, backend

#6393 Fix cors headers for datastore+tracingstore buildinfo
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/StandaloneDatastore.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/StandaloneTracingstore.scala
Labels: bug, backend

#6376 List unlisted users to superUsers
  app/models/user/User.scala
Labels: enhancement, backend

#6396 Include publication in dataset json again for compatibility with webknossos-libs
  app/models/binary/DataSetService.scala
  frontend/javascripts/oxalis/default_state.ts
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  frontend/javascripts/types/api_flow_types.ts
Labels: bug, backend

#6379 Strict permission checks during all steps of dataset upload
  CHANGELOG.unreleased.md
  app/controllers/UserTokenController.scala
  app/models/binary/DataSetService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AccessTokenService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: bug, backend, security, refactoring

#6317 Support uint64 segmentations (up to 2^53 - 1)
  CHANGELOG.unreleased.md
  app/models/annotation/AnnotationService.scala
  conf/messages
  frontend/javascripts/libs/resizable_buffer.ts
  frontend/javascripts/libs/utils.ts
  frontend/javascripts/messages.ts
  frontend/javascripts/oxalis/api/api_latest.ts
  frontend/javascripts/oxalis/constants.ts
  frontend/javascripts/oxalis/controller/td_controller.tsx
  frontend/javascripts/oxalis/geometries/materials/plane_material_factory.ts
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.ts
  frontend/javascripts/oxalis/model/bucket_data_handling/bucket.ts
  frontend/javascripts/oxalis/model/bucket_data_handling/data_cube.ts
  frontend/javascripts/oxalis/model/bucket_data_handling/data_rendering_logic.tsx
  frontend/javascripts/oxalis/model/sagas/clip_histogram_saga.ts
  frontend/javascripts/oxalis/model/sagas/mapping_saga.ts
  frontend/javascripts/oxalis/model/sagas/min_cut_saga.ts
  frontend/javascripts/oxalis/model/sagas/proofread_saga.ts
  frontend/javascripts/oxalis/model/sagas/save_saga.ts
  frontend/javascripts/oxalis/model/sagas/volume/volume_interpolation_saga.ts
  frontend/javascripts/oxalis/model_initialization.ts
  frontend/javascripts/oxalis/shaders/filtering.glsl.ts
  frontend/javascripts/oxalis/shaders/main_data_fragment.glsl.ts
  frontend/javascripts/oxalis/shaders/segmentation.glsl.ts
  frontend/javascripts/oxalis/shaders/texture_access.glsl.ts
  frontend/javascripts/oxalis/store.ts
  frontend/javascripts/oxalis/view/context_menu.tsx
  frontend/javascripts/oxalis/view/merger_mode_modal_view.tsx
  frontend/javascripts/oxalis/view/statusbar.tsx
  frontend/javascripts/oxalis/view/tracing_view.tsx
  frontend/javascripts/types/api_flow_types.ts
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/UnsignedInteger.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingBucketHelper.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: backend, frontend, new feature

#6404 restore upload routes cors headers
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
Labels: bug, backend, urgent

#6403 Fix undo/redo for volume interpolation/extrusion
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/sagas/volume/volume_interpolation_saga.ts
Labels: automerge

#6411 If Layer BoundingBoxes intersect, Use Intersection Center for all Layer Thumbnails
  CHANGELOG.unreleased.md
  app/controllers/DataSetController.scala
  util/src/main/scala/com/scalableminds/util/geometry/BoundingBox.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataSource.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/BoundingBoxMerger.scala
Labels: enhancement, backend

#6392 remove remote datastore feature
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/DataSetController.scala
  app/controllers/DataStoreController.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStore.scala
  conf/application.conf
  conf/evolutions/086-drop-foreign-datastores.sql
  conf/evolutions/reversions/086-drop-foreign-datastores.sql
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/dataset/dataset_add_foreign_view.tsx
  frontend/javascripts/admin/dataset/dataset_add_view.tsx
  frontend/javascripts/admin/onboarding.tsx
  frontend/javascripts/dashboard/advanced_dataset/dataset_action_view.tsx
  frontend/javascripts/dashboard/dataset/dataset_cache_provider.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_sharing_tab.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_view.tsx
  frontend/javascripts/messages.ts
  frontend/javascripts/oxalis/default_state.ts
  frontend/javascripts/test/fixtures/skeletontracing_server_objects.ts
  frontend/javascripts/test/fixtures/tasktracing_server_objects.ts
  frontend/javascripts/test/fixtures/volumetracing_server_objects.ts
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  frontend/javascripts/types/api_flow_types.ts
  test/db/dataStores.csv
  tools/postgres/schema.sql
Labels: backend, frontend, refactoring

#6335 Import Remote Zarr Datasets
  CHANGELOG.unreleased.md
  app/controllers/DataSetController.scala
  app/controllers/WKRemoteDataStoreController.scala
  app/models/binary/DataSetService.scala
  app/models/binary/ExploreRemoteLayerService.scala
  conf/META-INF/services/java.nio.file.spi.FileSystemProvider
  conf/messages
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/dataset/dataset_add_view.tsx
  frontend/javascripts/admin/dataset/dataset_add_zarr_view.tsx
  frontend/javascripts/messages.ts
  frontend/javascripts/oxalis/view/right-border-tabs/starting_job_modals.tsx
  frontend/javascripts/types/schemas/datasource.types.ts
  util/src/main/scala/com/scalableminds/util/geometry/Vec3Double.scala
  util/src/main/scala/com/scalableminds/util/geometry/Vec3Int.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/AxisOrder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ChunkReader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ChunkUtils.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/Compressor.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/FileSystemStore.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/MultiArrayUtils.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/OmeNgffHeader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/Store.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ZarrArray.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ZarrHeader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ZarrPath.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataSource.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/FileSystemsHolder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpFileSystemProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsFileSystemProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsPath.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsSeekableByteChannel.scala
  webknossos-datastore/conf/META-INF/services/java.nio.file.spi.FileSystemProvider
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
Labels: backend, frontend, new feature

#6367 Zarr private links
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/AnnotationPrivateLinkController.scala
  app/controllers/LegacyApiController.scala
  app/controllers/UserTokenController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationMerger.scala
  app/models/annotation/AnnotationPrivateLink.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/WKRemoteTracingStoreClient.scala
  app/models/annotation/nml/NmlWriter.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/user/Invite.scala
  app/oxalis/security/RandomIDGenerator.scala
  app/oxalis/security/WkSilhouetteEnvironment.scala
  conf/evolutions/087-zarr-private-links.sql
  conf/evolutions/reversions/087-zarr-private-links.sql
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/components/formatted_date.tsx
  frontend/javascripts/main.tsx
  frontend/javascripts/messages.tsx
  frontend/javascripts/oxalis/view/action-bar/private_links_view.tsx
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/share_view_dataset_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.tsx
  frontend/javascripts/oxalis/view/layouting/tracing_layout_view.tsx
  frontend/javascripts/types/api_flow_types.ts
  frontend/stylesheets/main.less
  package.json
  test/backend/NMLUnitTestSuite.scala
  tools/postgres/schema.sql
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ZarrHeader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/annotation/AnnotationLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/annotation/AnnotationLayerType.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/annotation/AnnotationSource.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteTracingstoreClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
  yarn.lock
Labels: backend, frontend, new feature

#6422 Small Zarr Fixes
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/BytesConverter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ZarrHeader.scala
Labels: bug, backend

#6425 Fix dataset access by sharing token
  app/models/binary/DataSet.scala
Labels: bug, backend

#6413 Create unified json format for ObjectId
  app/controllers/ScriptController.scala
  app/controllers/TaskTypeController.scala
  app/models/mesh/Mesh.scala
  app/models/project/Project.scala
  app/models/task/Script.scala
  app/models/task/TaskType.scala
  app/models/team/TeamMembership.scala
  app/utils/ObjectId.scala
  app/utils/SQLHelpers.scala
Labels: backend, refactoring

#6421 Unsigned Access to Pubilc S3 Data
  CHANGELOG.unreleased.md
  build.sbt
  conf/META-INF/services/java.nio.file.spi.FileSystemProvider
  frontend/javascripts/admin/dataset/dataset_add_zarr_view.tsx
  project/Dependencies.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/AmazonS3Factory.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/LICENSE
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3AccessControlList.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3FileChannel.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3FileStore.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3FileStoreAttributeView.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3FileSystem.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3FileSystemConfigurationException.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3FileSystemProvider.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3Iterator.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3Path.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3ReadOnlySeekableByteChannel.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3SeekableByteChannel.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/attribute/S3BasicFileAttributeView.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/attribute/S3BasicFileAttributes.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/attribute/S3PosixFileAttributeView.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/attribute/S3PosixFileAttributes.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/attribute/S3UserPrincipal.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/util/AnonymousAWSCredentialsProvider.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/util/AttributesUtils.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/util/Cache.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/util/IOUtils.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/util/S3Utils.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/FileSystemsHolder.scala
  webknossos-datastore/conf/META-INF/services/java.nio.file.spi.FileSystemProvider
Labels: enhancement, backend
