Repository scalableminds/webknossos, pull requests merged in 2022-04, with the labels that each got.

#6131 Small updates to dataset list
  CHANGELOG.unreleased.md
  frontend/javascripts/dashboard/advanced_dataset/dataset_table.js
  frontend/javascripts/types/api_flow_types.js
Labels: frontend

#6152 Do not depend on jzarr, use jblosc, ucarCdm directly
  project/Dependencies.scala
Labels: backend, refactoring

#6146 Remove unlink fallback layer functionality
  CHANGELOG.unreleased.md
  app/controllers/AnnotationController.scala
  app/models/annotation/WKRemoteTracingStoreClient.scala
  conf/messages
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/messages.js
  frontend/javascripts/oxalis/view/left-border-tabs/layer_settings_tab.js
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: automerge

#6158 Better error messages and logging for dataset uploads
  conf/messages
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
Labels: backend

#6160 Consistent serialization for SQL array literals
  CHANGELOG.unreleased.md
  app/models/annotation/Annotation.scala
  app/models/binary/DataSet.scala
  app/models/task/TaskType.scala
  app/utils/SQLHelpers.scala
Labels: bug, backend

#6109 increase ws default timeouts
  conf/application.conf
  webknossos-datastore/conf/standalone-datastore.conf
  webknossos-tracingstore/conf/standalone-tracingstore.conf
Labels: backend

#6167 In dataset upload, allow un-sorted anisotropic mags in properties.json
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
Labels: bug, backend

#6165 Asynchronous cache for zarr chunk loading
  CHANGELOG.unreleased.md
  project/Dependencies.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/DataCubeHandle.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ChunkContentsCache.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ChunkReader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ZarrArray.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/DataCubeCache.scala
Labels: backend, performance

#6166 Move "User access list" to Settings
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/onboarding.tsx
  frontend/javascripts/dashboard/advanced_dataset/dataset_access_list_view.tsx
  frontend/javascripts/dashboard/advanced_dataset/dataset_table.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_delete_tab.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_metadata_tab.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_sharing_tab.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_view.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_viewconfig_tab.tsx
  frontend/javascripts/dashboard/dataset_view.tsx
  frontend/javascripts/router.tsx
Labels: frontend

#6169 Update navbar.tsx
  frontend/javascripts/navbar.tsx
Labels: automerge

#6151 Remove Sample Datasets, advertise public dataset instead
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/dataset/dataset_add_view.tsx
  frontend/javascripts/admin/onboarding.tsx
  frontend/javascripts/dashboard/dataset/sample_datasets_modal.tsx
  frontend/javascripts/dashboard/dataset_view.tsx
  frontend/javascripts/types/api_flow_types.ts
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreModule.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/SampleDataSourceService.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend, frontend

#6172 Better error message when creating team with already-taken name
  app/controllers/TeamController.scala
  app/models/team/Team.scala
Labels: bug, backend
