Repository scalableminds/webknossos, pull requests merged in 2022-03, with the labels that each got.

#6091 More PR feedback for Docs
  docs/sharing.md
  docs/skeleton_annotation.md
  docs/users.md
Labels: documentation

#6098 Add remote origin headers also in error case
  CHANGELOG.unreleased.md
  app/controllers/Controller.scala
  app/controllers/DataSetController.scala
  app/controllers/TaskController.scala
  util/src/main/scala/com/scalableminds/util/mvc/ExtendedController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Application.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Controller.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ExportsController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/StandaloneDatastore.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/Application.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/SkeletonTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/TracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
Labels: backend

#6099 Disallow deactivating users with active tasks
  CHANGELOG.unreleased.md
  app/controllers/UserController.scala
  app/models/annotation/Annotation.scala
Labels: backend

#6103 Unify long-running RPC timeouts
  CHANGELOG.unreleased.md
  app/controllers/Application.scala
  app/models/annotation/WKRemoteTracingStoreClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/SampleDataSourceService.scala
Labels: backend

#6105 Fix markdown issues in docs
  docs/data_formats.md
  docs/datasets.md
  docs/faq.md
  docs/jobs.md
  docs/sharing.md
  docs/skeleton_annotation.md
  docs/tasks.md
  docs/tracing_ui.md
  docs/users.md
Labels: documentation

#6102 Add "hide/show other trees" to tree context-menu
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/right-border-tabs/tree_hierarchy_view.js
Labels: enhancement, frontend

#6113 lower histogram clip threshold a bit
  frontend/javascripts/oxalis/model/sagas/clip_histogram_saga.js
Labels: enhancement, frontend

#6111 adapt readme for m1-mac setups
  README.md
  webpack.config.js
Labels: automerge

#6117 Fix slack notification for arthur
  .circleci/slack-notification.sh
Labels: automerge

#6019 Read Zarr Datasets
  CHANGELOG.unreleased.md
  Dockerfile
  README.md
  conf/META-INF/services/java.nio.file.spi.FileSystemProvider
  package.json
  project/Dependencies.scala
  project/DependencyResolvers.scala
  util/src/main/scala/com/scalableminds/util/cache/LRUConcurrentCache.scala
  util/src/main/scala/com/scalableminds/util/geometry/Vec3Int.scala
  util/src/main/scala/com/scalableminds/util/io/ZipIO.scala
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/DataCubeHandle.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ArrayOrder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/BytesConverter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ChunkContentsCache.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ChunkReader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ChunkUtils.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/Compressor.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/DimensionSeparator.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/LICENSE
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/MultiArrayUtils.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/Store.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ZarrArray.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ZarrDataType.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ZarrHeader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/jzarr/ZarrPath.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/Positions.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/DataCubeCache.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/FileSystemsHolder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsBasicAuthCredentials.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsFileSystem.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsFileSystemProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsPath.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsSeekableByteChannel.scala
  webknossos-datastore/conf/META-INF/services/java.nio.file.spi.FileSystemProvider
Labels: backend, new feature

#6121 Materialize FileSystemProvider meta file
  webknossos-datastore/conf/META-INF/services/java.nio.file.spi.FileSystemProvider
Labels: bug, backend

#6122 install blosc in standalone datastore dockerfile
  webknossos-datastore/Dockerfile
Labels: bug, backend

#6116 allow all resolutions if there is no volume annotation in the nml
  .circleci/slack-notification.sh
  CHANGELOG.unreleased.md
  frontend/javascripts/messages.js
  util/src/main/scala/com/scalableminds/util/io/PathUtils.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: backend
