Repository scalableminds/webknossos, pull requests merged in 2022-02, with the labels that each got.

#6009 use allDataBlocking and temporary files for explorative download
  CHANGELOG.unreleased.md
  app/controllers/AnnotationIOController.scala
  app/models/annotation/AnnotationLayer.scala
  app/models/annotation/WKRemoteTracingStoreClient.scala
  app/models/annotation/nml/NmlWriter.scala
  util/src/main/scala/com/scalableminds/util/io/FileIO.scala
  util/src/main/scala/com/scalableminds/util/io/ZipIO.scala
Labels: bug, backend

#6022 For empty volume tracings, serve header-only zip
  CHANGELOG.unreleased.md
  util/src/main/scala/com/scalableminds/util/io/ZipIO.scala
Labels: enhancement, backend

#6021 Map node group context menu to right-click
  frontend/javascripts/oxalis/view/right-border-tabs/tree_hierarchy_view.js
Labels: frontend

#6012 Added shorthand to mark branch points from context menu
  frontend/javascripts/oxalis/model/actions/skeletontracing_actions.js
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer.js
  frontend/javascripts/oxalis/view/context_menu.js
  frontend/javascripts/test/reducers/skeletontracing_reducer.spec.js
Labels: frontend

#6013 add shorthand for deleting trees
  frontend/javascripts/oxalis/view/right-border-tabs/tree_hierarchy_view.js
Labels: frontend

#6028 Allow uploading multi-layer volume annotations
  CHANGELOG.unreleased.md
  app/controllers/AnnotationIOController.scala
  app/controllers/TaskController.scala
  app/models/annotation/AnnotationUploadService.scala
  app/models/annotation/nml/NmlParser.scala
  app/models/annotation/nml/NmlResults.scala
  app/models/annotation/nml/NmlVolumeTag.scala
  test/backend/NMLUnitTestSuite.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/Volume.scala
Labels: enhancement, backend

#5922 Add neuron reconstruction job backend and frontend part
  app/controllers/JobsController.scala
  app/models/job/Job.scala
  app/models/user/UserService.scala
  clean
  conf/messages
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/job/job_list_view.js
  frontend/javascripts/libs/utils.js
  frontend/javascripts/oxalis/model/accessors/tracing_accessor.js
  frontend/javascripts/oxalis/model/sagas/save_saga.js
  frontend/javascripts/oxalis/view/components/setting_input_views.js
  frontend/javascripts/oxalis/view/right-border-tabs/dataset_info_tab_view.js
  frontend/javascripts/oxalis/view/right-border-tabs/nuclei_inferral_modal.js
  frontend/javascripts/oxalis/view/right-border-tabs/starting_job_modals.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/users.e2e.js.snap
  frontend/javascripts/types/api_flow_types.js
  frontend/stylesheets/trace_view/_right_menu.less
  public/images/neuron_inferral_example.jpg
Labels: frontend, new feature

#6040 Faster CircleCI builds
  .circleci/config.yml
Labels: automerge

#6047 Fix non-32-aligned bucket requests
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/Positions.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/requests/DataServiceRequests.scala
Labels: bug, backend, automerge

#6045 Include ParamFailure values in error chains
  util/src/main/scala/com/scalableminds/util/mvc/ExtendedController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
Labels: backend, automerge

#6051 Time tracking: Do not fail on empty timestamps list
  app/models/user/time/TimeSpanService.scala
Labels: bug, backend

#6070 Skip deactivated users in dataset access list
  CHANGELOG.unreleased.md
  app/controllers/ReportController.scala
  app/models/user/User.scala
Labels: bug, backend

#6072 Serve empty service worker js for Demo Instance
  app/RequestHandler.scala
Labels: backend

#6058 Fix duplicating annotations via toggling show archived annotations button and fix downsample modal rendering errors
  CHANGELOG.unreleased.md
  frontend/javascripts/dashboard/explorative_annotations_view.js
  frontend/javascripts/oxalis/view/left-border-tabs/layer_settings_tab.js
  frontend/javascripts/oxalis/view/left-border-tabs/modals/downsample_volume_modal.js
Labels: bug, frontend
