Repository scalableminds/webknossos, pull requests merged in 2022-01, with the labels that each got.

#5912 Include result link in job slack notification
  app/controllers/WKRemoteWorkerController.scala
  app/models/job/Job.scala
  app/models/job/JobStatus.scala
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/job/job_list_view.js
  frontend/javascripts/types/api_flow_types.js
Labels: backend, frontend, jobs

#5926 fix wording in dataset table
  frontend/javascripts/dashboard/advanced_dataset/dataset_table.js
Labels: frontend

#5930 Add dataset tags to searchable properties
  frontend/javascripts/dashboard/advanced_dataset/dataset_table.js
Labels: enhancement, frontend

#5907 query synapses between agglomerate set from connectome file
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/ConnectomeFileService.scala
Labels: backend

#5931 Rename Sample User
  .circleci/config.yml
  app/controllers/InitialDataController.scala
  conf/application.conf
  frontend/javascripts/test/fixtures/tasktracing_server_objects.js
  tools/volume-stress-test/volume-stress-client.sh
Labels: backend

#5939 Check dataset upload name conflicts to avoid sql errors
  app/controllers/WKRemoteDataStoreController.scala
Labels: backend

#5927 Fix race condition in volume data download
  CHANGELOG.unreleased.md
  util/src/main/scala/com/scalableminds/util/io/ZipIO.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
Labels: bug, backend

#5949 Prevent organization creation with existing email address
  CHANGELOG.unreleased.md
  app/controllers/AuthenticationController.scala
Labels: backend

#5950 Validate file paths on dataset upload
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
Labels: bug, backend, security

#5942 Serve exported files from datastore
  CHANGELOG.unreleased.md
  app/controllers/JobsController.scala
  app/controllers/UserTokenController.scala
  app/controllers/WKRemoteDataStoreController.scala
  app/models/job/Job.scala
  conf/webknossos.latest.routes
  frontend/javascripts/admin/job/job_list_view.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ExportsController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AccessTokenService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: enhancement, backend

#5954 adds swagger definition to DataSetController#isValidNewName
  .scalafmt.conf
  app/controllers/DataSetController.scala
Labels: automerge

#5965 Make organization name accessible in the UI
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/auth/auth_token_view.js
  frontend/javascripts/admin/organization/organization_edit_view.js
Labels: automerge

#5946 Allow Cancelling Jobs
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/JobsController.scala
  app/controllers/WKRemoteWorkerController.scala
  app/models/job/Job.scala
  app/models/job/JobState.scala
  app/models/job/JobStatus.scala
  conf/evolutions/080-job-add-cancelled.sql
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/job/job_list_view.js
  tools/postgres/schema.sql
Labels: backend, frontend, jobs

#5980 Add debug output to failing dataset list requests
  app/controllers/DataSetController.scala
  app/models/binary/DataSetService.scala
  conf/messages
Labels: backend

#5976 Avoid scroll bars caused by context menu positioning
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/context_menu.js
  frontend/stylesheets/trace_view/_tracing_view.less
Labels: automerge

#5969 Upgrade webpack to v5
  .circleci/config.yml
  .flowconfig
  CHANGELOG.unreleased.md
  app/views/main.scala.html
  frontend/javascripts/libs/error_handling.js
  frontend/javascripts/oxalis/view/right-border-tabs/segments_tab/segments_view.js
  frontend/javascripts/test/puppeteer/dataset_rendering.screenshot.js
  package.json
  webpack.config.js
  yarn.lock
Labels: infrastructure, performance, dependencies, automerge

#5974 Clean up frontend deprecations and warnings
  frontend/javascripts/admin/job/job_list_view.js
  frontend/javascripts/admin/project/project_list_view.js
  frontend/javascripts/admin/scripts/script_list_view.js
  frontend/javascripts/admin/task/task_list_view.js
  frontend/javascripts/admin/task/task_search_form.js
  frontend/javascripts/admin/tasktype/task_type_list_view.js
  frontend/javascripts/admin/team/team_list_view.js
  frontend/javascripts/admin/user/permissions_and_teams_modal_view.js
  frontend/javascripts/admin/user/user_list_view.js
  frontend/javascripts/components/async_clickables.js
  frontend/javascripts/dashboard/dashboard_task_list_view.js
  frontend/javascripts/dashboard/dashboard_view.js
  frontend/javascripts/dashboard/dataset/helper_components.js
  frontend/javascripts/dashboard/dataset/team_selection_component.js
  frontend/javascripts/dashboard/explorative_annotations_view.js
  frontend/javascripts/dashboard/shared_annotations_view.js
  frontend/javascripts/libs/vector_input.js
  frontend/javascripts/navbar.js
  frontend/javascripts/oxalis/view/action-bar/merge_modal_view.js
  frontend/javascripts/oxalis/view/action-bar/user_scripts_modal_view.js
  frontend/javascripts/oxalis/view/components/editable_text_label.js
  frontend/javascripts/oxalis/view/components/input_component.js
  frontend/javascripts/oxalis/view/components/setting_input_views.js
  frontend/javascripts/oxalis/view/context_menu.js
  frontend/javascripts/oxalis/view/left-border-tabs/controls_and_rendering_settings_tab.js
  frontend/javascripts/oxalis/view/left-border-tabs/histogram_view.js
  frontend/javascripts/oxalis/view/left-border-tabs/layer_settings_tab.js
Labels: automerge

#5983 Fix placeholder resolutions for anisotropic layers with missing base resolutions
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.js
  frontend/javascripts/test/model/model_resolutions.spec.js
Labels: automerge

#5982 Honor mappingStatus when requesting to compute meshes ad-hoc
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.js
Labels: automerge

#5992 Fix positioning of clip button
  frontend/javascripts/oxalis/view/left-border-tabs/histogram_view.js
Labels: automerge

#5967 Store layer visibility with annotation
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/AnnotationController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
  conf/evolutions/081-annotation-viewconfiguration.sql
  conf/evolutions/reversions/081-annotation-viewconfiguration.sql
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/oxalis/model/sagas/annotation_saga.js
  frontend/javascripts/oxalis/model_initialization.js
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  frontend/javascripts/test/snapshots/public/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  frontend/javascripts/types/api_flow_types.js
  test/db/annotations.csv
  tools/postgres/schema.sql
Labels: enhancement, backend, frontend

#5958 Allow cancelling uploads
  CHANGELOG.unreleased.md
  app/controllers/WKRemoteDataStoreController.scala
  app/controllers/WKRemoteWorkerController.scala
  app/models/job/Job.scala
  conf/messages
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.js
  frontend/javascripts/admin/dataset/dataset_upload_view.js
  frontend/javascripts/dashboard/dataset/import_delete_component.js
  frontend/javascripts/messages.js
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/DataSetDeleter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/DirectoryConstants.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceRepository.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/SampleDataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: backend, frontend

#6001 Allow Download of Public Annotations While Logged Out
  CHANGELOG.unreleased.md
  app/controllers/AnnotationIOController.scala
Labels: backend
