Repository scalableminds/webknossos, pull requests merged in 2023-11, with the labels that each got.

#7413 Add uint24 support for DatasetArray-based formats (excepting ND)
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/n5/N5BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/precomputed/PrecomputedBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr3/Zarr3BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/DatasetArray.scala
Labels: backend, new feature

#7366 Upgrade to Play 2.9
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/RequestHandler.scala
  app/models/annotation/AnnotationUploadService.scala
  app/models/dataset/credential/CredentialDAO.scala
  app/models/dataset/credential/CredentialService.scala
  app/models/dataset/explore/ExploreRemoteLayerService.scala
  app/models/dataset/explore/N5MultiscalesExplorer.scala
  app/models/dataset/explore/RemoteLayerExplorer.scala
  build.sbt
  project/Dependencies.scala
  project/DependencyResolvers.scala
  project/build.properties
  project/plugins.sbt
  util/src/main/scala/com/scalableminds/util/io/FileIO.scala
  util/src/main/scala/com/scalableminds/util/io/ZipIO.scala
  util/src/main/scala/com/scalableminds/util/mvc/ExtendedController.scala
  util/src/main/scala/com/scalableminds/util/tools/JsonHelper.scala
  webknossos-datastore/app/DsRequestHandler.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/ChunkReader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/ChunkTyper.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/Compressor.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/DatasetArray.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/MultiArrayUtils.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/n5/N5ChunkReader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/n5/N5DataExtractor.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/precomputed/PrecomputedArray.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/zarr/BytesConverter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/zarr3/Zarr3ArrayHeader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datavault/FileSystemDataVault.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datavault/GoogleCloudDataVault.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datavault/S3DataVault.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datavault/VaultPath.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/JsonImplicits.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AgglomerateService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/ConnectomeFileService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSUsedStorageService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/MeshFileService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/UploadService.scala
  webknossos-datastore/app/play/modules/swagger/SwaggerModule.scala
  webknossos-tracingstore/app/TsRequestHandler.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingUpdater.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeSegmentIndexService.scala
Labels: backend, refactoring

#7421 Move maintenance banner to top of the screen
  CHANGELOG.unreleased.md
  frontend/javascripts/maintenance_banner.tsx
  frontend/javascripts/navbar.tsx
  frontend/javascripts/oxalis/constants.ts
  frontend/javascripts/oxalis/default_state.ts
  frontend/javascripts/oxalis/model/accessors/view_mode_accessor.ts
  frontend/javascripts/oxalis/model/actions/ui_actions.ts
  frontend/javascripts/oxalis/model/reducers/ui_reducer.ts
  frontend/javascripts/oxalis/store.ts
  frontend/javascripts/oxalis/view/arbitrary_view.ts
  frontend/javascripts/oxalis/view/layouting/default_layout_configs.ts
  frontend/javascripts/oxalis/view/nml_upload_zone_container.tsx
  frontend/javascripts/oxalis/view/plane_view.ts
  frontend/javascripts/router.tsx
  frontend/stylesheets/_utils.less
  frontend/stylesheets/_variables.less
  frontend/stylesheets/main.less
  frontend/stylesheets/trace_view/_tracing_view.less
Labels: frontend

#7379 Fix "Import Agglomerate Skeleton" tooltip
  frontend/javascripts/oxalis/view/context_menu.tsx
Labels: automerge

#7430 Add stats filter to task list view
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/task/task_list_view.tsx
Labels: frontend, automerge

#7367 Define CSP
  MIGRATIONS.unreleased.md
  app/views/main.scala.html
  conf/application.conf
  frontend/javascripts/libs/error_handling.ts
  frontend/javascripts/libs/window.ts
  frontend/javascripts/main.tsx
Labels: enhancement, frontend, security

#7442 Avoid Exception when trying to explore as Neuroglancer URI
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/explore/NeuroglancerUriExplorer.scala
Labels: bug, backend

#7441 Unify Fox.transformFuture and future2Fox
  tools/nml/nmlgenerator.py
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datavault/HttpsDataVault.scala
Labels: backend, refactoring

#7434 updated the delete orga warning text
  frontend/javascripts/admin/organization/organization_edit_view.tsx
Labels: frontend, automerge

#7449 Fix ad-hoc meshing with agglomerates and cumsum.json
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/Positions.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/requests/Cuboid.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AdHocMeshService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/AgglomerateFileCache.scala
Labels: bug, backend
