Repository scalableminds/webknossos, pull requests merged in 2023-07, with the labels that each got.

#7181 in dev_install.md, mention refresh-schema, change flow to tsc
  DEV_INSTALL.md
Labels: documentation

#7184 add title tags to mouse button images
  frontend/javascripts/oxalis/view/right-border-tabs/dataset_info_tab_view.tsx
Labels: enhancement, frontend

#7185 Added new publications to the docs
  docs/publications.md
  docs/tracing_ui.md
Labels: documentation

#7191 enable security.txt route also for no-ds setup
  conf/noDS.noTS.routes
  conf/noDS.routes
  conf/noTS.routes
Labels: backend

#7195 Fix typo in user list view
  frontend/javascripts/admin/user/user_list_view.tsx
Labels: frontend

#7187 Rename Open Tasks to Pending
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/project/project_list_view.tsx
  frontend/javascripts/admin/project/transfer_all_tasks_modal.tsx
  frontend/javascripts/admin/statistic/open_tasks_report_view.tsx
  frontend/javascripts/admin/statistic/project_progress_report_view.tsx
  frontend/javascripts/admin/task/task_list_view.tsx
  frontend/javascripts/navbar.tsx
Labels: frontend, low-hanging-fruit

#7201 Add tooltips explaining task "cancel and reset"
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/task/task_annotation_view.tsx
  frontend/javascripts/dashboard/dashboard_task_list_view.tsx
  frontend/javascripts/messages.tsx
Labels: frontend

#7202 fix linting error
  frontend/javascripts/admin/task/task_annotation_view.tsx
Labels: frontend

#7197 Add todos to PR template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: discussion

#7178 Add navigation+layout buttons for mobile
  CHANGELOG.unreleased.md
  app/views/main.scala.html
  frontend/javascripts/components/adapt_viewport_metatag.ts
  frontend/javascripts/components/brain_spinner.tsx
  frontend/javascripts/libs/input.ts
  frontend/javascripts/libs/react_hooks.ts
  frontend/javascripts/libs/utils.ts
  frontend/javascripts/navbar.tsx
  frontend/javascripts/oxalis/constants.ts
  frontend/javascripts/oxalis/controller.tsx
  frontend/javascripts/oxalis/controller/combinations/tool_controls.ts
  frontend/javascripts/oxalis/controller/viewmodes/arbitrary_controller.tsx
  frontend/javascripts/oxalis/controller/viewmodes/plane_controller.tsx
  frontend/javascripts/oxalis/model/accessors/flycam_accessor.ts
  frontend/javascripts/oxalis/model/actions/actions.ts
  frontend/javascripts/oxalis/view/components/border_toggle_button.tsx
  frontend/javascripts/oxalis/view/components/button_component.tsx
  frontend/javascripts/oxalis/view/layouting/default_layout_configs.ts
  frontend/javascripts/oxalis/view/layouting/flex_layout_wrapper.tsx
  frontend/javascripts/oxalis/view/layouting/floating_mobile_controls.tsx
  frontend/javascripts/oxalis/view/layouting/layout_canvas_adapter.ts
  frontend/javascripts/oxalis/view/layouting/tracing_layout_view.tsx
  frontend/javascripts/oxalis/view/tracing_view.tsx
  frontend/javascripts/router.tsx
  frontend/stylesheets/dark.less
  frontend/stylesheets/main.less
  frontend/stylesheets/trace_view/_tracing_view.less
  package.json
  yarn.lock
Labels: frontend

#7190 Thumbnail improvements: persistent cache, configured intensity, float layers
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/Startup.scala
  app/WebKnossosModule.scala
  app/controllers/DataSetController.scala
  app/models/binary/DataSetService.scala
  app/models/binary/ThumbnailService.scala
  app/models/binary/WKRemoteDataStoreClient.scala
  app/models/configuration/DataSetConfigurationService.scala
  app/utils/sql/SqlInterpolation.scala
  app/utils/sql/SqlTypeImplicits.scala
  conf/application.conf
  conf/evolutions/104-thumbnails.sql
  conf/evolutions/reversions/104-thumbnails.sql
  conf/webknossos.latest.routes
  tools/postgres/schema.sql
  util/src/main/scala/com/scalableminds/util/cache/AlfuCache.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/image/ImageCreator.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/ImageThumbnail.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/requests/DataServiceRequests.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: enhancement, backend, new feature, performance

#7217 Fix bug in thumbnail size handling for coarse mags
  app/models/binary/ThumbnailService.scala
Labels: bug, backend

#7216 Catch exceptions in FileSystemDataVault, return Empty or Failure
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datavault/FileSystemDataVault.scala
Labels: bug, backend

#7221 Properly reserve dataset when putting datasource (addRemote)
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/dataset/dataset_add_remote_view.tsx
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
Labels: bug, backend, frontend

#7208 Add route to add segment index to existing volume annotations
  app/controllers/AnnotationController.scala
  app/models/annotation/AnnotationService.scala
  conf/messages
  conf/webknossos.latest.routes
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: enhancement, backend

#7188 Make layer order editable via drag and drop
  CHANGELOG.unreleased.md
  frontend/javascripts/messages.tsx
  frontend/javascripts/oxalis/geometries/materials/plane_material_factory.ts
  frontend/javascripts/oxalis/model_initialization.ts
  frontend/javascripts/oxalis/shaders/main_data_shaders.glsl.ts
  frontend/javascripts/oxalis/store.ts
  frontend/javascripts/oxalis/view/left-border-tabs/layer_settings_tab.tsx
  frontend/javascripts/test/shaders/shader_syntax.spec.ts
  frontend/javascripts/types/schemas/dataset_view_configuration.schema.ts
  frontend/stylesheets/_utils.less
  package.json
  yarn.lock
Labels: enhancement, frontend

#7176 Route to import explored datasources automatically
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/AuthenticationController.scala
  app/controllers/DataSetController.scala
  app/controllers/FolderController.scala
  app/controllers/UserTokenController.scala
  app/models/binary/DataStore.scala
  app/models/binary/WKRemoteDataStoreClient.scala
  app/models/binary/explore/ExploreRemoteLayerService.scala
  app/models/folder/Folder.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  conf/evolutions/106-folder-no-slashes.sql
  conf/evolutions/reversions/106-folder-no-slashes.sql
  conf/messages
  conf/webknossos.latest.routes
  tools/postgres/schema.sql
Labels: backend, new feature
