Repository scalableminds/webknossos, pull requests merged in 2023-10, with the labels that each got.

#7331 Link Previews
  CHANGELOG.unreleased.md
  app/controllers/DatasetController.scala
  app/controllers/WkorgProxyController.scala
  app/models/annotation/Annotation.scala
  app/models/binary/Dataset.scala
  app/oxalis/opengraph/OpenGraphService.scala
  app/views/main.scala.html
  conf/webknossos.latest.routes
Labels: backend, new feature

#7374 Fix reading zarr2 data with channel axis
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrBucketProvider.scala
Labels: bug, backend

#7372 Adds support for remote Zarr3-based Webknossos datasets
  CHANGELOG.unreleased.md
  app/models/dataset/explore/WebknossosZarrExplorer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/zarr3/Zarr3Array.scala
Labels: backend, zarr

#7258 Add measurement tools
  CHANGELOG.unreleased.md
  frontend/javascripts/libs/format_utils.ts
  frontend/javascripts/libs/resizable_buffer.ts
  frontend/javascripts/maintenance_banner.tsx
  frontend/javascripts/navbar.tsx
  frontend/javascripts/oxalis/constants.ts
  frontend/javascripts/oxalis/controller/combinations/tool_controls.ts
  frontend/javascripts/oxalis/controller/scene_controller.ts
  frontend/javascripts/oxalis/controller/viewmodes/plane_controller.tsx
  frontend/javascripts/oxalis/default_state.ts
  frontend/javascripts/oxalis/geometries/helper_geometries.ts
  frontend/javascripts/oxalis/model/accessors/tool_accessor.ts
  frontend/javascripts/oxalis/model/accessors/view_mode_accessor.ts
  frontend/javascripts/oxalis/model/actions/ui_actions.ts
  frontend/javascripts/oxalis/model/reducers/ui_reducer.ts
  frontend/javascripts/oxalis/model/sagas/annotation_tool_saga.ts
  frontend/javascripts/oxalis/model/sagas/root_saga.ts
  frontend/javascripts/oxalis/store.ts
  frontend/javascripts/oxalis/view/action-bar/toolbar_view.tsx
  frontend/javascripts/oxalis/view/context_menu.tsx
  frontend/javascripts/oxalis/view/distance_measurement_tooltip.tsx
  frontend/javascripts/oxalis/view/input_catcher.tsx
  frontend/javascripts/oxalis/view/layouting/default_layout_configs.ts
  frontend/javascripts/oxalis/view/layouting/tracing_layout_view.tsx
  frontend/javascripts/oxalis/view/nml_upload_zone_container.tsx
  frontend/javascripts/test/reducers/volumetracing_reducer.spec.ts
  frontend/javascripts/test/sagas/annotation_tool_saga.spec.ts
  frontend/stylesheets/trace_view/_tracing_view.less
  public/images/area-measurement.svg
  public/images/line-measurement.svg
  public/images/ruler-pointed-border.svg
Labels: frontend, new feature

#7370 Skip typing data chunk arrays if no rechunking is needed
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/ChunkReader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/ChunkTyper.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/DatasetArray.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/zarr/BytesConverter.scala
Labels: enhancement, backend, performance

#7389 Allow Exploring Datasets on Local File System
  CHANGELOG.unreleased.md
  app/models/dataset/credential/CredentialService.scala
  app/models/dataset/explore/ExploreRemoteLayerService.scala
  app/utils/WkConf.scala
  conf/application.conf
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreConfig.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/MagLocator.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/n5/N5BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/precomputed/PrecomputedBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr3/Zarr3BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datavault/FileSystemDataVault.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datavault/FileSystemVaultPath.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/DataVaultService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/RemoteSourceDescriptorService.scala
  webknossos-datastore/conf/standalone-datastore.conf
Labels: backend, new feature

#7349 Support 2d ome zarr
  CHANGELOG.unreleased.md
  app/models/dataset/explore/N5MultiscalesExplorer.scala
  app/models/dataset/explore/NgffExplorer.scala
  app/models/dataset/explore/PrecomputedExplorer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/AxisOrder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/DatasetArray.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/DatasetHeader.scala
Labels: backend, new feature

#7288 Zarr3 download for volume annotation, supporting nd
  CHANGELOG.unreleased.md
  app/controllers/AnnotationIOController.scala
  app/files/TempFileService.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/WKRemoteTracingStoreClient.scala
  app/models/annotation/nml/NmlWriter.scala
  app/models/dataset/explore/ExploreRemoteLayerService.scala
  app/models/dataset/explore/N5ArrayExplorer.scala
  app/models/dataset/explore/WebknossosZarrExplorer.scala
  app/models/dataset/explore/Zarr3ArrayExplorer.scala
  app/models/dataset/explore/ZarrArrayExplorer.scala
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/oxalis/view/action-bar/download_modal_view.tsx
  test/backend/NMLUnitTestSuite.scala
  util/src/main/scala/com/scalableminds/util/geometry/Vec3Double.scala
  util/src/main/scala/com/scalableminds/util/io/FileIO.scala
  util/src/main/scala/com/scalableminds/util/io/ZipIO.scala
  util/src/main/scala/com/scalableminds/util/tools/BoxImplicits.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/MagLocator.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataFormatHelper.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/AxisOrder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/zarr3/Codecs.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/zarr3/Zarr3Array.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/zarr3/Zarr3ArrayHeader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataSource.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeDataZipFormat.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeDataZipHelper.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/WKWBucketStreamSink.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/Zarr3BucketStreamSink.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: enhancement, backend, new feature

#7376 Add Segment Index for Existing Volumes Without Losing History
  MIGRATIONS.unreleased.md
  app/controllers/AnnotationController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/WKRemoteTracingStoreClient.scala
  app/models/annotation/nml/NmlParser.scala
  conf/webknossos.latest.routes
  frontend/javascripts/oxalis/model/sagas/update_actions.ts
  frontend/javascripts/oxalis/view/version_entry.tsx
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeSegmentIndexService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeUpdateActions.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/WKWBucketStreamSink.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/Zarr3BucketStreamSink.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: enhancement, backend

#7348 Add Render Animation Worker Job
  CHANGELOG.unreleased.md
  app/controllers/JobsController.scala
  app/models/job/Job.scala
  app/models/job/JobCommand.scala
  conf/messages
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/job/job_list_view.tsx
  frontend/javascripts/oxalis/default_state.ts
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.ts
  frontend/javascripts/oxalis/model/actions/ui_actions.ts
  frontend/javascripts/oxalis/model/reducers/ui_reducer.ts
  frontend/javascripts/oxalis/store.ts
  frontend/javascripts/oxalis/view/action-bar/create_animation_modal.tsx
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.tsx
  frontend/javascripts/oxalis/view/action-bar/view_dataset_actions_view.tsx
  frontend/javascripts/types/api_flow_types.ts
  public/images/animation-illustration.png
Labels: backend, frontend, worker

#7393 second try for charlie slack notification ping
  .circleci/slack-notification.sh
Labels: CI

#7401 Added email notifications for Blender animation job
  app/models/job/Job.scala
Labels: backend

#7409 Added a hotfix to prevent the animation modal from crashing
  frontend/javascripts/oxalis/view/action-bar/create_animation_modal.tsx
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.tsx
  frontend/javascripts/oxalis/view/action-bar/view_dataset_actions_view.tsx
Labels: bug
