Repository scalableminds/webknossos, pull requests merged in 2023-04, with the labels that each got.

#6950 Log all details on deleting annotation layer
  app/controllers/AnnotationController.scala
Labels: backend

#6938 Added more drawings and rebranding to UI
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/auth/authentication_modal.tsx
  frontend/javascripts/admin/auth/login_form.tsx
  frontend/javascripts/admin/auth/registration_form_generic.tsx
  frontend/javascripts/admin/auth/registration_form_wkorg.tsx
  frontend/javascripts/admin/auth/registration_view.tsx
  frontend/javascripts/admin/onboarding.tsx
  frontend/javascripts/components/pricing_enforcers.tsx
  frontend/javascripts/dashboard/publication_card.tsx
  frontend/javascripts/router.tsx
  frontend/stylesheets/_drawings.less
  frontend/stylesheets/_publications.less
  frontend/stylesheets/_utils.less
  frontend/stylesheets/_variables.less
  frontend/stylesheets/main.less
  public/images/background_mixed_cells_drawn.svg
  public/images/drawings/404.svg
  public/images/drawings/login.svg
  public/images/drawings/signup.svg
  public/images/drawings/upgrade-plan.svg
Labels: frontend, UX

#6961 Redesign "Welcome" toast
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/novel_user_experiences/welcome_toast.tsx
  frontend/stylesheets/main.less
  public/images/drawings/waving-person.svg
  public/images/logo-icon-only.svg
Labels: frontend, UX

#6977 If uploaded dataset needs conversion, tag user only after conversion success
  CHANGELOG.unreleased.md
  app/controllers/WKRemoteDataStoreController.scala
  app/models/job/Job.scala
  conf/webknossos.latest.routes
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
Labels: enhancement, backend, UX

#6980 Replace usercache by AlfuFoxCache
  app/WebKnossosModule.scala
  app/controllers/AnnotationIOController.scala
  app/controllers/TaskController.scala
  app/controllers/TimeController.scala
  app/models/annotation/AnnotationRestrictions.scala
  app/models/annotation/AnnotationService.scala
  app/models/annotation/handler/SavedTracingInformationHandler.scala
  app/models/project/Project.scala
  app/models/user/UserCache.scala
  app/models/user/UserService.scala
  app/models/user/time/TimeSpanService.scala
  app/oxalis/security/WebknossosBearerTokenAuthenticatorService.scala
  util/src/main/scala/com/scalableminds/util/cache/AlfuCache.scala
Labels: backend, refactoring

#6988 Discourage rest api use in docs
  docs/rest_api.md
Labels: backend, discussion, documentation

#6994 Added new drawings to job notification emails
  CHANGELOG.unreleased.md
  app/views/mail/jobFailedGeneric.scala.html
  app/views/mail/jobFailedUploadConvert.scala.html
  app/views/mail/jobSuccessfulGeneric.scala.html
  app/views/mail/jobSuccessfulSegmentation.scala.html
  app/views/mail/jobSuccessfulUploadConvert.scala.html
Labels: backend

#7003 Update screenshots scalebar positioning
  frontend/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  frontend/javascripts/test/screenshots/2017-05-31_mSEM_scMS109_bk_100um_v01-aniso.png
  frontend/javascripts/test/screenshots/Multi-Channel-Test.png
  frontend/javascripts/test/screenshots/ROI2017_wkw.png
  frontend/javascripts/test/screenshots/ROI2017_wkw_fallback.png
  frontend/javascripts/test/screenshots/ROI2017_wkw_with_mapping_astrocyte.png
  frontend/javascripts/test/screenshots/annotation_ROI2017_wkw_fallback_null.png
  frontend/javascripts/test/screenshots/annotation_ROI2017_wkw_fallback_segmentation.png
  frontend/javascripts/test/screenshots/connectome_file_test_dataset.png
  frontend/javascripts/test/screenshots/dsA_2.png
  frontend/javascripts/test/screenshots/float_test_dataset.png
  frontend/javascripts/test/screenshots/kiwi.png
  frontend/javascripts/test/screenshots/test-agglomerate-file_with_mapping_link.png
  frontend/javascripts/test/screenshots/test-agglomerate-file_with_meshes_link.png
Labels: CI

#6903 Store editable mappings in multiple fossildb columns+keys
  MIGRATIONS.unreleased.md
  app/models/annotation/AnnotationMutexService.scala
  conf/application.conf
  conf/messages
  fossildb/run.sh
  fossildb/version
  frontend/javascripts/oxalis/model/bucket_data_handling/wkstore_adapter.ts
  tools/migrate-editable-mappings/AgglomerateGraph_pb2.py
  tools/migrate-editable-mappings/EditableMappingInfo_pb2.py
  tools/migrate-editable-mappings/EditableMapping_pb2.py
  tools/migrate-editable-mappings/SegmentToAgglomerateProto_pb2.py
  tools/migrate-editable-mappings/fossildbapi_pb2.py
  tools/migrate-editable-mappings/fossildbapi_pb2_grpc.py
  tools/migrate-editable-mappings/geometry_pb2.py
  tools/migrate-editable-mappings/migrate-editable-mappings.py
  util/src/main/scala/com/scalableminds/util/cache/AlfuCache.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DSMeshController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/rpc/RPCRequest.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AccessTokenService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/AgglomerateService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteTracingstoreClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/proto/AgglomerateGraph.proto
  webknossos-datastore/proto/EditableMappingInfo.proto
  webknossos-datastore/proto/ListOfLong.proto
  webknossos-datastore/proto/SegmentToAgglomerateProto.proto
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TSRemoteDatastoreClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TSRemoteWebKnossosClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TracingDataStore.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMapping.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingUpdater.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/VersionedFossilDbIterator.scala
  webknossos-tracingstore/conf/com.scalableminds.webknossos.tracingstore.routes
Labels: backend, refactoring, performance

#7018 Guard against NaNs in shader
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/shaders/texture_access.glsl.ts
Labels: rendering, automerge

#7023 Add more error chaining to annotation download
  app/controllers/AnnotationIOController.scala
  conf/messages
Labels: backend, automerge

#7025 Fix download of public annotation, include access ctx in user cache key
  CHANGELOG.unreleased.md
  app/controllers/AnnotationIOController.scala
  app/models/user/UserService.scala
  util/src/main/scala/com/scalableminds/util/cache/AlfuCache.scala
Labels: bug, backend

#7002 Update docker compose commands + dev install readme
  DEV_INSTALL.md
  package.json
  start-docker.sh
Labels: infrastructure

#7034 Fix organization storage layouting
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/organization/organization_cards.tsx
Labels: frontend
