Repository scalableminds/webknossos, pull requests merged in 2023-02, with the labels that each got.

#6776 Enforce Pricing for Team Sharing
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/organization/organization_cards.tsx
  frontend/javascripts/admin/organization/organization_edit_view.tsx
  frontend/javascripts/admin/organization/pricing_plan_utils.ts
  frontend/javascripts/admin/organization/upgrade_plan_modal.tsx
  frontend/javascripts/components/pricing_enforcers.tsx
  frontend/javascripts/components/secured_route.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_sharing_tab.tsx
  frontend/javascripts/dashboard/dataset/team_selection_component.tsx
  frontend/javascripts/dashboard/dataset_view.tsx
  frontend/javascripts/dashboard/folders/folder_tree.tsx
  frontend/javascripts/messages.tsx
  frontend/javascripts/navbar.tsx
  frontend/javascripts/oxalis/model/accessors/tool_accessor.ts
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/toolbar_view.tsx
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/segments_tab/segments_view.tsx
  frontend/javascripts/router.tsx
  frontend/javascripts/types/api_flow_types.ts
Labels: frontend, automerge

#6805 Fix logo in Readme
  README.md
Labels: automerge

#6801 Release 23.02.0
  CHANGELOG.released.md
  CHANGELOG.unreleased.md
  MIGRATIONS.released.md
  MIGRATIONS.unreleased.md
Labels: automerge

#6802 Fix spacing
  frontend/javascripts/components/brain_spinner.tsx
  frontend/stylesheets/main.less
  frontend/stylesheets/trace_view/_status_bar.less
Labels: frontend

#6810 Fix some login problems
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/auth/login_form.tsx
  frontend/javascripts/admin/auth/registration_form.tsx
  frontend/javascripts/admin/auth/spotlight_registration_form.tsx
  frontend/javascripts/router.tsx
Labels: bug, frontend

#6816 Prevent Deactivating Organization Owner
  app/controllers/UserController.scala
  app/models/user/User.scala
  conf/messages
Labels: enhancement, backend

#6775 Access Google Cloud Storage via NIO
  CHANGELOG.unreleased.md
  app/controllers/CredentialController.scala
  app/models/binary/credential/CredentialDAO.scala
  app/models/binary/credential/CredentialService.scala
  app/models/binary/credential/CredentialType.scala
  app/models/binary/explore/ExploreRemoteLayerService.scala
  app/models/binary/explore/N5ArrayExplorer.scala
  app/models/binary/explore/N5MultiscalesExplorer.scala
  app/models/binary/explore/NgffExplorer.scala
  app/models/binary/explore/RemoteLayerExplorer.scala
  app/models/binary/explore/ZarrArrayExplorer.scala
  conf/META-INF/services/java.nio.file.spi.FileSystemProvider
  conf/evolutions/099-rename-credential-types.sql
  conf/evolutions/reversions/099-rename-credential-types.sql
  conf/messages
  conf/webknossos.latest.routes
  docs/datasets.md
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/dataset/dataset_add_neuroglancer_view.tsx
  frontend/javascripts/admin/dataset/dataset_add_zarr_view.tsx
  project/Dependencies.scala
  project/plugins.sbt
  tools/postgres/schema.sql
  util/src/main/scala/com/scalableminds/util/io/ZipIO.scala
  util/src/main/scala/com/scalableminds/util/tools/JsonHelper.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/MagLocator.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/n5/N5BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/FileSystemStore.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3FileSystem.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/s3fs/S3FileSystemProvider.java
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/FileSystemCredentials.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/FileSystemService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/FileSystemsHolder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpFileSystemProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsBasicAuthCredentials.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsFileSystem.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsFileSystemProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsPath.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsSeekableByteChannel.scala
  webknossos-datastore/conf/META-INF/services/java.nio.file.spi.FileSystemProvider
Labels: backend, frontend, new feature, refactoring

#6824 Fix error message when trying to join an orga you are already in
  app/models/user/UserService.scala
Labels: bug, backend

#6828 fixes loki log batching
  CHANGELOG.unreleased.md
  app/models/voxelytics/LokiClient.scala
Labels: automerge

#6830 Fix dbtool schema scheck stderr capturing
  app/Startup.scala
Labels: backend, infrastructure, refactoring

#6799 Fix editable text style
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/dataset/dataset_upload_view.tsx
  frontend/javascripts/components/text_with_description.tsx
  frontend/javascripts/libs/vector_input.tsx
  frontend/javascripts/oxalis/view/action-bar/dataset_position_view.tsx
  frontend/javascripts/oxalis/view/components/editable_text_label.tsx
  frontend/javascripts/oxalis/view/components/input_component.tsx
  frontend/javascripts/oxalis/view/components/markdown_modal.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/comment_tab/comment_tab_view.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/dataset_info_tab_view.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/segments_tab/segment_list_item.tsx
Labels: frontend

#6811 Add owner information to organization
  CHANGELOG.unreleased.md
  app/models/organization/OrganizationService.scala
  app/models/user/User.scala
  frontend/javascripts/admin/organization/organization_edit_view.tsx
  frontend/javascripts/admin/organization/pricing_plan_utils.ts
  frontend/javascripts/admin/organization/upgrade_plan_modal.tsx
  frontend/javascripts/components/pricing_enforcers.tsx
  frontend/javascripts/components/secured_route.tsx
  frontend/javascripts/messages.tsx
  frontend/javascripts/oxalis/constants.ts
  frontend/javascripts/oxalis/model/accessors/tool_accessor.ts
  frontend/javascripts/oxalis/view/right-border-tabs/segments_tab/segments_view.tsx
  frontend/javascripts/types/api_flow_types.ts
Labels: backend, frontend

#6716 Explore and view Neuroglancer Precomputed image volumes
  CHANGELOG.unreleased.md
  app/models/binary/explore/ExploreRemoteLayerService.scala
  app/models/binary/explore/PrecomputedExplorer.scala
  conf/application.conf
  docs/datasets.md
  frontend/javascripts/admin/dataset/dataset_add_view.tsx
  frontend/javascripts/admin/dataset/dataset_add_zarr_view.tsx
  frontend/javascripts/types/schemas/datasource.schema.ts
  frontend/javascripts/types/schemas/datasource.types.ts
  package.json
  util/src/main/scala/com/scalableminds/util/geometry/BoundingBox.scala
  util/src/main/scala/com/scalableminds/util/geometry/Vec3Double.scala
  util/src/main/scala/com/scalableminds/util/geometry/Vec3Int.scala
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/precomputed/PrecomputedBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/precomputed/PrecomputedDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/ChunkReader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/Compressor.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/DatasetArray.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/DatasetHeader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/DimensionSeparator.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/precomputed/PrecomputedArray.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/precomputed/PrecomputedChunkReader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/precomputed/PrecomputedCompressorFactory.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/precomputed/PrecomputedDataType.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/precomputed/PrecomputedHeader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsPath.scala
Labels: backend, new feature

#6832 Mark owner in user list
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/user/user_list_view.tsx
Labels: frontend

#6813 Add mesh actions to 3d viewport context menu
  CHANGELOG.unreleased.md
  docs/mesh_visualization.md
  docs/proof_reading.md
  frontend/javascripts/admin/dataset/dataset_add_boss_view.tsx
  frontend/javascripts/admin/dataset/dataset_add_neuroglancer_view.tsx
  frontend/javascripts/admin/dataset/dataset_add_view.tsx
  frontend/javascripts/admin/dataset/dataset_add_zarr_view.tsx
  frontend/javascripts/admin/dataset/dataset_upload_view.tsx
  frontend/javascripts/libs/utils.ts
  frontend/javascripts/oxalis/constants.ts
  frontend/javascripts/oxalis/controller/combinations/skeleton_handlers.ts
  frontend/javascripts/oxalis/controller/td_controller.tsx
  frontend/javascripts/oxalis/view/context_menu.tsx
  frontend/javascripts/oxalis/view/layouting/tracing_layout_view.tsx
  frontend/javascripts/oxalis/view/plane_view.ts
Labels: enhancement, frontend, mesh

#6839 Remove <Textarea> from <InputComponent>
  CHANGELOG.unreleased.md
  frontend/javascripts/dashboard/advanced_dataset/dataset_table.tsx
  frontend/javascripts/libs/vector_input.tsx
  frontend/javascripts/oxalis/view/action-bar/dataset_position_view.tsx
  frontend/javascripts/oxalis/view/components/editable_text_icon.tsx
  frontend/javascripts/oxalis/view/components/input_component.tsx
  frontend/javascripts/oxalis/view/components/markdown_modal.tsx
  frontend/javascripts/oxalis/view/components/setting_input_views.tsx
  frontend/javascripts/oxalis/view/context_menu.tsx
  frontend/javascripts/oxalis/view/left-border-tabs/layer_settings_tab.tsx
  frontend/javascripts/oxalis/view/left-border-tabs/modals/add_volume_layer_modal.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/skeleton_tab_view.tsx
Labels: frontend

#6840 Add TS types for search inputs
  frontend/javascripts/admin/job/job_list_view.tsx
  frontend/javascripts/admin/project/project_list_view.tsx
  frontend/javascripts/admin/scripts/script_list_view.tsx
  frontend/javascripts/admin/task/task_list_view.tsx
  frontend/javascripts/admin/team/team_list_view.tsx
  frontend/javascripts/admin/user/user_list_view.tsx
  frontend/javascripts/dashboard/explorative_annotations_view.tsx
  frontend/javascripts/dashboard/publication_view.tsx
  frontend/javascripts/oxalis/view/action-bar/merge_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/user_scripts_modal_view.tsx
  frontend/javascripts/oxalis/view/components/setting_input_views.tsx
Labels: frontend

#6825 PR Template: edge cases
  .github/PULL_REQUEST_TEMPLATE.md
  .github/common_edge_cases.md
Labels: discussion, infrastructure

#6847 Readable error message if team name is taken, even if other team is deleted
  app/models/team/Team.scala
Labels: bug, backend

#6845 adds URL to help email
  app/controllers/Application.scala
  app/oxalis/mail/DefaultMails.scala
  app/views/mail/help.scala.html
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/oxalis/view/help_modal.tsx
Labels: automerge

#6837 Minor styling for Voxelytics reports
  frontend/javascripts/admin/voxelytics/task_list_view.tsx
  frontend/stylesheets/main.less
Labels: automerge

#6850 In test db, replace e2006_knossos by l4_sample
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  test/db/dataSet_layers.csv
  test/db/dataSet_resolutions.csv
  test/db/dataSets.csv
Labels: backend, testing, automerge

#6852 adds CORS headers to publication routes
  app/controllers/PublicationController.scala
Labels: automerge

#6844 Update style of login, signup views
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/auth/change_password_view.tsx
  frontend/javascripts/admin/auth/finish_reset_password_view.tsx
  frontend/javascripts/admin/auth/login_view.tsx
  frontend/javascripts/admin/auth/registration_view.tsx
  frontend/javascripts/admin/auth/start_reset_password_view.tsx
  frontend/stylesheets/_variables.less
  frontend/stylesheets/main.less
  frontend/stylesheets/trace_view/_tracing_view.less
  public/images/background_neurons_drawn.svg
Labels: frontend

#6849 Replace MomentJs with Dayjs
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/dataset/dataset_upload_view.tsx
  frontend/javascripts/admin/organization/organization_cards.tsx
  frontend/javascripts/admin/organization/upgrade_plan_modal.tsx
  frontend/javascripts/admin/statistic/statistic_view.tsx
  frontend/javascripts/admin/time/time_line_chart_view.tsx
  frontend/javascripts/admin/time/time_line_view.tsx
  frontend/javascripts/admin/user/user_list_view.tsx
  frontend/javascripts/admin/voxelytics/statistics_tab.tsx
  frontend/javascripts/admin/voxelytics/task_list_view.tsx
  frontend/javascripts/components/formatted_date.tsx
  frontend/javascripts/components/terms_of_services_check.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_view.tsx
  frontend/javascripts/dashboard/dataset_view.tsx
  frontend/javascripts/libs/format_utils.ts
  frontend/javascripts/oxalis/view/action-bar/private_links_view.tsx
  frontend/javascripts/oxalis/view/version_list.tsx
  frontend/javascripts/test/backend-snapshot-tests/timetracking.e2e.ts
  package.json
  yarn.lock
Labels: frontend

#6859 Fix sql migration links in migration guide
  MIGRATIONS.released.md
Labels: bug, infrastructure

#6863 Fix exploring datasets via http (without s)
  app/models/binary/credential/CredentialService.scala
  frontend/javascripts/admin/dataset/dataset_add_zarr_view.tsx
Labels: bug, backend

#6866 Fix basicauth for exploring remote http datasets
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsFileSystemProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsSeekableByteChannel.scala
Labels: bug, backend

#6834 Remove legacy datasets tab and use new compact route
  CHANGELOG.unreleased.md
  app/controllers/AnnotationController.scala
  app/controllers/DataSetController.scala
  app/controllers/LegacyApiController.scala
  app/models/annotation/AnnotationService.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/dataset/dataset_add_zarr_view.tsx
  frontend/javascripts/components/error_boundary.tsx
  frontend/javascripts/dashboard/advanced_dataset/dataset_action_view.tsx
  frontend/javascripts/dashboard/advanced_dataset/dataset_table.tsx
  frontend/javascripts/dashboard/dashboard_contexts.ts
  frontend/javascripts/dashboard/dashboard_view.tsx
  frontend/javascripts/dashboard/dataset/dataset_cache_provider.tsx
  frontend/javascripts/dashboard/dataset/dataset_collection_context.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_delete_tab.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_view.tsx
  frontend/javascripts/dashboard/dataset/queries.tsx
  frontend/javascripts/dashboard/dataset_folder_view.tsx
  frontend/javascripts/dashboard/dataset_view.tsx
  frontend/javascripts/dashboard/folders/details_sidebar.tsx
  frontend/javascripts/dashboard/folders/folder_tree.tsx
  frontend/javascripts/main.tsx
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.tsx
  frontend/javascripts/oxalis/view/action_bar_view.tsx
  frontend/javascripts/router.tsx
  frontend/javascripts/test/backend-snapshot-tests/annotations.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/datasets.e2e.ts
  frontend/javascripts/test/puppeteer/dataset_rendering_helpers.ts
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  frontend/javascripts/types/api_flow_types.ts
  util/src/main/scala/com/scalableminds/util/tools/TristateOptionJsonHelper.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/annotation/AnnotationLayer.scala
Labels: enhancement, backend, frontend, refactoring, performance

#6864 Fix style of connectome tab by restricting directory tree style
  CHANGELOG.unreleased.md
  frontend/stylesheets/antd_overwrites.less
Labels: automerge

#6867 Ensure that segments are added to segment list when using quick select...
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/sagas/quick_select_saga.ts
  frontend/javascripts/oxalis/model/sagas/volumetracing_saga.tsx
Labels: frontend

#6853 Add functions to get and set segment colors to the frontend API
  CHANGELOG.unreleased.md
  frontend/javascripts/libs/utils.ts
  frontend/javascripts/oxalis/api/api_latest.ts
  frontend/javascripts/oxalis/controller/combinations/tool_controls.ts
  frontend/javascripts/oxalis/controller/scene_controller.ts
  frontend/javascripts/oxalis/model/accessors/volumetracing_accessor.ts
  frontend/javascripts/oxalis/shaders/segmentation.glsl.ts
  frontend/javascripts/oxalis/view/action-bar/toolbar_view.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/segments_tab/segment_list_item.tsx
Labels: automerge

#6860 Update deprecated antd <Menu>
  CHANGELOG.unreleased.md
  frontend/javascripts/components/pricing_enforcers.tsx
  frontend/javascripts/dashboard/folders/folder_tree.tsx
  frontend/javascripts/navbar.tsx
  frontend/stylesheets/antd_overwrites.less
Labels: frontend

#6819 Annotation Locking Mechanism
  CHANGELOG.unreleased.md
  app/WebKnossosModule.scala
  app/controllers/AnnotationController.scala
  app/models/annotation/AnnotationMutexService.scala
  app/models/annotation/AnnotationService.scala
  app/oxalis/telemetry/SlackNotificationService.scala
  app/utils/WkConf.scala
  conf/application.conf
  conf/evolutions/100-annotation-mutexes.sql
  conf/evolutions/reversions/100-annotation-mutexes.sql
  conf/webknossos.latest.routes
  docs/sharing.md
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/messages.tsx
  frontend/javascripts/navbar.tsx
  frontend/javascripts/oxalis/default_state.ts
  frontend/javascripts/oxalis/model/actions/annotation_actions.ts
  frontend/javascripts/oxalis/model/reducers/annotation_reducer.ts
  frontend/javascripts/oxalis/model/reducers/reducer_helpers.ts
  frontend/javascripts/oxalis/model/sagas/annotation_saga.tsx
  frontend/javascripts/oxalis/model/sagas/save_saga.ts
  frontend/javascripts/oxalis/store.ts
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.tsx
  frontend/javascripts/test/sagas/annotation_saga.spec.ts
  package.json
  tools/postgres/schema.sql
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/Application.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
  yarn.lock
Labels: enhancement, backend, frontend

#6870 Add link to imprint and privacy to help menu
  frontend/javascripts/navbar.tsx
Labels: bug, frontend

#6871 Add evolutions 99,100 to migration guide
  MIGRATIONS.unreleased.md
Labels: infrastructure

#6874 Followups for OME-TIFF export
  CHANGELOG.unreleased.md
  app/controllers/JobsController.scala
  app/models/job/Job.scala
  conf/messages
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/oxalis/view/action-bar/download_modal_view.tsx
  test/backend/MathTestSuite.scala
  util/src/main/scala/com/scalableminds/util/geometry/BoundingBox.scala
  util/src/main/scala/com/scalableminds/util/geometry/Vec3Int.scala
  util/src/main/scala/com/scalableminds/util/tools/Math.scala
Labels: automerge

#6876 Fix superUser being wrongly marked as organization owners
  app/models/user/UserService.scala
Labels: bug, backend

#6879 adds dedicated explore method for zarr datasets with a datasource-properties.json
  CHANGELOG.unreleased.md
  app/models/binary/explore/ExploreRemoteLayerService.scala
  app/models/binary/explore/WebknossosZarrExplorer.scala
  docs/datasets.md
  frontend/javascripts/admin/dataset/dataset_add_view.tsx
Labels: automerge
