Repository scalableminds/webknossos, pull requests merged in 2023-01, with the labels that each got.

#6602 Add Pricing Plans to Organization Page
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/AuthenticationController.scala
  app/controllers/InitialDataController.scala
  app/controllers/OrganizationController.scala
  app/models/organization/Organization.scala
  app/models/organization/OrganizationService.scala
  app/models/team/PricingPlan.scala
  app/models/user/User.scala
  app/oxalis/mail/DefaultMails.scala
  app/views/mail/extendPricingPlan.scala.html
  app/views/mail/upgradePricingPlanRequest.scala.html
  app/views/mail/upgradePricingPlanStorage.scala.html
  app/views/mail/upgradePricingPlanToPower.scala.html
  app/views/mail/upgradePricingPlanToTeam.scala.html
  app/views/mail/upgradePricingPlanUsers.scala.html
  conf/evolutions/094-pricing-plans.sql
  conf/evolutions/reversions/094-pricing-plans.sql
  conf/messages
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/onboarding.tsx
  frontend/javascripts/admin/organization/organization_cards.tsx
  frontend/javascripts/admin/organization/organization_edit_view.tsx
  frontend/javascripts/admin/organization/pricing_plan_utils.ts
  frontend/javascripts/admin/organization/upgrade_plan_modal.tsx
  frontend/javascripts/admin/time/time_line_view.tsx
  frontend/javascripts/admin/user/user_list_view.tsx
  frontend/javascripts/admin/welcome_ui.tsx
  frontend/javascripts/dashboard/dashboard_view.tsx
  frontend/javascripts/libs/utils.ts
  frontend/javascripts/messages.tsx
  frontend/javascripts/navbar.tsx
  frontend/javascripts/oxalis/constants.ts
  frontend/javascripts/oxalis/view/right-border-tabs/connectome_tab/connectome_settings.tsx
  frontend/javascripts/router.tsx
  frontend/javascripts/types/api_flow_types.ts
  public/images/background_neuron_meshes.webp
  public/images/pricing/background_evaluation.jpeg
  public/images/pricing/background_neuron_analysis.svg
  public/images/pricing/background_neuron_meshes.jpeg
  public/images/pricing/background_neurons.jpeg
  public/images/pricing/background_users.jpeg
  test/db/organizations.csv
  tools/postgres/schema.sql
  util/src/main/scala/com/scalableminds/util/time/Instant.scala
Labels: backend, frontend

#6728 Add explicit name for foreign-key constraint to fix false positives in diff schema
  MIGRATIONS.unreleased.md
  conf/evolutions/095-constraint-naming.sql
  conf/evolutions/reversions/095-constraint-naming.sql
  tools/postgres/schema.sql
Labels: backend, refactoring

#6720 Allow deleting datasets that do not exist on disk
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/DataSetDeleter.scala
Labels: bug, backend

#6719 Allow deactivated users to switch organization
  CHANGELOG.unreleased.md
  app/models/user/User.scala
  app/models/user/UserService.scala
Labels: bug, backend

#6685 Measure used disk storage
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/WebKnossosModule.scala
  app/controllers/DataSetController.scala
  app/controllers/WKRemoteDataStoreController.scala
  app/models/binary/DataSetService.scala
  app/models/binary/DataStore.scala
  app/models/binary/WKRemoteDataStoreClient.scala
  app/models/organization/Organization.scala
  app/models/organization/OrganizationService.scala
  app/models/storage/UsedStorageService.scala
  app/utils/WkConf.scala
  app/utils/sql/SQLHelpers.scala
  conf/application.conf
  conf/evolutions/096-storage.sql
  conf/evolutions/reversions/096-storage.sql
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/organization/organization_cards.tsx
  frontend/javascripts/admin/organization/organization_edit_view.tsx
  frontend/javascripts/admin/organization/pricing_plan_utils.ts
  frontend/javascripts/dashboard/dashboard_view.tsx
  frontend/javascripts/types/api_flow_types.ts
  test/db/dataStores.csv
  test/db/organizations.csv
  tools/postgres/schema.sql
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreConfig.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSUsedStorageService.scala
  webknossos-datastore/conf/com.scalableminds.webknossos.datastore.routes
  webknossos-datastore/conf/standalone-datastore.conf
Labels: backend, new feature

#6723 Use new sql interpolator in more DAOs, clean up
  app/Startup.scala
  app/WebKnossosModule.scala
  app/controllers/Application.scala
  app/controllers/MaintenanceController.scala
  app/controllers/ReportController.scala
  app/models/annotation/Annotation.scala
  app/models/annotation/AnnotationPrivateLink.scala
  app/models/annotation/TracingStore.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataStore.scala
  app/models/binary/Publication.scala
  app/models/folder/Folder.scala
  app/models/job/Job.scala
  app/models/job/Worker.scala
  app/models/mesh/Mesh.scala
  app/models/organization/Organization.scala
  app/models/project/Project.scala
  app/models/shortlinks/ShortLink.scala
  app/models/task/Script.scala
  app/models/task/Task.scala
  app/models/task/TaskType.scala
  app/models/team/Team.scala
  app/models/user/Invite.scala
  app/models/user/MultiUser.scala
  app/models/user/User.scala
  app/models/user/time/TimeSpan.scala
  app/models/voxelytics/VoxelyticsDAO.scala
  app/oxalis/security/Token.scala
  app/utils/sql/SQLDAO.scala
  app/utils/sql/SQLHelpers.scala
  app/utils/sql/SecuredSQLDAO.scala
  app/utils/sql/SimpleSQLDAO.scala
  app/utils/sql/SqlClient.scala
  app/utils/sql/SqlEscaping.scala
  app/utils/sql/SqlInterpolation.scala
  app/utils/sql/SqlTypeImplicits.scala
  test/backend/SqlInterpolationTestSuite.scala
Labels: backend, refactoring

#6735 Verbose error logging for storage scan failures, avoid getting stuck
  app/models/organization/Organization.scala
  app/models/storage/UsedStorageService.scala
  app/utils/WkConf.scala
  conf/application.conf
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
Labels: bug, backend

#6741 fix sql query in timespan.findAll
  app/models/user/time/TimeSpan.scala
Labels: bug, backend

#6744 Do not fail storage scan if orga directory does not exist
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSUsedStorageService.scala
Labels: bug, backend

#6746 Include wkw file path when logging java internal error
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
Labels: enhancement, backend

#6745 Purge last usages of SqlToken.raw with user input
  app/models/binary/DataSet.scala
  app/models/user/MultiUser.scala
  app/oxalis/security/Token.scala
  app/utils/sql/SqlInterpolation.scala
  test/backend/SqlInterpolationTestSuite.scala
Labels: backend, refactoring

#6646 Store remote dataset credentials separately
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/CredentialController.scala
  app/controllers/DataSetController.scala
  app/controllers/WKRemoteDataStoreController.scala
  app/models/binary/credential/CredentialDAO.scala
  app/models/binary/credential/CredentialService.scala
  app/models/binary/credential/CredentialType.scala
  app/models/binary/explore/ExploreRemoteLayerService.scala
  app/models/binary/explore/N5ArrayExplorer.scala
  app/models/binary/explore/N5MultiscalesExplorer.scala
  app/models/binary/explore/NgffExplorer.scala
  app/models/binary/explore/RemoteLayerExplorer.scala
  app/models/binary/explore/ZarrArrayExplorer.scala
  conf/evolutions/097-credentials.sql
  conf/evolutions/reversions/097-credentials.sql
  conf/webknossos.latest.routes
  tools/postgres/schema.sql
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/ZarrStreamingController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/MagLocator.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/n5/N5BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/n5/N5DataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/wkw/WKWDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrBucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/zarr/ZarrDataLayers.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/datasource/DataLayer.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataServiceHolder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/BucketProviderCache.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/FileSystemCredentials.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/FileSystemService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingZarrStreamingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: automerge

#6749 Adapt color of multiuser switch indicator
  frontend/javascripts/navbar.tsx
  frontend/stylesheets/main.less
Labels: frontend

#6732 Vx followup
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  app/controllers/VoxelyticsController.scala
  app/models/binary/explore/N5MultiscalesExplorer.scala
  app/models/voxelytics/VoxelyticsDAO.scala
  app/models/voxelytics/VoxelyticsService.scala
  app/utils/sql/SqlInterpolation.scala
  app/utils/sql/SqlTypeImplicits.scala
  conf/evolutions/098-voxelytics-states.sql
  conf/evolutions/reversions/098-voxelytics-states.sql
  conf/webknossos.latest.routes
  frontend/javascripts/admin/admin_rest_api.ts
  frontend/javascripts/admin/voxelytics/artifacts_view.tsx
  frontend/javascripts/admin/voxelytics/log_tab.tsx
  frontend/javascripts/admin/voxelytics/statistics_tab.tsx
  frontend/javascripts/admin/voxelytics/task_list_view.tsx
  frontend/javascripts/admin/voxelytics/task_view.tsx
  frontend/javascripts/admin/voxelytics/utils.ts
  frontend/javascripts/admin/voxelytics/workflow_list_view.tsx
  frontend/javascripts/admin/voxelytics/workflow_view.tsx
  frontend/javascripts/libs/format_utils.ts
  frontend/javascripts/types/api_flow_types.ts
  frontend/stylesheets/antd_overwrites.less
  package.json
  test/backend/SqlInterpolationTestSuite.scala
  tools/postgres/schema.sql
Labels: automerge

#6754 Fix font import
  frontend/stylesheets/main.less
Labels: automerge

#6756 Fix superuser organization switching
  app/models/user/UserService.scala
  util/src/main/scala/com/scalableminds/util/requestlogging/RequestLogging.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/BinaryDataController.scala
Labels: bug, backend

#6762 minor logo fix
  public/images/favicon.png
  public/images/icon-only.svg
Labels: automerge

#6760 Adapt viewport and crosshair colors to new color scheme
  app/controllers/InitialDataController.scala
  frontend/javascripts/libs/format_utils.ts
  frontend/javascripts/oxalis/constants.ts
  frontend/javascripts/test/screenshots/2017-05-31_mSEM_aniso-test.png
  frontend/javascripts/test/screenshots/2017-05-31_mSEM_scMS109_bk_100um_v01-aniso.png
  frontend/javascripts/test/screenshots/Multi-Channel-Test.png
  frontend/javascripts/test/screenshots/ROI2017_wkw.png
  frontend/javascripts/test/screenshots/ROI2017_wkw_fallback.png
  frontend/javascripts/test/screenshots/ROI2017_wkw_with_mapping_astrocyte.png
  frontend/javascripts/test/screenshots/annotation_ROI2017_wkw_fallback_null.png
  frontend/javascripts/test/screenshots/annotation_ROI2017_wkw_fallback_segmentation.png
  frontend/javascripts/test/screenshots/connectome_file_test_dataset.png
  frontend/javascripts/test/screenshots/dsA_2.png
  frontend/javascripts/test/screenshots/float_test_dataset.png
  frontend/javascripts/test/screenshots/test-agglomerate-file_with_mapping_link.png
  frontend/javascripts/test/screenshots/test-agglomerate-file_with_meshes_link.png
  frontend/stylesheets/_variables.less
  public/images/logo.svg
Labels: automerge

#6763 Make voxelytics sql queries compatible with postgres 10
  app/models/voxelytics/VoxelyticsDAO.scala
Labels: bug, backend

#6764 Fix exploring remote datasets with no credentials
  CHANGELOG.unreleased.md
  app/models/binary/credential/CredentialService.scala
  app/models/binary/explore/ExploreRemoteLayerService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/FileSystemsHolder.scala
Labels: bug, backend

#6765 Fix antd deprecation warning for <Modal open/visible>
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/auth/accept_invite_view.tsx
  frontend/javascripts/admin/auth/authentication_modal.tsx
  frontend/javascripts/admin/dataset/dataset_add_zarr_view.tsx
  frontend/javascripts/admin/dataset/dataset_upload_view.tsx
  frontend/javascripts/admin/onboarding.tsx
  frontend/javascripts/admin/project/transfer_all_tasks_modal.tsx
  frontend/javascripts/admin/task/task_annotation_view.tsx
  frontend/javascripts/admin/task/task_list_view.tsx
  frontend/javascripts/admin/team/create_team_modal_view.tsx
  frontend/javascripts/admin/team/team_list_view.tsx
  frontend/javascripts/admin/user/experience_modal_view.tsx
  frontend/javascripts/admin/user/permissions_and_teams_modal_view.tsx
  frontend/javascripts/admin/user/user_list_view.tsx
  frontend/javascripts/dashboard/dashboard_task_list_view.tsx
  frontend/javascripts/dashboard/transfer_task_modal.tsx
  frontend/javascripts/libs/react_helpers.tsx
  frontend/javascripts/oxalis/view/action-bar/add_new_layout_modal.tsx
  frontend/javascripts/oxalis/view/action-bar/download_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/merge_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/private_links_view.tsx
  frontend/javascripts/oxalis/view/action-bar/python_client_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/share_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/share_view_dataset_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.tsx
  frontend/javascripts/oxalis/view/action-bar/user_scripts_modal_view.tsx
  frontend/javascripts/oxalis/view/action-bar/view_dataset_actions_view.tsx
  frontend/javascripts/oxalis/view/action_bar_view.tsx
  frontend/javascripts/oxalis/view/components/editable_text_label.tsx
  frontend/javascripts/oxalis/view/components/markdown_modal.tsx
  frontend/javascripts/oxalis/view/new_task_description_modal.tsx
  frontend/javascripts/oxalis/view/recommended_configuration_modal.tsx
  frontend/javascripts/oxalis/view/remove_tree_modal.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/comment_tab/comment_tab_view.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/skeleton_tab_view.tsx
Labels: frontend, automerge

#6761 When re-activating user, check orga user limit
  app/controllers/AuthenticationController.scala
  app/controllers/UserController.scala
  app/models/organization/OrganizationService.scala
Labels: bug, backend

#6771 Fix loading meshes that were pre-computed for a specific mapping
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/sagas/isosurface_saga.ts
Labels: bug, frontend

#6767 Enforce Pricing for Task/Project Management Features
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/dataset/dataset_upload_view.tsx
  frontend/javascripts/admin/onboarding.tsx
  frontend/javascripts/admin/organization/organization_edit_view.tsx
  frontend/javascripts/admin/organization/pricing_plan_utils.ts
  frontend/javascripts/admin/user/user_list_view.tsx
  frontend/javascripts/components/pricing_enforcers.tsx
  frontend/javascripts/components/secured_route.tsx
  frontend/javascripts/dashboard/dashboard_view.tsx
  frontend/javascripts/dashboard/dataset_view.tsx
  frontend/javascripts/dashboard/folders/folder_tree.tsx
  frontend/javascripts/main.tsx
  frontend/javascripts/messages.tsx
  frontend/javascripts/navbar.tsx
  frontend/javascripts/oxalis/default_state.ts
  frontend/javascripts/oxalis/model/accessors/organization_accessors.ts
  frontend/javascripts/oxalis/model/actions/actions.ts
  frontend/javascripts/oxalis/model/actions/organization_actions.ts
  frontend/javascripts/oxalis/model/reducers/organization_reducer.ts
  frontend/javascripts/oxalis/store.ts
  frontend/javascripts/oxalis/view/right-border-tabs/dataset_info_tab_view.tsx
  frontend/javascripts/router.tsx
Labels: frontend, automerge

#6778 Fix direct task assignment query
  CHANGELOG.unreleased.md
  app/models/task/Task.scala
Labels: bug, backend

#6759 Speed Up Dataset List Request
  CHANGELOG.unreleased.md
  app/controllers/DataSetController.scala
  app/models/annotation/Annotation.scala
  app/models/binary/DataSet.scala
  app/models/binary/DataSetService.scala
  app/models/folder/Folder.scala
  app/models/organization/Organization.scala
  conf/webknossos.latest.routes
  docs/rest_api.md
  util/src/main/scala/com/scalableminds/util/tools/JsonHelper.scala
Labels: backend, performance

#6783 Remove debug logging in editable mapping logic
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMapping.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
Labels: backend, refactoring

#6782 Catch zero-sized buckets in backend, fix http nio timeout handling
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/httpsfilesystem/HttpsSeekableByteChannel.scala
Labels: bug, backend

#6784 Fix publicly shared annotations
  CHANGELOG.unreleased.md
  frontend/javascripts/components/secured_route.tsx
Labels: bug, frontend, automerge

#6792 adds "Ok" to health check
  app/controllers/Application.scala
Labels: automerge

#6794 Fix datastore file system watcher
  conf/application.conf
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataSourceService.scala
  webknossos-datastore/conf/standalone-datastore.conf
Labels: bug, backend
