Repository scalableminds/webknossos, pull requests merged in 2025-04, with the labels that each got.

#8484 clean up spire usages
  test/backend/Zarr3TestSuite.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DataConverter.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/AgglomerateFileCache.scala
Labels: backend, refactoring

#8486 Fix redundant newer-version-on-server toast
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/sagas/save_saga.ts
Labels: bug, frontend

#8487 Format credits on orga page
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/organization/organization_cards.tsx
Labels: bug, frontend

#8474 Fix ai model list's alignment of items in actions column
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/voxelytics/ai_model_list_view.tsx
Labels: frontend, css

#8460 Improve volume and segment index performance
  .editorconfig
  CHANGELOG.unreleased.md
  MIGRATIONS.unreleased.md
  docker-compose.yml
  fossildb/version
  tools/proxy/proxy.js
  util/src/main/scala/com/scalableminds/util/tools/BoxImplicits.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/NativeBucketScanner.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/SegmentStatistics.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/SegmentIndexFileService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/TemporaryStore.scala
  webknossos-datastore/proto/fossildbapi.proto
  webknossos-jni/src/.clang-format
  webknossos-jni/src/bucketScanner.cpp
  webknossos-jni/src/dracoToStlDecoder.cpp
  webknossos-jni/src/include/com_scalableminds_webknossos_datastore_helpers_NativeBucketScanner.h
  webknossos-jni/src/include/jniutils.h
  webknossos-jni/src/jniutils.cpp
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TSRemoteDatastoreClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/annotation/TSAnnotationService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/EditableMappingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/controllers/VolumeTracingZarrStreamingController.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/RemoteFallbackLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/TemporaryTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingMergeService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/TSFullMeshService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeBucketBuffer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeSegmentIndexBuffer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeSegmentIndexService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeSegmentStatisticsService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingBucketHelper.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeUpdateActions.scala
Labels: backend, refactoring, performance

#8494 Avoid white flash on page reload in dark theme
  app/views/main.scala.html
  project/license.sbt
Labels: bug, enhancement, backend, frontend, css

#8500 Add stdint include to bucketscanner to fix build system compatibility
  webknossos-jni/src/bucketScanner.cpp
Labels: bug, backend

#8488 If a split action doesn’t actually split the agglomerate, skip no-op steps
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingUpdater.scala
Labels: backend, refactoring, performance

#8498 Restructure list annotations query to guide Postgres to a more efficient query plan
  CHANGELOG.unreleased.md
  app/models/annotation/Annotation.scala
Labels: bug, backend, performance

#8482 Use FossilDBPutBuffer for more efficient saving of multiple fossil keys
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/annotation/TSAnnotationService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBClient.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBPutBuffer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingMergeService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingUpdater.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/SkeletonTracingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingBucketHelper.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: backend, performance

#8489 Use native bucket scanner also in EditableMappingService
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/NativeBucketScanner.scala
  webknossos-jni/src/bucketScanner.cpp
  webknossos-jni/src/include/com_scalableminds_webknossos_datastore_helpers_NativeBucketScanner.h
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeSegmentIndexService.scala
Labels: backend, performance

#8443 Allow to change individual mesh opacity
  CHANGELOG.unreleased.md
  docs/volume_annotation/segments_list.md
  frontend/javascripts/components/color_picker.tsx
  frontend/javascripts/oxalis/constants.ts
  frontend/javascripts/oxalis/controller/segment_mesh_controller.ts
  frontend/javascripts/oxalis/model/accessors/volumetracing_accessor.ts
  frontend/javascripts/oxalis/model/actions/annotation_actions.ts
  frontend/javascripts/oxalis/model/reducers/annotation_reducer.ts
  frontend/javascripts/oxalis/model/sagas/mesh_saga.ts
  frontend/javascripts/oxalis/store.ts
  frontend/javascripts/oxalis/view/right-border-tabs/segments_tab/segment_list_item.tsx
  frontend/javascripts/oxalis/view/right-border-tabs/segments_tab/segments_view.tsx
Labels: frontend

#8503 Don't allow find_largest_segment_id on layer whose category is saved as color in backend
  CHANGELOG.unreleased.md
  frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx
Labels: bug, frontend

#8469 Use multi-get; native bucket scanner in segment stats computation
  CHANGELOG.unreleased.md
  util/src/main/scala/com/scalableminds/util/tools/Fox.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreModule.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/dataformats/BucketProvider.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/NativeBucketScanner.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/helpers/SegmentStatistics.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/requests/DataServiceRequests.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataServiceHolder.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DatasetErrorLoggingService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/SegmentIndexFileService.scala
  webknossos-jni/src/bucketScanner.cpp
  webknossos-jni/src/include/com_scalableminds_webknossos_datastore_helpers_NativeBucketScanner.h
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/TracingStoreModule.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/editablemapping/EditableMappingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/TSDatasetErrorLoggingService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeSegmentStatisticsService.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingLayer.scala
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/volume/VolumeTracingService.scala
Labels: backend, refactoring, performance

#8510 Fix typo when writing zarr header: dimension_separator
  CHANGELOG.unreleased.md
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/datareaders/zarr/ZarrHeader.scala
Labels: bug, backend

#8507 Bump backend dependencies, run codespell
  .codespellrc
  CHANGELOG.unreleased.md
  build.sbt
  frontend/javascripts/admin/api/jobs.ts
  frontend/javascripts/oxalis/shaders/utils.glsl.ts
  project/Dependencies.scala
  project/build.properties
  project/plugins.sbt
  tools/postgres/schema.sql
Labels: enhancement, backend, refactoring

#8509 Global Data Vault Credentials in Datastore Config
  CHANGELOG.unreleased.md
  app/controllers/CredentialController.scala
  app/models/dataset/credential/CredentialDAO.scala
  app/models/dataset/credential/CredentialService.scala
  app/models/dataset/explore/WKExploreRemoteLayerService.scala
  conf/application.conf
  test/backend/DataVaultTestSuite.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreConfig.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/DataStoreModule.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/CredentialConfigReader.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/CredentialType.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/DataVaultCredentials.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/RemoteSourceDescriptorService.scala
  webknossos-datastore/conf/standalone-datastore.conf
Labels: enhancement, backend

#8513 Fix concurrency bug in skeleton saving
  CHANGELOG.unreleased.md
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/skeleton/SkeletonTracingService.scala
Labels: bug, backend

#8476 Make manual `reserveManualUpload` route return `datasetId` and `directoryName`
  CHANGELOG.unreleased.md
  app/controllers/WKRemoteDataStoreController.scala
  app/models/dataset/DatasetService.scala
  conf/messages
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/controllers/DataSourceController.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/uploading/ComposeService.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/uploading/UploadService.scala
Labels: enhancement, backend

#8147 Convert CircleCI config to Github Actions
  .circleci/config.yml
  .circleci/not-on-master.sh
  .circleci/slack-notification.sh
  .github/Dockerfile.datastore
  .github/Dockerfile.tracingstore
  .github/Dockerfile.webknossos
  .github/actions/retry/action.yml
  .github/docker-compose.yml
  .github/slack-notification.sh
  .github/workflows/build_test_deploy.yml
  CHANGELOG.unreleased.md
  Dockerfile.dev
  docker-compose.yml
  project/BuildInfoSettings.scala
  start-docker.sh
  webknossos-jni/src/bucketScanner.cpp
  yarn.lock
Labels: CI

#8530 Switch CI to ubuntu 22.04 for now to match docker image
  .github/workflows/build_test_deploy.yml
Labels: bug, CI

#8515 more informative logging in wk remote tracingstore client
  app/models/annotation/WKRemoteTracingStoreClient.scala
Labels: backend

#8516 remove synchronized blocks for putBuffer, it is not thread safe anyway
  webknossos-tracingstore/app/com/scalableminds/webknossos/tracingstore/tracings/FossilDBPutBuffer.scala
Labels: backend, refactoring

#8529 Reorder CI steps, down from 10m to 7m
  .github/workflows/build_test_deploy.yml
  build.sbt
Labels: CI

#8514 Auto correct dataset name in view URL
  CHANGELOG.unreleased.md
  frontend/javascripts/libs/window.ts
  frontend/javascripts/messages.tsx
  frontend/javascripts/oxalis/controller/url_manager.ts
  frontend/javascripts/oxalis/model_initialization.ts
  frontend/javascripts/oxalis/view/left-border-tabs/layer_settings_tab.tsx
  frontend/javascripts/test/controller/url_manager.spec.ts
  frontend/javascripts/test/model/model.spec.ts
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/libs/nml.spec.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/libs/nml.spec.js.snap
  tools/nml/nmlgenerator.py
Labels: bug, enhancement, frontend

#8540 Apply proper antd theming to Welcome Toast
  frontend/javascripts/oxalis/view/novel_user_experiences/welcome_toast.tsx
Labels: frontend

#8485 Allow to mirror datasets
  CHANGELOG.unreleased.md
  frontend/javascripts/dashboard/dataset/dataset_rotation_form_item.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx
  frontend/javascripts/dashboard/dataset/dataset_settings_view.tsx
  frontend/javascripts/oxalis/model/accessors/dataset_layer_transformation_accessor.ts
Labels: frontend, new feature

#8545 Enable test coverage comparison
  .github/workflows/build_test_deploy.yml
  frontend/javascripts/oxalis/view/right-border-tabs/advanced_search_popover.tsx
Labels: testing

#8548 Fix legacy links
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/model/accessors/dataset_accessor.ts
Labels: bug, frontend

#8550 Fix adding new layer via advanced dataset settings tab
  CHANGELOG.unreleased.md
  frontend/javascripts/dashboard/dataset/dataset_settings_data_tab.tsx
Labels: bug, frontend

#8527 Do not fetch job costs for free jobs
  frontend/javascripts/oxalis/view/action-bar/starting_job_modals.tsx
Labels: bug, frontend

#8552 Update DEV_INSTALL.md to mention new node version
  DEV_INSTALL.md
Labels: documentation

#8539 Include intensityRange, color, isInverted & gammaCorrectionValue in sharing links
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/controller/url_manager.ts
  frontend/javascripts/oxalis/model_initialization.ts
  frontend/javascripts/types/schemas/url_state.schema.ts
Labels: enhancement, frontend

#8533 In Multi-NML upload, keep description if unambiguous. In update route, don’t touch it
  CHANGELOG.unreleased.md
  app/controllers/AnnotationController.scala
  app/controllers/AnnotationIOController.scala
Labels: enhancement, backend, refactoring

#8543 Convert E2E tests to vitest
  .github/workflows/build_test_deploy.yml
  CHANGELOG.unreleased.md
  frontend/javascripts/admin/api/tasks.ts
  frontend/javascripts/oxalis/model/helpers/proto_helpers.ts
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/annotations.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/datasets.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/folders.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/misc.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/projects.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/scripts.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/tasks.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/tasktypes.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/teams.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/timetracking.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/users.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/annotations.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/datasets.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/folders.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/misc.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/projects.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/scripts.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/tasks.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/tasktypes.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/teams.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/teamstructure.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/timetracking.e2e.ts
  frontend/javascripts/test/backend-snapshot-tests/users.e2e.ts
  frontend/javascripts/test/e2e-setup.ts
  frontend/javascripts/test/global_mocks.ts
  frontend/javascripts/test/helpers/apiHelpers.ts
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/annotations.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/datasets.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/folders.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/folders.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/misc.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/misc.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/projects.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/projects.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/scripts.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/scripts.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/tasks.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/tasktypes.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/teams.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/teams.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/timetracking.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/timetracking.e2e.js.snap
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/users.e2e.js.md
  frontend/javascripts/test/snapshots/public-test/test-bundle/test/backend-snapshot-tests/users.e2e.js.snap
  package.json
  tools/extractReleaseNotes.js
  tools/postgres/dbtool.js
  tools/test.sh
  vitest.config.ts
  yarn.lock
Labels: frontend, testing

#8553 Update screenshot tests to use Vitest
  CHANGELOG.unreleased.md
  frontend/javascripts/test/backend-snapshot-tests/__snapshots__/projects.e2e.ts.snap
  frontend/javascripts/test/backend-snapshot-tests/projects.e2e.ts
  frontend/javascripts/test/e2e-setup.ts
  frontend/javascripts/test/puppeteer/dataset_rendering.screenshot.ts
  frontend/javascripts/test/puppeteer/dataset_rendering.wkorg_screenshot.ts
  frontend/javascripts/test/puppeteer/dataset_rendering_helpers.ts
  frontend/javascripts/test/puppeteer/dtype_datasets_rendering.screenshot.ts
  package.json
  tools/test.sh
  vitest.config.ts
  yarn.lock
Labels: frontend, testing

#8551 In Data Loading, Clip to Layer BoundingBox
  CHANGELOG.unreleased.md
  util/src/main/scala/com/scalableminds/util/geometry/BoundingBox.scala
  util/src/main/scala/com/scalableminds/util/geometry/Vec3Int.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/requests/Cuboid.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/models/requests/DataServiceRequests.scala
  webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/BinaryDataService.scala
Labels: bug, enhancement, backend

#8562 Enforce rerendering trees color picker on selected item change
  CHANGELOG.unreleased.md
  frontend/javascripts/oxalis/view/right-border-tabs/trees_tab/tree_hierarchy_renderers.tsx
Labels: bug, frontend

#8575 Fix screenshot tests
  .github/workflows/nightly.yml
  .github/workflows/wkorg-nightly.yaml
Labels: frontend, testing

#8557 Unify json parsing code in WKRemoteDataStoreController
  app/controllers/WKRemoteDataStoreController.scala
Labels: backend, refactoring

#8493 Transform meshes and bboxes according to transformation settings
  frontend/javascripts/admin/voxelytics/ai_model_list_view.tsx
  frontend/javascripts/oxalis/controller/scene_controller.ts
  frontend/javascripts/oxalis/controller/segment_mesh_controller.ts
  frontend/javascripts/oxalis/model/accessors/disabled_tool_accessor.ts
  frontend/javascripts/oxalis/model/accessors/skeletontracing_accessor.ts
  frontend/javascripts/oxalis/model/reducers/skeletontracing_reducer.ts
  frontend/javascripts/oxalis/model/sagas/mesh_saga.ts
  frontend/javascripts/oxalis/model/sagas/proofread_saga.ts
  frontend/javascripts/oxalis/view/context_menu.tsx
  frontend/javascripts/oxalis/view/plane_view.ts
  frontend/javascripts/oxalis/view/right-border-tabs/trees_tab/skeleton_tab_view.tsx
  frontend/javascripts/test/sagas/annotation_tool_disabled_info.spec.ts
Labels: bug, frontend

#8584 Fix broken proofreading tool links in docs
  docs/proofreading/split_segments_toolkit.md
  docs/volume_annotation/tools.md
Labels: documentation
